import UEOT.V3.QSDPerron
import UEOT.V3.EvolutionReproductiveMartingale
import Mathlib.Tactic

/-!
# UEOT Core compression — positive eigenstructure calculus

This module tests M-PE-01 as a genuine cross-family generator.

The common primitive is a positive right eigenstructure for a finite positive
operator.  The same right eigenrelation has two independently useful
consequences:

* reweighting a kernel by the positive eigenvector gives a normalized Doob
  transform;
* evaluating a row state against the same eigenvector scales exactly under one
  mean-evolution step, and therefore yields a normalized martingale under a
  conditional-mean evolution law.

A normalized positive left eigenvector adds the QSD and invariant-law side of
the calculus.  Perron--Frobenius existence, primitive-matrix rank-one
asymptotics, and compact-resolvent spectral-gap estimates are deliberately not
part of this generator.
-/

namespace UEOT.V3.Compression.PositiveEigenstructure

noncomputable section

open MeasureTheory
open scoped BigOperators

universe uI uΩ

variable {I : Type uI} [Fintype I]

local instance : DecidableEq I := Classical.decEq I

/-- Row action of a finite matrix. -/
def rowApply (q : I → ℝ) (M : Matrix I I ℝ) (j : I) : ℝ :=
  ∑ i : I, q i * M i j

/-- Column action of a finite matrix. -/
def colApply (M : Matrix I I ℝ) (h : I → ℝ) (i : I) : ℝ :=
  ∑ j : I, M i j * h j

/-- Positive right eigenstructure, the common primitive used by both QSD and
reproductive-value specializations. -/
structure RightEigenData (M : Matrix I I ℝ) where
  scale : ℝ
  vector : I → ℝ
  scale_pos : 0 < scale
  vector_pos : ∀ i, 0 < vector i
  eigen : ∀ i, colApply M vector i = scale * vector i

/-- Positive left/right eigenstructure with the normalizations needed for a
probability QSD and the Doob stationary law. -/
structure BiEigenData (M : Matrix I I ℝ) where
  right : RightEigenData M
  left : I → ℝ
  matrix_nonneg : ∀ i j, 0 ≤ M i j
  left_nonneg : ∀ i, 0 ≤ left i
  left_sum_one : ∑ i : I, left i = 1
  pairing_sum_one : ∑ i : I, left i * right.vector i = 1
  left_eigen : ∀ j, rowApply left M j = right.scale * left j

/-- Doob transform generated by positive right eigenstructure. -/
def hTransform {M : Matrix I I ℝ} (D : RightEigenData M) : Matrix I I ℝ :=
  fun i j => M i j * D.vector j / (D.scale * D.vector i)

/-- Paired left/right weight. -/
def invariantWeight {M : Matrix I I ℝ} (D : BiEigenData M) : I → ℝ :=
  fun i => D.left i * D.right.vector i

/-- A positive right eigenvector normalizes the Doob transform row by row. -/
theorem hTransform_row_sum
    {M : Matrix I I ℝ} (D : RightEigenData M) :
    ∀ i, ∑ j : I, hTransform D i j = 1 := by
  intro i
  unfold hTransform
  have hden : D.scale * D.vector i ≠ 0 :=
    mul_ne_zero D.scale_pos.ne' (D.vector_pos i).ne'
  calc
    (∑ j : I, M i j * D.vector j /
        (D.scale * D.vector i)) =
        (∑ j : I, M i j * D.vector j) /
          (D.scale * D.vector i) := by
            rw [Finset.sum_div]
    _ = colApply M D.vector i /
          (D.scale * D.vector i) := by rfl
    _ = (D.scale * D.vector i) /
          (D.scale * D.vector i) := by rw [D.eigen i]
    _ = 1 := div_self hden

/-- Nonnegative matrix entries and a positive right eigenvector give a
nonnegative Doob transform. -/
theorem hTransform_nonneg
    {M : Matrix I I ℝ} (D : RightEigenData M)
    (hM : ∀ i j, 0 ≤ M i j) :
    ∀ i j, 0 ≤ hTransform D i j := by
  intro i j
  exact div_nonneg
    (mul_nonneg (hM i j) (D.vector_pos j).le)
    (mul_nonneg D.scale_pos.le (D.vector_pos i).le)

/-- The right eigenrelation is equivalently a scaling law for the linear
readout z ↦ z·h. -/
def readoutCLM {M : Matrix I I ℝ} (D : RightEigenData M) :
    (I → ℝ) →L[ℝ] ℝ :=
  LinearMap.toContinuousLinearMap
    { toFun := fun z => ∑ i : I, z i * D.vector i
      map_add' := by
        intro x y
        simp only [Pi.add_apply]
        rw [← Finset.sum_add_distrib]
        apply Finset.sum_congr rfl
        intro i hi
        ring
      map_smul' := by
        intro c x
        simp only [Pi.smul_apply, RingHom.id_apply, smul_eq_mul]
        rw [Finset.mul_sum]
        apply Finset.sum_congr rfl
        intro i hi
        ring }

@[simp] theorem readoutCLM_apply
    {M : Matrix I I ℝ} (D : RightEigenData M) (z : I → ℝ) :
    readoutCLM D z = ∑ i : I, z i * D.vector i := rfl

/-- One matrix step scales the right-eigenvector readout exactly. -/
theorem readout_vecMul
    {M : Matrix I I ℝ} (D : RightEigenData M) (z : I → ℝ) :
    readoutCLM D (Matrix.vecMul z M) = D.scale * readoutCLM D z := by
  simp only [readoutCLM_apply, Matrix.vecMul, dotProduct]
  calc
    (∑ j : I, (∑ i : I, z i * M i j) * D.vector j) =
        ∑ j : I, ∑ i : I, (z i * M i j) * D.vector j := by
          apply Finset.sum_congr rfl
          intro j hj
          rw [Finset.sum_mul]
    _ = ∑ i : I, ∑ j : I, (z i * M i j) * D.vector j := by
          rw [Finset.sum_comm]
    _ = ∑ i : I, z i * (∑ j : I, M i j * D.vector j) := by
          apply Finset.sum_congr rfl
          intro i hi
          rw [Finset.mul_sum]
          apply Finset.sum_congr rfl
          intro j hj
          ring
    _ = ∑ i : I, z i * (D.scale * D.vector i) := by
          apply Finset.sum_congr rfl
          intro i hi
          rw [← D.eigen i]
          rfl
    _ = D.scale * ∑ i : I, z i * D.vector i := by
          rw [Finset.mul_sum]
          apply Finset.sum_congr rfl
          intro i hi
          ring

/-- Associativity of row action. -/
theorem rowApply_mul
    (q : I → ℝ) (A B : Matrix I I ℝ) :
    rowApply q (A * B) = rowApply (fun k => rowApply q A k) B := by
  funext j
  unfold rowApply
  simp only [Matrix.mul_apply]
  calc
    (∑ i : I, q i * ∑ k : I, A i k * B k j) =
        ∑ i : I, ∑ k : I, (q i * A i k) * B k j := by
          apply Finset.sum_congr rfl
          intro i hi
          rw [Finset.mul_sum]
          apply Finset.sum_congr rfl
          intro k hk
          ring
    _ = ∑ k : I, ∑ i : I, (q i * A i k) * B k j := by
          rw [Finset.sum_comm]
    _ = ∑ k : I, (∑ i : I, q i * A i k) * B k j := by
          apply Finset.sum_congr rfl
          intro k hk
          rw [Finset.sum_mul]
    _ = ∑ k : I, rowApply q A k * B k j := by rfl

/-- A left eigenrelation propagates through every finite power. -/
theorem left_pow
    {M : Matrix I I ℝ} (D : BiEigenData M) :
    ∀ n j, rowApply D.left (M ^ n) j =
      D.right.scale ^ n * D.left j := by
  intro n
  induction n with
  | zero =>
      intro j
      simp [rowApply, Matrix.one_apply]
  | succ n ih =>
      intro j
      rw [pow_succ, rowApply_mul]
      have hfun :
          (fun k => rowApply D.left (M ^ n) k) =
            fun k => D.right.scale ^ n * D.left k := by
        funext k
        exact ih k
      rw [hfun]
      calc
        rowApply (fun k => D.right.scale ^ n * D.left k) M j =
            D.right.scale ^ n * rowApply D.left M j := by
              unfold rowApply
              rw [Finset.mul_sum]
              apply Finset.sum_congr rfl
              intro k hk
              ring
        _ = D.right.scale ^ n *
              (D.right.scale * D.left j) := by rw [D.left_eigen j]
        _ = D.right.scale ^ (n + 1) * D.left j := by
              rw [pow_succ]
              ring

/-- The normalized left eigenlaw is unchanged after conditioning by its
survival scale. -/
theorem normalized_left_pow
    {M : Matrix I I ℝ} (D : BiEigenData M) :
    ∀ n j, rowApply D.left (M ^ n) j / D.right.scale ^ n =
      D.left j := by
  intro n j
  rw [left_pow D n j]
  have hn : D.right.scale ^ n ≠ 0 :=
    pow_ne_zero _ D.right.scale_pos.ne'
  field_simp [hn]

/-- Total left mass after n steps is exactly the eigen-scale to the n-th
power. -/
theorem survival_mass_pow
    {M : Matrix I I ℝ} (D : BiEigenData M) :
    ∀ n, ∑ j : I, rowApply D.left (M ^ n) j =
      D.right.scale ^ n := by
  intro n
  simp_rw [left_pow D n]
  rw [← Finset.mul_sum]
  simp [D.left_sum_one]

/-- The paired left/right weight is normalized. -/
theorem invariantWeight_sum
    {M : Matrix I I ℝ} (D : BiEigenData M) :
    ∑ i : I, invariantWeight D i = 1 := by
  simpa [invariantWeight] using D.pairing_sum_one

/-- The paired left/right weight is invariant for the Doob transform. -/
theorem invariantWeight_stationary
    {M : Matrix I I ℝ} (D : BiEigenData M) :
    ∀ j,
      rowApply (invariantWeight D) (hTransform D.right) j =
        invariantWeight D j := by
  intro j
  unfold rowApply invariantWeight hTransform
  have hscale : D.right.scale ≠ 0 := D.right.scale_pos.ne'
  calc
    (∑ i : I,
        (D.left i * D.right.vector i) *
          (M i j * D.right.vector j /
            (D.right.scale * D.right.vector i))) =
        ∑ i : I,
          (D.left i * M i j) *
            (D.right.vector j / D.right.scale) := by
              apply Finset.sum_congr rfl
              intro i hi
              have hi : D.right.vector i ≠ 0 :=
                (D.right.vector_pos i).ne'
              field_simp [hscale, hi]
    _ = (∑ i : I, D.left i * M i j) *
          (D.right.vector j / D.right.scale) := by
            rw [Finset.sum_mul]
    _ = rowApply D.left M j *
          (D.right.vector j / D.right.scale) := by rfl
    _ = (D.right.scale * D.left j) *
          (D.right.vector j / D.right.scale) := by
            rw [D.left_eigen j]
    _ = D.left j * D.right.vector j := by
          field_simp [hscale]

/-- Full finite QSD/Doob algebra generated by positive left/right
eigenstructure. -/
theorem qsdDoob_bundle
    {M : Matrix I I ℝ} (D : BiEigenData M) :
    (∀ n j,
      rowApply D.left (M ^ n) j / D.right.scale ^ n = D.left j) ∧
    (∀ n, ∑ j : I, rowApply D.left (M ^ n) j = D.right.scale ^ n) ∧
    (∀ i, ∑ j : I, hTransform D.right i j = 1) ∧
    (∀ i j, 0 ≤ hTransform D.right i j) ∧
    (∑ i : I, invariantWeight D i = 1) ∧
    (∀ i, 0 ≤ invariantWeight D i) ∧
    (∀ j,
      rowApply (invariantWeight D) (hTransform D.right) j =
        invariantWeight D j) := by
  refine ⟨normalized_left_pow D, survival_mass_pow D,
    hTransform_row_sum D.right, hTransform_nonneg D.right D.matrix_nonneg,
    invariantWeight_sum D, ?_, invariantWeight_stationary D⟩
  intro i
  exact mul_nonneg (D.left_nonneg i) (D.right.vector_pos i).le

/-- Substochastic rows force the normalized left eigen-scale to be at most
one. -/
theorem scale_le_one_of_substochastic
    {M : Matrix I I ℝ} (D : BiEigenData M)
    (hrows : ∀ i, ∑ j : I, M i j ≤ 1) :
    D.right.scale ≤ 1 := by
  have hmass : (∑ j : I, rowApply D.left M j) = D.right.scale := by
    simp_rw [D.left_eigen]
    rw [← Finset.mul_sum, D.left_sum_one, mul_one]
  calc
    D.right.scale = ∑ j : I, rowApply D.left M j := hmass.symm
    _ = ∑ i : I, D.left i * (∑ j : I, M i j) := by
      unfold rowApply
      calc
        (∑ j : I, ∑ i : I, D.left i * M i j) =
            ∑ i : I, ∑ j : I, D.left i * M i j := by
              rw [Finset.sum_comm]
        _ = ∑ i : I, D.left i * (∑ j : I, M i j) := by
              apply Finset.sum_congr rfl
              intro i hi
              rw [Finset.mul_sum]
    _ ≤ ∑ i : I, D.left i * 1 := by
      apply Finset.sum_le_sum
      intro i hi
      exact mul_le_mul_of_nonneg_left (hrows i) (D.left_nonneg i)
    _ = 1 := by simp [D.left_sum_one]

/-! ## Stochastic right-eigenfunction transport -/

variable {Ω : Type uΩ} {m0 : MeasurableSpace Ω}
variable {μ : Measure Ω} [IsProbabilityMeasure μ]
variable {ℱ : Filtration ℕ m0}

/-- Normalized right-eigenvector readout. -/
def W
    {M : Matrix I I ℝ} (D : RightEigenData M)
    (Z : ℕ → Ω → (I → ℝ)) (n : ℕ) (ω : Ω) : ℝ :=
  (D.scale ^ n)⁻¹ * readoutCLM D (Z n ω)

/-- Conditional mean evolution plus the right eigenrelation gives the scalar
one-step conditional mean law. -/
theorem condExp_readout
    {M : Matrix I I ℝ} (D : RightEigenData M)
    (Z : ℕ → Ω → (I → ℝ))
    (hZint : ∀ n, Integrable (Z n) μ)
    (hmean : ∀ n,
      μ[Z (n + 1) | ℱ n] =ᵐ[μ]
        fun ω => Matrix.vecMul (Z n ω) M)
    (n : ℕ) :
    μ[fun ω => readoutCLM D (Z (n + 1) ω) | ℱ n] =ᵐ[μ]
      fun ω => D.scale * readoutCLM D (Z n ω) := by
  have hcomm :=
    ContinuousLinearMap.comp_condExp_comm
      (m := ℱ n) (hZint (n + 1)) (readoutCLM D)
  calc
    μ[fun ω => readoutCLM D (Z (n + 1) ω) | ℱ n]
        =ᵐ[μ] (readoutCLM D) ∘ μ[Z (n + 1) | ℱ n] := hcomm.symm
    _ =ᵐ[μ] fun ω => readoutCLM D (Matrix.vecMul (Z n ω) M) := by
      exact (hmean n).mono fun ω hω => congrArg (readoutCLM D) hω
    _ =ᵐ[μ] fun ω => D.scale * readoutCLM D (Z n ω) := by
      exact Filter.Eventually.of_forall fun ω => readout_vecMul D (Z n ω)

/-- Normalization by the eigen-scale turns the scalar recursion into the
martingale one-step identity. -/
theorem condExp_W_succ
    {M : Matrix I I ℝ} (D : RightEigenData M)
    (Z : ℕ → Ω → (I → ℝ))
    (hZint : ∀ n, Integrable (Z n) μ)
    (hmean : ∀ n,
      μ[Z (n + 1) | ℱ n] =ᵐ[μ]
        fun ω => Matrix.vecMul (Z n ω) M)
    (n : ℕ) :
    μ[W D Z (n + 1) | ℱ n] =ᵐ[μ] W D Z n := by
  have hscalar := condExp_readout D Z hZint hmean n
  have hsmul := condExp_smul (μ := μ) ((D.scale ^ (n + 1))⁻¹)
    (fun ω => readoutCLM D (Z (n + 1) ω)) (ℱ n)
  have hscale : D.scale ≠ 0 := D.scale_pos.ne'
  change
    μ[fun ω => (D.scale ^ (n + 1))⁻¹ * readoutCLM D (Z (n + 1) ω) | ℱ n]
      =ᵐ[μ] fun ω => (D.scale ^ n)⁻¹ * readoutCLM D (Z n ω)
  calc
    μ[fun ω => (D.scale ^ (n + 1))⁻¹ * readoutCLM D (Z (n + 1) ω) | ℱ n]
        =ᵐ[μ] fun ω => (D.scale ^ (n + 1))⁻¹ *
          μ[fun ω => readoutCLM D (Z (n + 1) ω) | ℱ n] ω := by
            change
              μ[((D.scale ^ (n + 1))⁻¹) •
                (fun ω => readoutCLM D (Z (n + 1) ω)) | ℱ n]
                =ᵐ[μ] ((D.scale ^ (n + 1))⁻¹) •
                  μ[fun ω => readoutCLM D (Z (n + 1) ω) | ℱ n]
            exact hsmul
    _ =ᵐ[μ] fun ω => (D.scale ^ (n + 1))⁻¹ *
          (D.scale * readoutCLM D (Z n ω)) := by
            exact hscalar.mono fun ω hω =>
              congrArg (fun x => (D.scale ^ (n + 1))⁻¹ * x) hω
    _ =ᵐ[μ] fun ω => (D.scale ^ n)⁻¹ * readoutCLM D (Z n ω) := by
      exact Filter.Eventually.of_forall fun ω => by
        rw [pow_succ]
        field_simp [hscale]

/-- Adaptedness passes through the scalar right-eigenvector readout. -/
theorem stronglyAdapted_W
    {M : Matrix I I ℝ} (D : RightEigenData M)
    (Z : ℕ → Ω → (I → ℝ))
    (hZadapt : StronglyAdapted ℱ Z) :
    StronglyAdapted ℱ (W D Z) := by
  intro n
  have hv : StronglyMeasurable[ℱ n] (fun ω => readoutCLM D (Z n ω)) :=
    (readoutCLM D).continuous.comp_stronglyMeasurable (hZadapt n)
  exact (continuous_const.mul continuous_id).comp_stronglyMeasurable hv

/-- Integrability passes through the finite continuous-linear readout. -/
theorem integrable_W
    {M : Matrix I I ℝ} (D : RightEigenData M)
    (Z : ℕ → Ω → (I → ℝ))
    (hZint : ∀ n, Integrable (Z n) μ) :
    ∀ n, Integrable (W D Z n) μ := by
  intro n
  have hv : Integrable (fun ω => readoutCLM D (Z n ω)) μ :=
    (readoutCLM D).integrable_comp (hZint n)
  change Integrable
    (fun ω => (D.scale ^ n)⁻¹ * readoutCLM D (Z n ω)) μ
  exact hv.const_mul ((D.scale ^ n)⁻¹)

/-- Positive state coordinates and a positive eigenvector make W
nonnegative. -/
theorem W_nonneg
    {M : Matrix I I ℝ} (D : RightEigenData M)
    (Z : ℕ → Ω → (I → ℝ))
    (hZnonneg : ∀ n ω i, 0 ≤ Z n ω i) :
    ∀ n ω, 0 ≤ W D Z n ω := by
  intro n ω
  have hscale : 0 ≤ (D.scale ^ n)⁻¹ :=
    inv_nonneg.mpr (pow_nonneg D.scale_pos.le n)
  have hsum : 0 ≤ readoutCLM D (Z n ω) := by
    simp only [readoutCLM_apply]
    exact Finset.sum_nonneg fun i hi =>
      mul_nonneg (hZnonneg n ω i) (D.vector_pos i).le
  exact mul_nonneg hscale hsum

/-- Conditional mean evolution along a positive right eigendirection generates
a normalized martingale. -/
theorem rightEigen_martingale
    {M : Matrix I I ℝ} (D : RightEigenData M)
    (Z : ℕ → Ω → (I → ℝ))
    (hZadapt : StronglyAdapted ℱ Z)
    (hZint : ∀ n, Integrable (Z n) μ)
    (hmean : ∀ n,
      μ[Z (n + 1) | ℱ n] =ᵐ[μ]
        fun ω => Matrix.vecMul (Z n ω) M) :
    Martingale (W D Z) ℱ μ := by
  apply martingale_nat (stronglyAdapted_W D Z hZadapt)
    (integrable_W D Z hZint)
  intro n
  exact (condExp_W_succ D Z hZint hmean n).symm

/-- With deterministic initial counts, the normalized martingale has constant
expected right-eigenvector readout. -/
theorem rightEigen_expectation
    {M : Matrix I I ℝ} (D : RightEigenData M)
    (Z : ℕ → Ω → (I → ℝ))
    (z0 : I → ℕ)
    (hZadapt : StronglyAdapted ℱ Z)
    (hZint : ∀ n, Integrable (Z n) μ)
    (hmean : ∀ n,
      μ[Z (n + 1) | ℱ n] =ᵐ[μ]
        fun ω => Matrix.vecMul (Z n ω) M)
    (hinit : ∀ ω i, Z 0 ω i = (z0 i : ℝ)) :
    ∀ n, ∫ ω, W D Z n ω ∂μ =
      ∑ i : I, (z0 i : ℝ) * D.vector i := by
  intro n
  have hmart := rightEigen_martingale D Z hZadapt hZint hmean
  have hEq := hmart.setIntegral_eq (i := 0) (j := n) (Nat.zero_le n)
    (s := Set.univ) MeasurableSet.univ
  have h0 :
      (fun ω => W D Z 0 ω) =
        fun _ => ∑ i : I, (z0 i : ℝ) * D.vector i := by
    funext ω
    simp only [W, pow_zero, inv_one, one_mul, readoutCLM_apply]
    apply Finset.sum_congr rfl
    intro i hi
    rw [hinit ω i]
  have hEq' : ∫ ω, W D Z 0 ω ∂μ = ∫ ω, W D Z n ω ∂μ := by
    simpa only [Measure.restrict_univ] using hEq
  have hW0 :
      ∫ ω, W D Z 0 ω ∂μ =
        ∑ i : I, (z0 i : ℝ) * D.vector i := by
    rw [h0]
    simp
  exact hEq'.symm.trans hW0

/-- Full stochastic bundle generated by positive right eigenstructure. -/
theorem stochasticRightEigen_bundle
    {M : Matrix I I ℝ} (D : RightEigenData M)
    (Z : ℕ → Ω → (I → ℝ))
    (z0 : I → ℕ)
    (hZnonneg : ∀ n ω i, 0 ≤ Z n ω i)
    (hZadapt : StronglyAdapted ℱ Z)
    (hZint : ∀ n, Integrable (Z n) μ)
    (hmean : ∀ n,
      μ[Z (n + 1) | ℱ n] =ᵐ[μ]
        fun ω => Matrix.vecMul (Z n ω) M)
    (hinit : ∀ ω i, Z 0 ω i = (z0 i : ℝ)) :
    Martingale (W D Z) ℱ μ ∧
      (∀ n ω, 0 ≤ W D Z n ω) ∧
      (∀ n, Integrable (W D Z n) μ) ∧
      (∀ n, ∫ ω, W D Z n ω ∂μ =
        ∑ i : I, (z0 i : ℝ) * D.vector i) := by
  refine ⟨rightEigen_martingale D Z hZadapt hZint hmean,
    W_nonneg D Z hZnonneg, integrable_W D Z hZint, ?_⟩
  exact rightEigen_expectation D Z z0 hZadapt hZint hmean hinit

/-! ## Exact source-facing specializations -/

/-- P-QSD-02 reconstructed from M-PE-01 positive bi-eigenstructure. -/
theorem p_qsd_02_via_positiveEigenstructure
    (Q : Matrix I I ℝ) (q h : I → ℝ) (ρ : ℝ)
    (hQ : ∀ i j, 0 ≤ Q i j)
    (hq0 : ∀ i, 0 ≤ q i)
    (hρ : 0 < ρ)
    (hh : ∀ i, 0 < h i)
    (hqsum : ∑ i : I, q i = 1)
    (hqh : ∑ i : I, q i * h i = 1)
    (hleft : ∀ j, UEOT.V3.QSDPerron.rowApply q Q j = ρ * q j)
    (hright : ∀ i, UEOT.V3.QSDPerron.colApply Q h i = ρ * h i) :
    (∀ n j,
      UEOT.V3.QSDPerron.rowApply q (Q ^ n) j / ρ ^ n = q j) ∧
    (∀ n, ∑ j : I, UEOT.V3.QSDPerron.rowApply q (Q ^ n) j = ρ ^ n) ∧
    (∀ i, ∑ j : I, UEOT.V3.QSDPerron.doobTransform Q h ρ i j = 1) ∧
    (∀ i j, 0 ≤ UEOT.V3.QSDPerron.doobTransform Q h ρ i j) ∧
    (∑ i : I, UEOT.V3.QSDPerron.doobInvariant q h i = 1) ∧
    (∀ i, 0 ≤ UEOT.V3.QSDPerron.doobInvariant q h i) ∧
    (∀ j,
      UEOT.V3.QSDPerron.rowApply
        (UEOT.V3.QSDPerron.doobInvariant q h)
        (UEOT.V3.QSDPerron.doobTransform Q h ρ) j =
          UEOT.V3.QSDPerron.doobInvariant q h j) := by
  let R : RightEigenData Q :=
    { scale := ρ
      vector := h
      scale_pos := hρ
      vector_pos := hh
      eigen := by
        intro i
        simpa [colApply, UEOT.V3.QSDPerron.colApply] using hright i }
  let D : BiEigenData Q :=
    { right := R
      left := q
      matrix_nonneg := hQ
      left_nonneg := hq0
      left_sum_one := hqsum
      pairing_sum_one := hqh
      left_eigen := by
        intro j
        simpa [rowApply, UEOT.V3.QSDPerron.rowApply, R] using hleft j }
  have hbundle := qsdDoob_bundle D
  simpa [D, R, rowApply, hTransform, invariantWeight,
    UEOT.V3.QSDPerron.rowApply,
    UEOT.V3.QSDPerron.doobTransform,
    UEOT.V3.QSDPerron.doobInvariant] using hbundle

/-- Killed/substochastic P-QSD-02 wrapper, including rho ≤ 1. -/
theorem p_qsd_02_killed_via_positiveEigenstructure
    (Q : Matrix I I ℝ) (q h : I → ℝ) (ρ : ℝ)
    (hQ : ∀ i j, 0 ≤ Q i j)
    (hrows : ∀ i, ∑ j : I, Q i j ≤ 1)
    (hq0 : ∀ i, 0 ≤ q i)
    (hρ : 0 < ρ)
    (hh : ∀ i, 0 < h i)
    (hqsum : ∑ i : I, q i = 1)
    (hqh : ∑ i : I, q i * h i = 1)
    (hleft : ∀ j, UEOT.V3.QSDPerron.rowApply q Q j = ρ * q j)
    (hright : ∀ i, UEOT.V3.QSDPerron.colApply Q h i = ρ * h i) :
    ρ ≤ 1 ∧
    (∀ n j,
      UEOT.V3.QSDPerron.rowApply q (Q ^ n) j / ρ ^ n = q j) ∧
    (∀ n, ∑ j : I, UEOT.V3.QSDPerron.rowApply q (Q ^ n) j = ρ ^ n) ∧
    (∀ i, ∑ j : I, UEOT.V3.QSDPerron.doobTransform Q h ρ i j = 1) ∧
    (∀ i j, 0 ≤ UEOT.V3.QSDPerron.doobTransform Q h ρ i j) ∧
    (∑ i : I, UEOT.V3.QSDPerron.doobInvariant q h i = 1) ∧
    (∀ i, 0 ≤ UEOT.V3.QSDPerron.doobInvariant q h i) ∧
    (∀ j,
      UEOT.V3.QSDPerron.rowApply
        (UEOT.V3.QSDPerron.doobInvariant q h)
        (UEOT.V3.QSDPerron.doobTransform Q h ρ) j =
          UEOT.V3.QSDPerron.doobInvariant q h j) := by
  let R : RightEigenData Q :=
    { scale := ρ
      vector := h
      scale_pos := hρ
      vector_pos := hh
      eigen := by
        intro i
        simpa [colApply, UEOT.V3.QSDPerron.colApply] using hright i }
  let D : BiEigenData Q :=
    { right := R
      left := q
      matrix_nonneg := hQ
      left_nonneg := hq0
      left_sum_one := hqsum
      pairing_sum_one := hqh
      left_eigen := by
        intro j
        simpa [rowApply, UEOT.V3.QSDPerron.rowApply, R] using hleft j }
  have hscale := scale_le_one_of_substochastic D hrows
  have hbundle := qsdDoob_bundle D
  refine ⟨?_, ?_⟩
  · simpa [D, R] using hscale
  · simpa [D, R, rowApply, hTransform, invariantWeight,
      UEOT.V3.QSDPerron.rowApply,
      UEOT.V3.QSDPerron.doobTransform,
      UEOT.V3.QSDPerron.doobInvariant] using hbundle

/-- P-EVO-04 reconstructed from the stochastic right-eigenstructure theorem. -/
theorem p_evo_04_via_positiveEigenstructure
    (M : Matrix I I ℝ) (Rscale : ℝ) (r : I → ℝ)
    (Z : ℕ → Ω → (I → ℝ))
    (z0 : I → ℕ)
    (hR : 0 < Rscale)
    (hr : ∀ i, 0 < r i)
    (hZnonneg : ∀ n ω i, 0 ≤ Z n ω i)
    (hZadapt : StronglyAdapted ℱ Z)
    (hZint : ∀ n, Integrable (Z n) μ)
    (hmean : ∀ n,
      μ[Z (n + 1) | ℱ n] =ᵐ[μ]
        fun ω => Matrix.vecMul (Z n ω) M)
    (hperron : ∀ i, ∑ j : I, M i j * r j = Rscale * r i)
    (hinit : ∀ ω i, Z 0 ω i = (z0 i : ℝ)) :
    Martingale
        (UEOT.V3.EvolutionReproductiveMartingale.W Rscale r Z) ℱ μ ∧
      (∀ n ω,
        0 ≤ UEOT.V3.EvolutionReproductiveMartingale.W Rscale r Z n ω) ∧
      (∀ n,
        Integrable
          (UEOT.V3.EvolutionReproductiveMartingale.W Rscale r Z n) μ) ∧
      (∀ n,
        ∫ ω, UEOT.V3.EvolutionReproductiveMartingale.W Rscale r Z n ω ∂μ =
          ∑ i : I, (z0 i : ℝ) * r i) := by
  let D : RightEigenData M :=
    { scale := Rscale
      vector := r
      scale_pos := hR
      vector_pos := hr
      eigen := by
        intro i
        simpa [colApply] using hperron i }
  have hbundle :=
    stochasticRightEigen_bundle D Z z0 hZnonneg hZadapt hZint hmean hinit
  have hW :
      W D Z = UEOT.V3.EvolutionReproductiveMartingale.W Rscale r Z := by
    funext n ω
    simp [W, UEOT.V3.EvolutionReproductiveMartingale.W,
      UEOT.V3.EvolutionReproductiveMartingale.reproValueCLM_apply, D]
  rw [hW] at hbundle
  simpa [D] using hbundle

end

end UEOT.V3.Compression.PositiveEigenstructure
