import UEOT.V3.Compression.TheoryCompletion.ScientificClosure.SISCEmissionTiming
import UEOT.V3.Compression.TheoryCompletion.ScientificClosure.SISCFiniteStochasticQuotient
import Mathlib.Tactic

/-!
# UMC: future-word observability sufficient for finite stochastic Markov descent

The six-state mixture-alias counterexample shows that observational equality
does NOT imply strong Markov lumpability without further observability.
Here all probe tests come from the same source kernel future trace functions.
Their indicator-spanning power turns all-future signature equality into
one-step source-class mass equality, with no independently assumed
equality of test expectations or prior Markov quotient. We keep the
pre-action emission convention explicit.
-/

namespace UEOT.V3.Compression.TheoryCompletion.UnifiedClosure

open UEOT.V3.Compression.TheoryCompletion.ScientificClosure.SISC
open UEOT.V3.Compression.RecursiveSufficientState

universe uX uA uO uI

noncomputable abbrev stochasticFuture
    {X : Type uX} {A : Type uA} {O : Type uO}
    [Fintype X] [DecidableEq O]
    (K : FiniteControlledStochasticKernel X A)
    (read : X → O) : X → List (A × O) → ℝ :=
  controlledOutputTrace K read

/-- Every reachable predictive class indicator is in the linear span of
actual future-word probabilities, which are generated by the SAME K/read. -/
def FutureTestsResolvePredictiveClasses
    {X : Type uX} {A : Type uA} {O : Type uO} {I : Type uI}
    [Fintype X] [DecidableEq O] [Fintype I]
    (K : FiniteControlledStochasticKernel X A) (read : X → O)
    (probe : I → List (A × O))
    (coeff : ReachableState (stochasticFuture K read) → I → ℝ) : Prop := by
  classical
  exact ∀ c y, (if stochasticFuture K read y = c.1 then (1 : ℝ) else 0) =
    ∑ i, coeff c i * stochasticFuture K read y (probe i)

/-- Equality of all observed futures forces matching current readout. -/
theorem equal_stochastic_futures_have_equal_readout
    {X : Type uX} {A : Type uA} {O : Type uO}
    [Fintype X] [DecidableEq O]
    (K : FiniteControlledStochasticKernel X A) (read : X → O)
    {x y : X} (heq : stochasticFuture K read x = stochasticFuture K read y)
    (a : A) : read x = read y := by
  have h := congrFun heq [(a, read x)]
  change controlledOutputTrace K read x [(a, read x)] =
    controlledOutputTrace K read y [(a, read x)] at h
  rw [one_word_trace_is_pre_transition_observation,
      one_word_trace_is_pre_transition_observation] at h
  by_cases hread : read y = read x
  · exact hread.symm
  · simp [hread] at h

/-- Equality of ALL futures automatically proves equality of one-step
expected future-word test values on each predictive fibre. -/
theorem equal_futures_agree_on_transition_future_tests
    {X : Type uX} {A : Type uA} {O : Type uO}
    [Fintype X] [DecidableEq O]
    (K : FiniteControlledStochasticKernel X A) (read : X → O)
    {x y : X} (heq : stochasticFuture K read x = stochasticFuture K read y)
    (a : A) (w : List (A × O)) :
    (∑ z : X, K.mass x a z * stochasticFuture K read z w) =
    (∑ z : X, K.mass y a z * stochasticFuture K read z w) := by
  have hread : read x = read y :=
    equal_stochastic_futures_have_equal_readout K read heq a
  have htrace := congrFun heq ((a, read x) :: w)
  dsimp [stochasticFuture] at htrace ⊢
  simp only [controlledOutputTrace, if_pos hread.symm] at htrace
  exact htrace

/-- Directly reconstruct class transition mass via finite true
future-word response tests. No predicted class mass is an assumption. -/
theorem class_mass_eq_reconstructed_future_expectations
    {X : Type uX} {A : Type uA} {O : Type uO} {I : Type uI}
    [Fintype X] [Fintype I] [DecidableEq O]
    (K : FiniteControlledStochasticKernel X A) (read : X → O)
    (probe : I → List (A × O))
    (coeff : ReachableState (stochasticFuture K read) → I → ℝ)
    (hresolve : FutureTestsResolvePredictiveClasses K read probe coeff)
    (x : X) (a : A) (c : ReachableState (stochasticFuture K read)) :
    massIntoClass K (stochasticFuture K read) x a c =
      ∑ i, coeff c i *
        (∑ z : X, K.mass x a z * stochasticFuture K read z (probe i)) := by
  classical
  unfold massIntoClass
  calc
    (∑ z : X, if stochasticFuture K read z = c.1 then
        K.mass x a z else 0) =
      ∑ z : X, K.mass x a z *
        (if stochasticFuture K read z = c.1 then (1 : ℝ) else 0) := by
      apply Finset.sum_congr rfl
      intro z _
      split_ifs <;> ring
    _ = ∑ z : X, K.mass x a z *
        (∑ i, coeff c i * stochasticFuture K read z (probe i)) := by
      apply Finset.sum_congr rfl
      intro z _
      rw [hresolve c z]
    _ = ∑ z : X, ∑ i, K.mass x a z *
        (coeff c i * stochasticFuture K read z (probe i)) := by
      simp_rw [Finset.mul_sum]
    _ = ∑ i, ∑ z : X, K.mass x a z *
        (coeff c i * stochasticFuture K read z (probe i)) := Finset.sum_comm
    _ = ∑ i, coeff c i *
        (∑ z : X, K.mass x a z * stochasticFuture K read z (probe i)) := by
      apply Finset.sum_congr rfl
      intro i _
      rw [Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro z _
      ring

/-- Non-Dirac stochastic breakthrough: future-word indicator identifiability
derives genuine strong lumpability without independently hypothesizing it. -/
theorem stochastic_future_tests_force_strong_lumpability
    {X : Type uX} {A : Type uA} {O : Type uO} {I : Type uI}
    [Fintype X] [Fintype I] [DecidableEq O]
    (K : FiniteControlledStochasticKernel X A) (read : X → O)
    (probe : I → List (A × O))
    (coeff : ReachableState (stochasticFuture K read) → I → ℝ)
    (hresolve : FutureTestsResolvePredictiveClasses K read probe coeff) :
    StrongLumpability K (stochasticFuture K read) := by
  intro x y hxy a c
  rw [class_mass_eq_reconstructed_future_expectations
        K read probe coeff hresolve x a c,
      class_mass_eq_reconstructed_future_expectations
        K read probe coeff hresolve y a c]
  apply Finset.sum_congr rfl
  intro i _
  rw [equal_futures_agree_on_transition_future_tests
    K read hxy a (probe i)]

/-- Normalized nonnegative Markov quotient for genuinely stochastic K. -/
theorem stochastic_future_tests_have_unique_normalized_quotient
    {X : Type uX} {A : Type uA} {O : Type uO} {I : Type uI}
    [Fintype X] [Fintype I] [DecidableEq O]
    (K : FiniteControlledStochasticKernel X A) (read : X → O)
    (probe : I → List (A × O))
    (coeff : ReachableState (stochasticFuture K read) → I → ℝ)
    (hresolve : FutureTestsResolvePredictiveClasses K read probe coeff) :
    letI : Fintype (ReachableState (stochasticFuture K read)) :=
      Fintype.ofFinite _
    ∃! Kbar : FiniteControlledStochasticKernel
      (ReachableState (stochasticFuture K read)) A,
      ∀ x a c, Kbar.mass (toReachable (stochasticFuture K read) x) a c =
        massIntoClass K (stochasticFuture K read) x a c :=
  (strong_lumpability_iff_existsUnique_stochastic_quotient
    K (stochasticFuture K read)).mp
      (stochastic_future_tests_force_strong_lumpability
        K read probe coeff hresolve)

end UEOT.V3.Compression.TheoryCompletion.UnifiedClosure
