import UEOT.V3.Compression.RecursiveSufficientState
import UEOT.V3.Compression.Objecthood.FormedParentSelfRepairSynthesis

/-!
# P0.1 scratch — Operational Object constitution

The semantic roles are intentionally separate predicates.  This avoids defining
"Object" by assuming all desired conclusions as fields of one package.
-/

namespace UEOT.V3.Compression.TheoryCompletion

noncomputable section

local instance tcSemanticDecidableEq (α : Type*) : DecidableEq α := Classical.decEq α

open Set MeasureTheory ProbabilityTheory
open UEOT.V3
open UEOT.V3.ViabilityKernel
open UEOT.V3.ViabilityTrajectory
open UEOT.V3.RecoveryHittingNonnegative
open UEOT.V3.Compression.RecursiveSufficientState
open UEOT.V3.Compression.CrossTrack
open UEOT.V3.Compression.Objecthood
open scoped ENNReal ProbabilityTheory

universe uV uChild uH uProbe uR uY uE uZ uX uA uC

/-- Predictive identity is sufficiency of one history representation for one
declared response family.  It is deliberately not identified with Objecthood. -/
def PredictiveIdentity
    {H : Type uH} {S : Type uC} {E : Type uE} {T : Type uR}
    (C : H → S) (R : H → E → T) : Prop :=
  InputFiberCompatible C R

/-- Formation provenance: the selected carrier/coalition is generated by the
declared candidate mechanism rather than supplied as an unrelated token. -/
def FormedProvenance
    {Candidate : Type uC} (generated : Set Candidate) (object : Candidate) : Prop :=
  object ∈ generated

/-- Object-specific interface delimitation inside one response family.  Every
distinct competing candidate is distinguished from the selected object by at
least one declared probe. -/
def InteractionDelimitedAt
    {Obj : Type uC} {Probe : Type uE} {Y : Type uY}
    [MeasurableSpace Y]
    (F : InteractionResponseFamily Obj Probe Y)
    (probes : Finset Probe) (object : Obj) : Prop :=
  ∀ ⦃other : Obj⦄, other ≠ object →
    ∃ probe ∈ probes, F.response object probe ≠ F.response other probe

/-- Pairwise family separation implies object-specific delimitation for each
selected candidate. -/
theorem interactionDelimitedAt_of_pairwise
    {Obj : Type uC} {Probe : Type uE} {Y : Type uY}
    [MeasurableSpace Y]
    (F : InteractionResponseFamily Obj Probe Y)
    (probes : Finset Probe)
    (hsep : PairwiseInteractionSeparating F probes)
    (object : Obj) :
    InteractionDelimitedAt F probes object := by
  intro other hne
  rcases hsep (a := object) (b := other) hne.symm with ⟨probe, hprobe, hneResponse⟩
  exact ⟨probe, hprobe, hneResponse⟩

/-- Minimal nonvacuous constitutive persistence semantics: there is an actual
seed in a fixed viability kernel contained in the declared domain, together
with an internal controller whose genuine infinite trajectory stays in the
corresponding constitutive domain almost surely. -/
def ConstitutivelyPersists
    {X : Type uX} {A : Type uA}
    [Fintype X] [Fintype A]
    [MeasurableSpace X] [MeasurableSingletonClass X]
    [MeasurableSpace (ConstitutiveState X A)]
    [MeasurableSingletonClass (ConstitutiveState X A)]
    (P : X → A → PMF X) (V : Set X) : Prop :=
  ∃ (K : Set X) (controller : X → A) (seed : X),
    K ⊆ V ∧
    seed ∈ K ∧
    viabilityStep P K = K ∧
    stationaryTrajMeasure
      (constitutiveLift P) noExternalControl
      (PMF.pure (seed, controller))
      {omega | ∀ n : ℕ, omega n ∈ constitutiveDomain K controller} = 1

/-- The canonical constitutive-persistence certificate implies the smaller
semantic persistence predicate. -/
theorem constitutivelyPersists_of_certificate
    {X : Type uX} {A : Type uA}
    [Fintype X] [Fintype A]
    [MeasurableSpace X] [MeasurableSingletonClass X]
    [MeasurableSpace (ConstitutiveState X A)]
    [MeasurableSingletonClass (ConstitutiveState X A)]
    {P : X → A → PMF X} {V : Set X}
    (C : ConstitutivePersistenceCertificate P V) :
    ConstitutivelyPersists P V := by
  exact ⟨C.K, C.controller, C.seed,
    C.kernel_sub_domain, C.seed_mem, C.source_fixed, C.all_times_safe⟩

/-- Physical recoverability on an explicitly declared, nonempty basin.
The predicate requires at least one certified starting state and finite expected
hitting time under one repair policy throughout that basin; it does not pretend
that the certified basin is the whole state space. -/
def PhysicallyRecoverableOn
    {X : Type uX} {A : Type uA}
    [Fintype X] [Fintype A]
    [MeasurableSpace X] [MeasurableSingletonClass X]
    (P : X → A → PMF X) (target basin : Set X) : Prop :=
  basin.Nonempty ∧
    ∃ repairPolicy : X → A, ∀ x ∈ basin,
      expectedHittingTime (stationaryKernel P repairPolicy) x target ≠ ∞

/-- Recoverability is definitionally nonvacuous: the declared repair basin has
an actual certified starting state. -/
theorem physicallyRecoverableOn_basin_nonempty
    {X : Type uX} {A : Type uA}
    [Fintype X] [Fintype A]
    [MeasurableSpace X] [MeasurableSingletonClass X]
    {P : X → A → PMF X} {target basin : Set X}
    (h : PhysicallyRecoverableOn P target basin) :
    basin.Nonempty :=
  h.1

/-- A physical-repair certificate plus an explicit nonempty-basin witness
gives recoverability on exactly its finite-potential basin.  Nonemptiness is
not silently inferred from the Track-O certificate because that source
structure does not require it. -/
theorem physicallyRecoverableOn_of_certificate
    {X : Type uX} {A : Type uA}
    [Fintype X] [Fintype A]
    [MeasurableSpace X] [MeasurableSingletonClass X]
    {P : X → A → PMF X} {target : Set X}
    (C : PhysicalRepairCertificate P target)
    (hbasin : C.basin.Nonempty) :
    PhysicallyRecoverableOn P target C.basin := by
  refine ⟨hbasin, C.repairPolicy, ?_⟩
  intro x hx
  exact C.expectedHittingTime_ne_top_of_mem_basin hx

/-- Typed semantic identity inside one declared parent-completion fibre.  This
is intentionally weaker than literal equality of parent representations. -/
def SemanticFiberIdentity
    {Parent : Type uC} {Child : Type uE}
    (pi : Parent → Child) (parent : Parent) (child : Child) : Prop :=
  pi parent = child

/-- An operational formed-persistent parent canonically supplies provenance,
object-specific interaction delimitation, and nonvacuous constitutive
persistence. -/
theorem operationalParent_constituents
    [Fintype Child]
    [MeasurableSpace Y] [MeasurableSpace Z]
    {readout : Finset V → H → Rout}
    {p : H → Probe → Measure Y}
    {regions : Child → Finset V}
    {response : Finset Child → E → Measure Z}
    {hprob : ∀ S e, IsProbabilityMeasure (response S e)}
    {probes : Finset E}
    {dynamics : FormedCandidate readout p regions → X → A → PMF X}
    {persistenceDomain : FormedCandidate readout p regions → Set X}
    [Fintype X] [Fintype A]
    [MeasurableSpace X] [MeasurableSingletonClass X]
    [MeasurableSpace (ConstitutiveState X A)]
    [MeasurableSingletonClass (ConstitutiveState X A)]
    (C : OperationalFormedPersistentParent
      readout p regions response hprob probes dynamics persistenceDomain) :
    FormedProvenance
        (responseFormedCandidateFamily readout p regions) C.parent.1 ∧
    InteractionDelimitedAt
        (formedCandidateResponseFamily readout p regions response hprob)
        probes C.parent ∧
    ConstitutivelyPersists
        (dynamics C.parent) (persistenceDomain C.parent) := by
  refine ⟨C.parent_mem_generatedFamily, ?_, ?_⟩
  · exact interactionDelimitedAt_of_pairwise
      (formedCandidateResponseFamily readout p regions response hprob)
      probes C.separating C.parent
  · exact constitutivelyPersists_of_certificate C.persistence

/-- Self-repair plus an explicit witness that the Track-O finite-potential
repair basin is nonempty gives finite-expected-time physical recovery semantics,
without strengthening that basin to all states. -/
theorem selfRepairingParent_recoverability
    [Fintype Child]
    [MeasurableSpace Y] [MeasurableSpace Z]
    {readout : Finset V → H → Rout}
    {p : H → Probe → Measure Y}
    {regions : Child → Finset V}
    {response : Finset Child → E → Measure Z}
    {hprob : ∀ S e, IsProbabilityMeasure (response S e)}
    {probes : Finset E}
    {dynamics : FormedCandidate readout p regions → X → A → PMF X}
    {persistenceDomain : FormedCandidate readout p regions → Set X}
    [Fintype X] [Fintype A] [Nonempty A]
    [MeasurableSpace X] [MeasurableSingletonClass X]
    [MeasurableSpace (ConstitutiveState X A)]
    [MeasurableSingletonClass (ConstitutiveState X A)]
    (C : SelfRepairingOperationalParent
      readout p regions response hprob probes dynamics persistenceDomain)
    (hbasin : C.physicalRepair.basin.Nonempty) :
    PhysicallyRecoverableOn
      (dynamics C.operational.parent)
      C.operational.persistence.K
      C.physicalRepair.basin := by
  exact physicallyRecoverableOn_of_certificate C.physicalRepair hbasin

/-- The hardened Objecthood package identifies the exact selected operational
parent with the semantic fibre certified by Track X. -/
theorem semanticallyStableParent_identity
    [Fintype Child]
    [MeasurableSpace Y] [MeasurableSpace Z]
    {readout : Finset V → H → Rout}
    {p : H → Probe → Measure Y}
    {regions : Child → Finset V}
    {response : Finset Child → E → Measure Z}
    {hprob : ∀ S e, IsProbabilityMeasure (response S e)}
    {probes : Finset E}
    {dynamics : FormedCandidate readout p regions → X → A → PMF X}
    {persistenceDomain : FormedCandidate readout p regions → Set X}
    {Csem : Type uC} {Ssem : Type uR}
    [Fintype X] [Fintype A] [Nonempty A]
    [MeasurableSpace X] [MeasurableSingletonClass X]
    [MeasurableSpace (ConstitutiveState X A)]
    [MeasurableSingletonClass (ConstitutiveState X A)]
    [Fintype Ssem] [Nonempty Ssem]
    {pi : FormedCandidate readout p regions → Csem}
    {semanticKernel : FormedCandidate readout p regions → Matrix Ssem Ssem ℝ}
    {hSemanticKernel : ∀ q, semanticKernel q ∈ Matrix.rowStochastic ℝ Ssem}
    (C : SemanticallyStableSelfRepairingOperationalParent
      readout p regions response hprob probes dynamics persistenceDomain
      pi semanticKernel hSemanticKernel) :
    SemanticFiberIdentity
      pi C.repairing.operational.parent C.semantic.child := by
  exact C.selected_parent_in_fiber

end

end UEOT.V3.Compression.TheoryCompletion
