import UEOT.V3.Compression

#print axioms UEOT.V3.Compression.QuotientDescent.fiberCompatible_iff_existsUnique_descend
#print axioms UEOT.V3.Compression.QuotientDescent.strongLumpability_unique_setLevel_descend
#print axioms UEOT.V3.Compression.QuotientDescent.countableAEFamily_descend
#print axioms UEOT.V3.Compression.QuotientDescent.p_pred_01_via_countableAE_descent
#print axioms UEOT.V3.Compression.TransportCertificate.twoStage_bound
#print axioms UEOT.V3.Compression.TransportCertificate.factorRoute_exact
#print axioms UEOT.V3.Compression.TransportCertificate.chain_bound
#print axioms UEOT.V3.Compression.TransportCertificate.processInterface_exact_source_via_twoStage
#print axioms UEOT.V3.Compression.TransportCertificate.processInterface_approx_via_twoStage
#print axioms UEOT.V3.Compression.TransportCertificate.transportDefect_source_via_chain
#print axioms UEOT.V3.Compression.TransportCertificate.dynamicsCrossScale_approx_via_twoStage
#print axioms UEOT.V3.Compression.TransportCertificate.dynamicsCrossScale_exact_via_factor
