import UEOT.V3.Compression.CrossTrack.InteractionBindingIsolation
import Mathlib.Tactic

/-!
# P4.0 — inverse-Objecthood identifiability semantics

Inverse discovery must distinguish three notions that are easy to conflate:

1. a finite/model candidate token;
2. equivalence under the declared observational/interventional evidence;
3. the scientific object-equivalence relation one actually wants to recover.

This module defines the generic identification criterion only **among an
explicit validity class**.  It then instantiates the evidence relation with the
finite interaction-response interface already proved in Track X.

Nothing here asserts that interaction evidence is full UEOT Objecthood, that a
candidate token is a metaphysically unique object, or that persistence,
repairability, semantic identity, purpose, GOD or GOA can be inferred from one
fingerprint.  Those are later P4 validity/bridge obligations.
-/

namespace UEOT.V3.Compression.TheoryCompletion.InverseObjecthood

open MeasureTheory
open UEOT.V3.Compression.CrossTrack

universe uA uE

/-- Generic evidence-relative candidate equivalence: two candidates are
indistinguishable by the declared evidence map. -/
def EvidenceEquivalent
    {A : Type uA} {Evidence : Type uE}
    (evidence : A → Evidence) (a b : A) : Prop :=
  evidence a = evidence b

/-- Equality of a declared evidence map is a genuine equivalence relation and
therefore supports a quotient/evidence-class semantics. -/
def evidenceSetoid
    {A : Type uA} {Evidence : Type uE}
    (evidence : A → Evidence) : Setoid A where
  r := EvidenceEquivalent evidence
  iseqv := by
    constructor
    · intro a
      rfl
    · intro a b hab
      change evidence a = evidence b at hab
      change evidence b = evidence a
      exact hab.symm
    · intro a b c hab hbc
      change evidence a = evidence b at hab
      change evidence b = evidence c at hbc
      change evidence a = evidence c
      exact hab.trans hbc

/-- Relative inverse-identifiability schema.

Identification means that, **among candidates admitted by `valid`**, equality
of the declared evidence is strong enough to force the target scientific
object-equivalence relation `objectEq`.

The target equivalence is deliberately supplied separately as a `Setoid`.
Candidate equality, evidence equality, same-control-parent identity and full
Objecthood identity are not silently identified. -/
def ObjectClassIdentifiedByEvidenceAmongValid
    {A : Type uA} {Evidence : Type uE}
    (valid : A → Prop)
    (evidence : A → Evidence)
    (objectClass : Setoid A) : Prop :=
  ∀ a b, valid a → valid b →
    EvidenceEquivalent evidence a b → objectClass.r a b

/-- One valid evidence-indistinguishable pair in distinct target object classes
is a complete no-go witness for that evidence interface. -/
theorem objectClass_not_identified_of_valid_counterexample
    {A : Type uA} {Evidence : Type uE}
    (valid : A → Prop)
    (evidence : A → Evidence)
    (objectClass : Setoid A)
    {a b : A}
    (ha : valid a) (hb : valid b)
    (hEvidence : EvidenceEquivalent evidence a b)
    (hObject : ¬ objectClass.r a b) :
    ¬ ObjectClassIdentifiedByEvidenceAmongValid valid evidence objectClass := by
  intro h
  exact hObject (h a b ha hb hEvidence)

/-- Explicit equality Setoid used only for the literal-candidate specialization. -/
def equalitySetoid (A : Type uA) : Setoid A where
  r := Eq
  iseqv := ⟨Eq.refl, Eq.symm, Eq.trans⟩

/-- If the desired scientific object relation is literal candidate equality,
identification says exactly that the evidence map is injective on valid
candidates.  This is a specialization, not the universal meaning of Objecthood. -/
theorem literalCandidate_identified_iff_injectiveOnValid
    {A : Type uA} {Evidence : Type uE}
    (valid : A → Prop) (evidence : A → Evidence) :
    ObjectClassIdentifiedByEvidenceAmongValid valid evidence (equalitySetoid A) ↔
      ∀ a b, valid a → valid b → evidence a = evidence b → a = b := by
  rfl

/-- Probe-relative interaction evidence equivalence.  This is an observational
relation generated by the selected probes, not yet an Objecthood identity
relation. -/
def InteractionEvidenceEquivalent
    {A : Type uA} {I Y : Type*} [MeasurableSpace Y]
    (F : InteractionResponseFamily A I Y)
    (probes : Finset I) (a b : A) : Prop :=
  ∀ i ∈ probes, F.response a i = F.response b i

/-- Probe-relative interaction evidence forms an equivalence relation on
candidate tokens. -/
def interactionEvidenceSetoid
    {A : Type uA} {I Y : Type*} [MeasurableSpace Y]
    (F : InteractionResponseFamily A I Y)
    (probes : Finset I) : Setoid A where
  r := InteractionEvidenceEquivalent F probes
  iseqv := ⟨
    by
      intro a i hi
      rfl,
    by
      intro a b hab i hi
      exact (hab i hi).symm,
    by
      intro a b c hab hbc i hi
      exact (hab i hi).trans (hbc i hi)⟩

/-- Existing Track-X fingerprint geometry exactly represents the
probe-relative observational equivalence relation. -/
theorem interactionEvidenceEquivalent_iff_fingerprintDist_eq_zero
    {A : Type uA} {I Y : Type*} [MeasurableSpace Y]
    (F : InteractionResponseFamily A I Y)
    (probes : Finset I) (hprobes : probes.Nonempty)
    (a b : A) :
    InteractionEvidenceEquivalent F probes a b ↔
      interactionFingerprintDist F probes hprobes a b = 0 := by
  symm
  exact interactionFingerprintDist_eq_zero_iff F probes hprobes a b

/-- Pairwise interaction separation is precisely the extra condition that
collapses every probe-relative evidence class to one literal candidate label.
Without it, P4 may recover only an evidence class. -/
theorem pairwiseSeparating_iff_evidenceEquivalent_implies_eq
    {A : Type uA} {I Y : Type*} [MeasurableSpace Y]
    (F : InteractionResponseFamily A I Y)
    (probes : Finset I) :
    PairwiseInteractionSeparating F probes ↔
      ∀ a b, InteractionEvidenceEquivalent F probes a b → a = b := by
  constructor
  · intro hsep a b heq
    by_contra hne
    rcases hsep hne with ⟨i, hi, hdiff⟩
    exact hdiff (heq i hi)
  · intro h a b hne
    by_contra hnone
    have heq : InteractionEvidenceEquivalent F probes a b := by
      intro i hi
      by_contra hdiff
      exact hnone ⟨i, hi, hdiff⟩
    exact hne (h a b heq)

end UEOT.V3.Compression.TheoryCompletion.InverseObjecthood
