import Mathlib.Analysis.ODE.DiscreteGronwall
import Mathlib.Algebra.Field.GeomSum
import Mathlib.Topology.MetricSpace.Pseudo.Basic

/-!
# P-ID-02: development transport pipeline

This module formalizes the frozen UEOT v3.0 development-pipeline statement.
The actual structural trajectory `θ` is compared with a reference trajectory
`θbar` generated by the declared model `Ψ`.  A one-step model residual and a
Lipschitz propagation bound imply the source recurrence

`e (t+1) ≤ L t * e t + ε t`,

and the exact finite-horizon product/sum expansion follows from the standard
discrete Grönwall inequality.
-/

namespace UEOT.V3.DevelopmentTransport

open Finset

universe uX

variable {X : Type uX} [PseudoMetricSpace X]

/-- The source one-step development error recursion.  This is obtained directly
from the residual bound, reference dynamics, the triangle inequality, and the
stated Lipschitz bound. -/
theorem development_error_step
    (θ θbar : ℕ → X)
    (Ψ : ℕ → X → X)
    (L ε : ℕ → ℝ)
    (href : ∀ t, θbar (t + 1) = Ψ t (θbar t))
    (hres : ∀ t, dist (θ (t + 1)) (Ψ t (θ t)) ≤ ε t)
    (hlip : ∀ t x y, dist (Ψ t x) (Ψ t y) ≤ L t * dist x y)
    (t : ℕ) :
    dist (θ (t + 1)) (θbar (t + 1)) ≤
      L t * dist (θ t) (θbar t) + ε t := by
  rw [href t]
  calc
    dist (θ (t + 1)) (Ψ t (θbar t))
        ≤ dist (θ (t + 1)) (Ψ t (θ t)) +
            dist (Ψ t (θ t)) (Ψ t (θbar t)) := dist_triangle _ _ _
    _ ≤ ε t + L t * dist (θ t) (θbar t) :=
      add_le_add (hres t) (hlip t (θ t) (θbar t))
    _ = L t * dist (θ t) (θbar t) + ε t := add_comm _ _

/-- **P-ID-02: development pipeline, exact finite-horizon form.**

If the actual trajectory has one-step residual at most `ε t`, the reference
trajectory follows `Ψ`, and `Ψ t` is `L t`-Lipschitz in the metric inequality
sense with nonnegative constants, then

`e_n ≤ (∏_{j<n} L_j) e_0 + ∑_{k<n} ε_k ∏_{j=k+1}^{n-1} L_j`.

The interval product `Ico (k+1) n` is exactly the source product over
`j = k+1, ..., n-1`. -/
theorem development_pipeline
    (θ θbar : ℕ → X)
    (Ψ : ℕ → X → X)
    (L ε : ℕ → ℝ)
    (href : ∀ t, θbar (t + 1) = Ψ t (θbar t))
    (hres : ∀ t, dist (θ (t + 1)) (Ψ t (θ t)) ≤ ε t)
    (hlip : ∀ t x y, dist (Ψ t x) (Ψ t y) ≤ L t * dist x y)
    (hL0 : ∀ t, 0 ≤ L t)
    (n : ℕ) :
    dist (θ n) (θbar n) ≤
      (∏ j ∈ Finset.range n, L j) * dist (θ 0) (θbar 0) +
        ∑ k ∈ Finset.range n,
          ε k * ∏ j ∈ Finset.Ico (k + 1) n, L j := by
  have hgr :=
    discrete_gronwall_prod_general
      (u := fun t => dist (θ t) (θbar t))
      (b := ε)
      (c := L)
      (n₀ := 0)
      (fun t _ => development_error_step θ θbar Ψ L ε href hres hlip t)
      (fun t _ => hL0 t)
      (Nat.zero_le n)
  rw [Nat.Ico_zero_eq_range] at hgr
  calc
    dist (θ n) (θbar n)
        ≤ dist (θ 0) (θbar 0) * (∏ j ∈ Finset.range n, L j) +
            ∑ k ∈ Finset.range n,
              ε k * ∏ j ∈ Finset.Ico (k + 1) n, L j := hgr
    _ = (∏ j ∈ Finset.range n, L j) * dist (θ 0) (θbar 0) +
          ∑ k ∈ Finset.range n,
            ε k * ∏ j ∈ Finset.Ico (k + 1) n, L j := by
      rw [mul_comm (dist (θ 0) (θbar 0))]

/-- Uniform-coefficient version used to expose the geometric-series corollary
that immediately follows P-ID-02 in the frozen source. -/
theorem development_pipeline_uniform_geom
    (θ θbar : ℕ → X)
    (Ψ : ℕ → X → X)
    (L ε : ℕ → ℝ)
    (Lbar εbar : ℝ)
    (href : ∀ t, θbar (t + 1) = Ψ t (θbar t))
    (hres : ∀ t, dist (θ (t + 1)) (Ψ t (θ t)) ≤ ε t)
    (hlip : ∀ t x y, dist (Ψ t x) (Ψ t y) ≤ L t * dist x y)
    (hLbar0 : 0 ≤ Lbar)
    (hL : ∀ t, L t ≤ Lbar)
    (hε : ∀ t, ε t ≤ εbar)
    (n : ℕ) :
    dist (θ n) (θbar n) ≤
      Lbar ^ n * dist (θ 0) (θbar 0) +
        εbar * ∑ i ∈ Finset.range n, Lbar ^ i := by
  induction n with
  | zero => simp
  | succ n ih =>
      calc
        dist (θ (n + 1)) (θbar (n + 1))
            ≤ L n * dist (θ n) (θbar n) + ε n :=
              development_error_step θ θbar Ψ L ε href hres hlip n
        _ ≤ Lbar * dist (θ n) (θbar n) + εbar := by
              exact add_le_add
                (mul_le_mul_of_nonneg_right (hL n) dist_nonneg)
                (hε n)
        _ ≤ Lbar *
              (Lbar ^ n * dist (θ 0) (θbar 0) +
                εbar * ∑ i ∈ Finset.range n, Lbar ^ i) + εbar := by
              exact add_le_add_right (mul_le_mul_of_nonneg_left ih hLbar0) εbar
        _ = Lbar ^ (n + 1) * dist (θ 0) (θbar 0) +
              εbar * ∑ i ∈ Finset.range (n + 1), Lbar ^ i := by
              rw [Finset.sum_range_succ, pow_succ]
              ring

/-- Frozen-source contraction corollary.

If all local Lipschitz constants are bounded by one constant `Lbar < 1` and all
residuals are bounded by `εbar`, then

`e_n ≤ Lbar^n e_0 + εbar (1 - Lbar^n)/(1 - Lbar)`.
-/
theorem development_pipeline_uniform_contraction
    (θ θbar : ℕ → X)
    (Ψ : ℕ → X → X)
    (L ε : ℕ → ℝ)
    (Lbar εbar : ℝ)
    (href : ∀ t, θbar (t + 1) = Ψ t (θbar t))
    (hres : ∀ t, dist (θ (t + 1)) (Ψ t (θ t)) ≤ ε t)
    (hlip : ∀ t x y, dist (Ψ t x) (Ψ t y) ≤ L t * dist x y)
    (hLbar0 : 0 ≤ Lbar)
    (hLbar1 : Lbar < 1)
    (hL : ∀ t, L t ≤ Lbar)
    (hε : ∀ t, ε t ≤ εbar)
    (n : ℕ) :
    dist (θ n) (θbar n) ≤
      Lbar ^ n * dist (θ 0) (θbar 0) +
        εbar * (1 - Lbar ^ n) / (1 - Lbar) := by
  have h := development_pipeline_uniform_geom
    θ θbar Ψ L ε Lbar εbar href hres hlip hLbar0 hL hε n
  calc
    dist (θ n) (θbar n)
        ≤ Lbar ^ n * dist (θ 0) (θbar 0) +
            εbar * ∑ i ∈ Finset.range n, Lbar ^ i := h
    _ = Lbar ^ n * dist (θ 0) (θbar 0) +
          εbar * (1 - Lbar ^ n) / (1 - Lbar) := by
      rw [geom_sum_eq (ne_of_lt hLbar1) n]
      have h₁ : Lbar - 1 ≠ 0 := sub_ne_zero.mpr (ne_of_lt hLbar1)
      have h₂ : 1 - Lbar ≠ 0 := sub_ne_zero.mpr (ne_of_gt hLbar1)
      field_simp [h₁, h₂]
      ring

end UEOT.V3.DevelopmentTransport
