import UEOT.V3.HilbertMeanProductBlockIndependence
import Mathlib.Probability.Process.Filtration
import Mathlib.Tactic

/-!
# P-STAT-06 — explicit prefix filtration on a finite canonical product

For a sample indexed by `Fin N`, time `n : ℕ` reveals exactly those coordinates
whose numeric index is at most `n`.  Defining the filtration directly as the
sigma-algebra generated by the corresponding finite block projection keeps it
aligned with the block conditional-expectation theorem, avoiding a separate
identification with `Filtration.natural`.
-/

namespace UEOT.V3.HilbertMeanPrefixFiltration

open MeasureTheory
open UEOT.V3.HilbertMeanProductBlockIndependence

universe uH

variable {H : Type uH} [MeasurableSpace H]

/-- Coordinates revealed by natural time `n`. -/
def prefix {N : ℕ} (n : ℕ) : Finset (Fin N) :=
  Finset.univ.filter fun i => i.1 ≤ n

@[simp] theorem mem_prefix_iff {N : ℕ} (n : ℕ) (i : Fin N) :
    i ∈ prefix n ↔ i.1 ≤ n := by
  simp [prefix]

/-- Restriction from a larger prefix block to a smaller one. -/
def restrictPrefix {N : ℕ} {n m : ℕ} (hnm : n ≤ m) :
    (prefix (N := N) m → H) → (prefix (N := N) n → H) :=
  fun x i => x ⟨i.1, (mem_prefix_iff m i.1).2 ((mem_prefix_iff n i.1).1 i.2 |>.trans hnm)⟩

/-- Prefix restriction is measurable. -/
theorem measurable_restrictPrefix {N : ℕ} {n m : ℕ} (hnm : n ≤ m) :
    Measurable (restrictPrefix (H := H) (N := N) hnm) := by
  rw [measurable_pi_iff]
  intro i
  exact measurable_pi_apply _

/-- Smaller block projection factors through the larger block projection. -/
theorem blockProjection_prefix_factor {N : ℕ} {n m : ℕ} (hnm : n ≤ m) :
    blockProjection (H := H) (prefix (N := N) n) =
      restrictPrefix (H := H) (N := N) hnm ∘
        blockProjection (H := H) (prefix (N := N) m) := by
  funext ω i
  rfl

/-- Sigma algebra generated by the prefix block at time `n`. -/
def prefixSigma {N : ℕ} (n : ℕ) : MeasurableSpace (Fin N → H) :=
  MeasurableSpace.comap
    (blockProjection (H := H) (prefix (N := N) n))
    inferInstance

/-- Prefix sigma-algebras are monotone in time. -/
theorem prefixSigma_mono {N : ℕ} :
    Monotone (prefixSigma (H := H) (N := N)) := by
  intro n m hnm
  exact MeasurableSpace.comap_le_comap_of_eq_comp
    (restrictPrefix (H := H) (N := N) hnm)
    (measurable_restrictPrefix (H := H) (N := N) hnm)
    (blockProjection_prefix_factor (H := H) (N := N) hnm)

/-- Every prefix sigma algebra is contained in the ambient product measurable
space. -/
theorem prefixSigma_le {N : ℕ} (n : ℕ) :
    prefixSigma (H := H) (N := N) n ≤
      (inferInstance : MeasurableSpace (Fin N → H)) := by
  exact (measurable_blockProjection (H := H) (prefix (N := N) n)).comap_le

/-- Explicit natural-number indexed prefix filtration. -/
def prefixFiltration {N : ℕ} :
    Filtration ℕ (inferInstance : MeasurableSpace (Fin N → H)) where
  seq := prefixSigma (H := H) (N := N)
  mono' := prefixSigma_mono (H := H) (N := N)
  le' := prefixSigma_le (H := H) (N := N)

@[simp] theorem prefixFiltration_apply {N : ℕ} (n : ℕ) :
    prefixFiltration (H := H) (N := N) n = prefixSigma (H := H) (N := N) n := rfl

end UEOT.V3.HilbertMeanPrefixFiltration
