import UEOT.V3.HilbertMeanPrefixFiltration
import Mathlib.Tactic

/-!
# P-STAT-06 — predecessor prefix equals the strict past

For a genuine active index `i` with positive numeric value, the filtration one
step before `i` reveals exactly the coordinates strictly before `i`.
-/

namespace UEOT.V3.HilbertMeanPrefixPredecessor

open UEOT.V3.HilbertMeanDoobBlocks
open UEOT.V3.HilbertMeanPrefixFiltration
open UEOT.V3.HilbertMeanProductBlockIndependence

universe uH

variable {H : Type uH} [MeasurableSpace H]

/-- If `i > 0`, the numeric prefix at time `i-1` is exactly `past i`. -/
theorem prefixBlock_pred_eq_past {N : ℕ} (i : Fin N) (hi : 0 < i.1) :
    prefixBlock (N := N) (i.1 - 1) = past i := by
  ext j
  simp only [mem_prefixBlock_iff, mem_past_iff]
  rw [Fin.lt_def]
  omega

/-- The predecessor prefix filtration is exactly the sigma algebra generated by
the strict-past block projection.  This is the sigma-algebra identification
needed to transport the explicit past/active conditional expectation into the
Doob tower for every noninitial index. -/
theorem prefixFiltration_pred_eq_pastComap
    {N : ℕ} (i : Fin N) (hi : 0 < i.1) :
    prefixFiltration (H := H) (N := N) (i.1 - 1) =
      MeasurableSpace.comap
        (blockProjection (H := H) (past i))
        (inferInstance : MeasurableSpace (past i → H)) := by
  rw [prefixFiltration_apply]
  unfold prefixSigma
  rw [prefixBlock_pred_eq_past i hi]

end UEOT.V3.HilbertMeanPrefixPredecessor
