import UEOT.V3.HilbertMeanAzuma
import Mathlib.Probability.Moments.SubGaussian
import Mathlib.Tactic

/-!
# P-STAT-06 — conditional Hoeffding bridge

The frozen P-STAT-06 proof uses a Doob martingale for a statistic with one-sample
replacement sensitivity `2 / N`. Conditionally on the past, each martingale
increment has conditional mean zero and a conditional support interval of width
at most `2 / N`. Hoeffding's lemma therefore gives the exact conditional
sub-Gaussian proxy `(2/N)^2 / 4 = 1/N^2` used by `HilbertMeanAzuma`.

This file isolates that probability-theoretic bridge. The interval endpoints
may depend on the conditioning state; only their width is uniformly bounded.
A separate source-facing module can therefore instantiate this theorem with the
Doob increments generated by the RKHS bounded-difference statistic.
-/

namespace UEOT.V3.HilbertMeanConditionalHoeffding

open MeasureTheory ProbabilityTheory Real
open scoped NNReal

universe uΩ

variable {Ω : Type uΩ} {m mΩ : MeasurableSpace Ω}
variable [StandardBorelSpace Ω]

/-- Conditional Hoeffding with history-dependent support endpoints.

`D` simultaneously gives an absolute envelope, used only to obtain global
exponential integrability, and a uniform bound on the conditional support
width. The resulting variance proxy is exactly `(D / 2)^2`.
-/
theorem hasCondSubgaussianMGF_of_fiber_range
    (μ : Measure Ω) [IsProbabilityMeasure μ]
    (hm : m ≤ mΩ)
    (X : Ω → ℝ) (D : ℝ≥0)
    (a b : Ω → ℝ)
    (hXm : AEMeasurable X μ)
    (hglobal : ∀ᵐ ω ∂μ, X ω ∈ Set.Icc (-(D : ℝ)) (D : ℝ))
    (hfiber : ∀ᵐ ω' ∂(μ.trim hm),
      ∀ᵐ ω ∂(condExpKernel μ m ω'), X ω ∈ Set.Icc (a ω') (b ω'))
    (hcenter : ∀ᵐ ω' ∂(μ.trim hm),
      (∫ ω, X ω ∂condExpKernel μ m ω') = 0)
    (hwidth : ∀ᵐ ω' ∂(μ.trim hm), ‖b ω' - a ω'‖₊ ≤ D) :
    HasCondSubgaussianMGF m hm X ((D / 2) ^ 2) μ := by
  have hXint : Integrable X μ :=
    Integrable.of_mem_Icc (-(D : ℝ)) (D : ℝ) hXm hglobal
  have hXintComp : Integrable X (condExpKernel μ m ∘ₘ μ.trim hm) := by
    rw [condExpKernel_comp_trim (μ := μ) hm]
    exact hXint
  have hXfiber : ∀ᵐ ω' ∂(μ.trim hm), Integrable X (condExpKernel μ m ω') :=
    Measure.ae_integrable_of_integrable_comp hXintComp
  refine ⟨?_, ?_⟩
  · intro t
    rw [condExpKernel_comp_trim (μ := μ) hm]
    exact integrable_exp_mul_of_mem_Icc hXm hglobal
  · filter_upwards [hXfiber, hfiber, hcenter, hwidth] with ω' hXi hIcc hzero hD t
    letI : IsProbabilityMeasure (condExpKernel μ m ω') := by infer_instance
    have hsg : HasSubgaussianMGF X ((‖b ω' - a ω'‖₊ / 2) ^ 2)
        (condExpKernel μ m ω') :=
      hasSubgaussianMGF_of_mem_Icc_of_integral_eq_zero
        hXi.aemeasurable hIcc hzero
    calc
      mgf X (condExpKernel μ m ω') t
          ≤ exp (((‖b ω' - a ω'‖₊ / 2) ^ 2 : ℝ≥0) * t ^ 2 / 2) := hsg.mgf_le t
      _ ≤ exp ((((D / 2) ^ 2 : ℝ≥0) : ℝ) * t ^ 2 / 2) := by
        apply Real.exp_le_exp.mpr
        gcongr

/-- The exact P-STAT-06 normalization: conditional support width `2/N`
implies the increment proxy `1/N^2`. -/
theorem hasCondSubgaussianMGF_invSqParam_of_fiber_range
    (μ : Measure Ω) [IsProbabilityMeasure μ]
    (hm : m ≤ mΩ)
    {N : ℕ} (hN : 0 < N)
    (X : Ω → ℝ)
    (a b : Ω → ℝ)
    (hXm : AEMeasurable X μ)
    (hglobal : ∀ᵐ ω ∂μ,
      X ω ∈ Set.Icc (-(2 / (N : ℝ))) (2 / (N : ℝ)))
    (hfiber : ∀ᵐ ω' ∂(μ.trim hm),
      ∀ᵐ ω ∂(condExpKernel μ m ω'), X ω ∈ Set.Icc (a ω') (b ω'))
    (hcenter : ∀ᵐ ω' ∂(μ.trim hm),
      (∫ ω, X ω ∂condExpKernel μ m ω') = 0)
    (hwidth : ∀ᵐ ω' ∂(μ.trim hm),
      ‖b ω' - a ω'‖₊ ≤ (2 : ℝ≥0) / (N : ℝ≥0)) :
    HasCondSubgaussianMGF m hm X (HilbertMeanAzuma.invSqParam N) μ := by
  have hNnn : (N : ℝ≥0) ≠ 0 := by exact_mod_cast (Nat.ne_of_gt hN)
  have hfrac : (2 : ℝ≥0) / (N : ℝ≥0) / 2 = (N : ℝ≥0)⁻¹ := by
    field_simp [hNnn]
  have hbase := hasCondSubgaussianMGF_of_fiber_range
    (μ := μ) hm X ((2 : ℝ≥0) / (N : ℝ≥0)) a b hXm ?_ hfiber hcenter hwidth
  · convert hbase using 1
    simp only [HilbertMeanAzuma.invSqParam]
    exact (congrArg (fun x : ℝ≥0 => x ^ 2) hfrac).symm
  · filter_upwards [hglobal] with ω hω
    simpa [NNReal.coe_div] using hω

end UEOT.V3.HilbertMeanConditionalHoeffding
