import UEOT.V3.HilbertMeanSourceClippedIncrement
import UEOT.V3.HilbertMeanPastActiveIndependence
import Mathlib.Probability.Moments.SubGaussian
import Mathlib.Tactic

/-!
# P-STAT-06 — rational conditional MGF for the source increment

For each rational parameter, past/active independence identifies the
conditional exponential moment with an integral over the active source
marginal.  The strict-past fiber Hoeffding theorem then supplies the exact
`1/N²` bound almost everywhere.
-/

namespace UEOT.V3.HilbertMeanSourceRationalMGF

open MeasureTheory ProbabilityTheory Real
open scoped NNReal
open UEOT.V3.HilbertMeanAzuma
open UEOT.V3.HilbertMeanDoobBlocks
open UEOT.V3.HilbertMeanPastActiveClippedFiber
open UEOT.V3.HilbertMeanPastActiveIndependence
open UEOT.V3.HilbertMeanProductBlockIndependence
open UEOT.V3.HilbertMeanSourceClippedIncrement
open UEOT.V3.HilbertMeanSplitStatistic

universe uH

variable {H : Type uH}
variable [NormedAddCommGroup H] [InnerProductSpace ℝ H]
variable [MeasurableSpace H]

/-- The sigma-algebra generated by the strict-past block. -/
def sourcePastSigma {N : ℕ} (i : Fin N) : MeasurableSpace (Fin N → H) :=
  (inferInstance : MeasurableSpace (past i → H)).comap
    (blockProjection (H := H) (past i))

/-- The strict-past sigma-algebra is a sub-sigma-algebra of the canonical
product measurable space. -/
theorem sourcePastSigma_le
    {N : ℕ} (i : Fin N) :
    sourcePastSigma (H := H) i ≤
      (inferInstance : MeasurableSpace (Fin N → H)) := by
  exact (measurable_blockProjection (H := H) (past i)).comap_le

/-- Exact rational conditional-MGF bound under the canonical product law. -/
theorem ae_condExp_exp_sourceClippedIncrement_le
    [BorelSpace H] [StandardBorelSpace H] [Nonempty H]
    [MeasurableAdd₂ H] [MeasurableSub H]
    {N : ℕ} (hN : 0 < N)
    (μ : Fin N → Measure H) [∀ j, IsProbabilityMeasure (μ j)]
    (i : Fin N) (μH : H) (hμH : ‖μH‖ ≤ 1)
    (hunit : ∀ j, ∀ᵐ z ∂μ j, ‖z‖ ≤ 1)
    (q : ℚ) :
    (Measure.pi μ)[fun ω =>
        exp ((q : ℝ) * sourceClippedIncrement μ i μH ω) |
      sourcePastSigma (H := H) i]
      ≤ᵐ[Measure.pi μ]
      (fun _ => exp (((invSqParam N : ℝ≥0) : ℝ) * (q : ℝ) ^ 2 / 2)) := by
  let G : (past i → H) × H → ℝ :=
    pastCenteredClippedActiveSection μ i μH
  let f : (past i → H) × H → ℝ :=
    fun z => exp ((q : ℝ) * G z)
  have hG : StronglyMeasurable G := by
    dsimp [G]
    exact stronglyMeasurable_pastCenteredClippedActiveSection μ i μH
  have hf : StronglyMeasurable f := by
    apply Measurable.stronglyMeasurable
    exact Real.measurable_exp.comp (measurable_const.mul hG.measurable)
  have hf_int : Integrable
      (fun ω : Fin N → H =>
        f (blockProjection (past i) ω, ω i))
      (Measure.pi μ) := by
    simpa [f, G, sourceClippedIncrement] using
      integrable_exp_mul_sourceClippedIncrement
        hN μ i μH hμH hunit (q : ℝ)
  have hcond := condExp_past_active_ae_eq_integral_active
    (H := H) μ i f hf hf_int
  have hall : ∀ᵐ ω ∂Measure.pi μ, ∀ j, ‖ω j‖ ≤ 1 :=
    ae_unit_all_of_marginals μ hunit
  filter_upwards [hcond, hall] with ω hcondω hω
  have hpast : ∀ j : past i,
      ‖blockProjection (past i) ω j‖ ≤ 1 := by
    intro j
    simpa [blockProjection] using hω (j : Fin N)
  have hsg :=
    hasSubgaussianMGF_pastCenteredClippedActiveSection_invSqParam
      hN μ i (blockProjection (past i) ω) hpast μH hμH hunit
  have hmgf := hsg.mgf_le (q : ℝ)
  rw [hcondω]
  simpa [sourcePastSigma, f, G, mgf] using hmgf

end UEOT.V3.HilbertMeanSourceRationalMGF
