import Mathlib.Probability.HasLaw
import Mathlib.Probability.Kernel.CondDistrib
import Mathlib.MeasureTheory.Integral.Prod
import Mathlib.Tactic

/-!
# P-STAT-06 — independent future blocks have constant conditional law

For the canonical product-space Doob construction, the coordinates not yet
revealed are independent of the revealed past. This file isolates the key
regular-conditional-distribution fact: if a future block `Y` is independent of
a past block `X`, and their laws are `ξ` and `ν`, then the conditional law of
`Y` given `X` is almost everywhere the constant kernel with value `ξ`.

This is the structural bridge needed to identify abstract conditional
expectations with explicit continuation integrals over the unrevealed product
law.
-/

namespace UEOT.V3.HilbertMeanIndependentCondDistrib

open MeasureTheory ProbabilityTheory
open scoped ProbabilityTheory

universe uΩ uβ uγ

variable {Ω : Type uΩ} {β : Type uβ} {γ : Type uγ}
variable [MeasurableSpace Ω] [mβ : MeasurableSpace β] [MeasurableSpace γ]
variable [StandardBorelSpace γ] [Nonempty γ]

/-- Independence plus the two marginal laws identifies the regular conditional
law of the future block as the constant future law. -/
theorem condDistrib_eq_const_of_indep
    (μ : Measure Ω) [IsProbabilityMeasure μ]
    (ν : Measure β) [IsProbabilityMeasure ν]
    (ξ : Measure γ) [IsProbabilityMeasure ξ]
    (X : Ω → β) (Y : Ω → γ)
    (hXm : Measurable X)
    (hXlaw : HasLaw X ν μ)
    (hYlaw : HasLaw Y ξ μ)
    (hXY : IndepFun X Y μ) :
    condDistrib Y X μ =ᵐ[ν] Kernel.const β ξ := by
  rw [← hXlaw.map_eq]
  apply condDistrib_ae_eq_of_measure_eq_compProd X hYlaw.aemeasurable
  calc
    μ.map (fun ω => (X ω, Y ω)) = ν.prod ξ :=
      (hXY.hasLaw_prod hXlaw hYlaw).map_eq
    _ = μ.map X ⊗ₘ Kernel.const β ξ := by
      rw [hXlaw.map_eq]
      simp

/-- For independent past and future blocks, conditional expectation with
respect to the sigma-algebra generated by the past is the explicit integral
over the unconditional future law. -/
theorem condExp_prod_ae_eq_integral_future_of_indep
    (μ : Measure Ω) [IsProbabilityMeasure μ]
    (ν : Measure β) [IsProbabilityMeasure ν]
    (ξ : Measure γ) [IsProbabilityMeasure ξ]
    (X : Ω → β) (Y : Ω → γ)
    (hXm : Measurable X)
    (hXlaw : HasLaw X ν μ)
    (hYlaw : HasLaw Y ξ μ)
    (hXY : IndepFun X Y μ)
    (f : β × γ → ℝ)
    (hf : StronglyMeasurable f)
    (hf_int : Integrable (fun ω => f (X ω, Y ω)) μ) :
    μ[fun ω => f (X ω, Y ω) | mβ.comap X] =ᵐ[μ]
      fun ω => ∫ y, f (X ω, y) ∂ξ := by
  have hcond := condExp_prod_ae_eq_integral_condDistrib
    (μ := μ) hXm hYlaw.aemeasurable hf hf_int
  have hk := condDistrib_eq_const_of_indep
    μ ν ξ X Y hXm hXlaw hYlaw hXY
  have hleft : StronglyMeasurable
      (fun x : β => ∫ y, f (x, y) ∂condDistrib Y X μ x) :=
    hf.integral_condDistrib
  have hright : StronglyMeasurable
      (fun x : β => ∫ y, f (x, y) ∂ξ) :=
    hf.integral_prod_right'
  have hint_eq : ∀ᵐ x ∂ν,
      (∫ y, f (x, y) ∂condDistrib Y X μ x) = ∫ y, f (x, y) ∂ξ := by
    filter_upwards [hk] with x hx
    rw [hx, Kernel.const_apply]
  have hp : Measurable fun x : β =>
      (∫ y, f (x, y) ∂condDistrib Y X μ x) = ∫ y, f (x, y) ∂ξ :=
    hleft.measurable.eq hright.measurable
  have hpull : ∀ᵐ ω ∂μ,
      (∫ y, f (X ω, y) ∂condDistrib Y X μ (X ω)) =
        ∫ y, f (X ω, y) ∂ξ :=
    (hXlaw.ae_iff hp).2 hint_eq
  exact hcond.trans hpull

end UEOT.V3.HilbertMeanIndependentCondDistrib
