import UEOT.V3.HilbertMeanProductBlockIndependence
import UEOT.V3.HilbertMeanDoobBlocks
import Mathlib.Probability.Process.Filtration
import Mathlib.Tactic

/-!
# P-STAT-06 — explicit prefix filtration on a finite canonical product

For a sample indexed by `Fin N`, time `n : ℕ` reveals exactly those coordinates
whose numeric index is at most `n`. Defining the filtration directly as the
sigma-algebra generated by the corresponding finite block projection keeps it
aligned with the block conditional-expectation theorem, avoiding a separate
identification with `Filtration.natural`.
-/

namespace UEOT.V3.HilbertMeanPrefixFiltration

open MeasureTheory
open UEOT.V3.HilbertMeanProductBlockIndependence
open UEOT.V3.HilbertMeanDoobBlocks

universe uH

variable {H : Type uH} [MeasurableSpace H]

/-- Coordinates revealed by natural time `n`. -/
def prefixBlock {N : ℕ} (n : ℕ) : Finset (Fin N) :=
  Finset.univ.filter fun i => i.1 ≤ n

@[simp] theorem mem_prefixBlock_iff {N : ℕ} (n : ℕ) (i : Fin N) :
    i ∈ prefixBlock n ↔ i.1 ≤ n := by
  simp [prefixBlock]

/-- At a genuine sample index `i`, the numeric prefix is exactly the canonical
`revealed i = past i ∪ {i}` block. -/
theorem prefixBlock_val_eq_revealed {N : ℕ} (i : Fin N) :
    prefixBlock i.1 = revealed i := by
  ext j
  simp [mem_prefixBlock_iff, mem_revealed_iff]

/-- The coordinates outside the prefix at `i` are exactly the strict future of
`i`. -/
theorem univ_sdiff_prefixBlock_val_eq_future {N : ℕ} (i : Fin N) :
    Finset.univ \ prefixBlock i.1 = future i := by
  ext j
  simp [mem_prefixBlock_iff, mem_future_iff, not_le]

/-- The revealed prefix through `i` is disjoint from the strict future. -/
theorem prefixBlock_disjoint_future {N : ℕ} (i : Fin N) :
    Disjoint (prefixBlock i.1) (future i) := by
  rw [prefixBlock_val_eq_revealed]
  exact revealed_disjoint_future i

/-- Restriction from a larger prefix block to a smaller one. -/
def restrictPrefix {N : ℕ} {n m : ℕ} (hnm : n ≤ m) :
    (prefixBlock (N := N) m → H) → (prefixBlock (N := N) n → H) :=
  fun x i => x ⟨i.1,
    (mem_prefixBlock_iff m i.1).2
      (((mem_prefixBlock_iff n i.1).1 i.2).trans hnm)⟩

/-- Prefix restriction is measurable. -/
theorem measurable_restrictPrefix {N : ℕ} {n m : ℕ} (hnm : n ≤ m) :
    Measurable (restrictPrefix (N := N) (H := H) hnm) := by
  rw [measurable_pi_iff]
  intro i
  exact measurable_pi_apply _

/-- Smaller block projection factors through the larger block projection. -/
theorem blockProjection_prefixBlock_factor {N : ℕ} {n m : ℕ} (hnm : n ≤ m) :
    blockProjection (H := H) (prefixBlock (N := N) n) =
      restrictPrefix (N := N) (H := H) hnm ∘
        blockProjection (H := H) (prefixBlock (N := N) m) := by
  funext ω i
  rfl

/-- Sigma algebra generated by the prefix block at time `n`. -/
def prefixSigma {N : ℕ} (n : ℕ) : MeasurableSpace (Fin N → H) :=
  MeasurableSpace.comap
    (blockProjection (H := H) (prefixBlock (N := N) n))
    inferInstance

/-- Prefix sigma-algebras are monotone in time. -/
theorem prefixSigma_mono {N : ℕ} :
    Monotone (prefixSigma (H := H) (N := N)) := by
  intro n m hnm
  exact MeasurableSpace.comap_le_comap_of_eq_comp
    (restrictPrefix (N := N) (H := H) hnm)
    (measurable_restrictPrefix (N := N) (H := H) hnm)
    (blockProjection_prefixBlock_factor (N := N) (H := H) hnm)

/-- Every prefix sigma algebra is contained in the ambient product measurable
space. -/
theorem prefixSigma_le {N : ℕ} (n : ℕ) :
    prefixSigma (H := H) (N := N) n ≤
      (inferInstance : MeasurableSpace (Fin N → H)) := by
  exact (measurable_blockProjection (H := H) (prefixBlock (N := N) n)).comap_le

/-- Explicit natural-number indexed prefix filtration. -/
def prefixFiltration {N : ℕ} :
    Filtration ℕ (inferInstance : MeasurableSpace (Fin N → H)) where
  seq := prefixSigma (H := H) (N := N)
  mono' := prefixSigma_mono (H := H) (N := N)
  le' := prefixSigma_le (H := H) (N := N)

@[simp] theorem prefixFiltration_apply {N : ℕ} (n : ℕ) :
    prefixFiltration (H := H) (N := N) n = prefixSigma (H := H) (N := N) n := rfl

/-- Source-facing prefix/future conditional-expectation bridge. At a genuine
sample index `i`, conditioning a function of the revealed prefix and strict
future on the prefix filtration is exactly integration over the unconditional
future-block law. -/
theorem condExp_prefix_future_ae_eq_integral
    [StandardBorelSpace H] [Nonempty H]
    {N : ℕ}
    (μ : Fin N → Measure H) [∀ j, IsProbabilityMeasure (μ j)]
    (i : Fin N)
    (f : (prefixBlock i.1 → H) × (future i → H) → ℝ)
    (hf : StronglyMeasurable f)
    (hf_int : Integrable
      (fun (ω : Fin N → H) =>
        f (blockProjection (prefixBlock i.1) ω, blockProjection (future i) ω))
      (Measure.pi μ)) :
    (Measure.pi μ)[fun (ω : Fin N → H) =>
        f (blockProjection (prefixBlock i.1) ω, blockProjection (future i) ω) |
      prefixSigma (H := H) (N := N) i.1] =ᵐ[Measure.pi μ]
      fun ω => ∫ y,
        f (blockProjection (prefixBlock i.1) ω, y) ∂blockLaw μ (future i) := by
  exact condExp_blocks_ae_eq_integral_second
    μ (prefixBlock i.1) (future i) (prefixBlock_disjoint_future i) f hf hf_int

end UEOT.V3.HilbertMeanPrefixFiltration
