import UEOT.V3.InformationPredictiveZeroTVRecovery
import UEOT.V3.InformationRandomEncoder
import Mathlib.Probability.Kernel.Composition.MeasureComp

/-!
# P-INFO-03 — canonical zero-distortion achievability

The converse side of the zero-distortion theorem is attained by the canonical
choice `M=C`: encode the predictive-core label deterministically and decode its
canonical future law.  This module fixes the exact randomized-encoder joint law
generated by that deterministic core encoder and the matching decoder.
-/

namespace UEOT.V3.InformationPredictiveAchievability

noncomputable section

open MeasureTheory ProbabilityTheory
open scoped ENNReal ProbabilityTheory
open UEOT.V3.TotalVariation
open UEOT.V3.InformationKernelTV
open UEOT.V3.InformationRandomEncoder
open UEOT.V3.InformationPredictiveZeroTVRecovery

universe uU uH uC uY

variable {U : Type uU} {H : Type uH} {C : Type uC} {Y : Type uY}
variable [MeasurableSpace U] [MeasurableSpace H] [MeasurableSpace C]
variable [MeasurableSpace Y]
variable [StandardBorelSpace U] [StandardBorelSpace H] [StandardBorelSpace C]
variable [StandardBorelSpace Y]
variable [Nonempty H] [Nonempty C] [Nonempty Y]

/-- The source-achieving encoder `M=C`: emit the deterministic canonical core
label `c(U,H)`. -/
noncomputable def canonicalCoreEncoder
    (c : U × H → C) (hc : Measurable c) : Kernel (U × H) C :=
  Kernel.deterministic c hc

instance canonicalCoreEncoder_isMarkov
    (c : U × H → C) (hc : Measurable c) :
    IsMarkovKernel (canonicalCoreEncoder c hc) := by
  unfold canonicalCoreEncoder
  infer_instance

/-- Embedding of a source sample together with its canonical core label into
the `U × (H × C)` geometry used by conditional mutual information. -/
def canonicalCoreGraph
    (c : U × H → C) : U × H → U × (H × C) :=
  fun uh => (uh.1, (uh.2, c uh))

lemma measurable_canonicalCoreGraph
    (c : U × H → C) (hc : Measurable c) :
    Measurable (canonicalCoreGraph c) := by
  unfold canonicalCoreGraph
  exact measurable_fst.prodMk (measurable_snd.prodMk hc)

/-- **Canonical encoder joint-law identity.**  Running the generic randomized
encoder construction with the deterministic core encoder is exactly the
pushforward of the source law along the graph `(u,h) ↦ (u,(h,c(u,h)))`. -/
theorem randomEncoderJoint_canonicalCoreEncoder
    (μ : Measure (U × H)) [IsProbabilityMeasure μ]
    (c : U × H → C) (hc : Measurable c) :
    randomEncoderJoint μ (canonicalCoreEncoder c hc) =
      μ.map (canonicalCoreGraph c) := by
  unfold randomEncoderJoint canonicalCoreEncoder
  rw [Measure.compProd_deterministic hc]
  have hpair : Measurable (fun uh : U × H => (uh, c uh)) :=
    measurable_id.prodMk hc
  rw [Measure.map_map
    (measurable_encoderReassoc (U := U) (H := H) (M := C))
    hpair]
  apply Measure.map_congr
  rfl

/-- Decoder attaining zero predictive distortion when the encoder emits the
canonical core itself: ignore `U` and return the future law indexed by `C`. -/
noncomputable def canonicalCoreDecoder
    (κC : Kernel C Y) : Kernel (U × C) Y :=
  κC.comap Prod.snd measurable_snd

instance canonicalCoreDecoder_isMarkov
    (κC : Kernel C Y) [IsMarkovKernel κC] :
    IsMarkovKernel (canonicalCoreDecoder (U := U) κC) := by
  unfold canonicalCoreDecoder
  infer_instance

/-- On the support graph of the deterministic core encoder, the source
canonical predictive kernel and the canonical decoder kernel agree pointwise. -/
theorem canonicalPredictive_eq_decoded_on_coreGraph
    (κC : Kernel C Y) [IsMarkovKernel κC]
    (c : U × H → C) (hc : Measurable c)
    (uh : U × H) :
    canonicalPredictiveKernel (M := C) κC c hc (canonicalCoreGraph c uh) =
      decodedPredictiveKernel (H := H)
        (canonicalCoreDecoder (U := U) κC) (canonicalCoreGraph c uh) := by
  simp [canonicalPredictiveKernel, decodedPredictiveKernel,
    canonicalCoreDecoder, canonicalCoreGraph, Kernel.comap_apply]

/-- **Canonical zero-distortion achievability.**  Under the true law generated
by the deterministic encoder `M=C`, decoding with the canonical future law has
exactly zero expected total-variation distortion. -/
theorem canonicalCoreEncoder_zeroDistortion
    (μ : Measure (U × H)) [IsProbabilityMeasure μ]
    (c : U × H → C) (hc : Measurable c)
    (κC : Kernel C Y) [IsMarkovKernel κC] :
    (∫⁻ z,
      ENNReal.ofReal
        (tvDist
          (canonicalPredictiveKernel (M := C) κC c hc z)
          (decodedPredictiveKernel (H := H)
            (canonicalCoreDecoder (U := U) κC) z))
      ∂randomEncoderJoint μ (canonicalCoreEncoder c hc)) = 0 := by
  rw [randomEncoderJoint_canonicalCoreEncoder μ c hc]
  have hmeas : Measurable fun z : U × (H × C) =>
      ENNReal.ofReal
        (tvDist
          (canonicalPredictiveKernel (M := C) κC c hc z)
          (decodedPredictiveKernel (H := H)
            (canonicalCoreDecoder (U := U) κC) z)) :=
    (measurable_tvDist_kernel
      (canonicalPredictiveKernel (M := C) κC c hc)
      (decodedPredictiveKernel (H := H)
        (canonicalCoreDecoder (U := U) κC))).ennreal_ofReal
  rw [lintegral_map' hmeas.aemeasurable
    (measurable_canonicalCoreGraph c hc).aemeasurable]
  simp_rw [canonicalPredictive_eq_decoded_on_coreGraph κC c hc]
  simp [tvDist_self_eq_zero]

end

end UEOT.V3.InformationPredictiveAchievability
