import UEOT.V3.InformationDecoderFano
import Mathlib.Analysis.Convex.Integral
import Mathlib.Probability.Kernel.Integral

/-!
# P-INFO-04 — sharp decoder conditional-entropy bound

This module isolates the conditional-entropy core of the frozen Fano statement.
For a probability base law `μ`, a posterior Markov kernel `π : Y → Fin M`, and
an arbitrary measurable decoder `d : Y → Fin M`, define

`e = E[1 - π_y {d(y)}]`.

Then

`H_π(J|Y) ≤ h₂(e) + e log(M-1)`.

No MAP/Bayes-risk substitution is used: the pointwise theorem is applied at the
actual decoded index `d(y)`.
-/

namespace UEOT.V3.InformationDecoderConditionalFano

open MeasureTheory ProbabilityTheory
open scoped BigOperators ENNReal
open UEOT.V3.InformationDecoderFano

universe uY

variable {Y : Type uY} [MeasurableSpace Y]

/-- Correct-decoding posterior mass, written as a finite measurable selector. -/
noncomputable def decoderCorrectProb {M : ℕ}
    (π : Kernel Y (Fin M)) (d : Y → Fin M) (y : Y) : ℝ :=
  ∑ j, if d y = j then (π y {j}).toReal else 0

/-- Average conditional error probability of decoder `d`. -/
noncomputable def decoderError {M : ℕ}
    (μ : Measure Y) (π : Kernel Y (Fin M)) (d : Y → Fin M) : ℝ :=
  ∫ y, (1 - decoderCorrectProb π d y) ∂μ

/-- Conditional Shannon entropy generated by a finite posterior kernel. -/
noncomputable def posteriorConditionalEntropy {M : ℕ}
    (μ : Measure Y) (π : Kernel Y (Fin M)) : ℝ :=
  ∫ y, (∑ j, Real.negMulLog ((π y {j}).toReal)) ∂μ

lemma decoderCorrectProb_eq {M : ℕ}
    (π : Kernel Y (Fin M)) (d : Y → Fin M) (y : Y) :
    decoderCorrectProb π d y = (π y {d y}).toReal := by
  classical
  simp [decoderCorrectProb]

lemma measurable_decoderCorrectProb {M : ℕ}
    (π : Kernel Y (Fin M)) (d : Y → Fin M) (hd : Measurable d) :
    Measurable (decoderCorrectProb π d) := by
  classical
  unfold decoderCorrectProb
  refine Finset.measurable_sum _ ?_
  intro j hj
  have hs : MeasurableSet (d ⁻¹' ({j} : Set (Fin M))) :=
    hd (measurableSet_singleton j)
  have hm : Measurable (fun y => (π y {j}).toReal) :=
    (Kernel.measurable_coe π (measurableSet_singleton j)).ennreal_toReal
  simpa [Set.mem_preimage, Set.mem_singleton_iff] using
    (Measurable.ite hs hm measurable_const)

lemma decoderCorrectProb_mem_Icc {M : ℕ}
    (π : Kernel Y (Fin M)) [IsMarkovKernel π]
    (d : Y → Fin M) (y : Y) :
    decoderCorrectProb π d y ∈ Set.Icc (0 : ℝ) 1 := by
  rw [decoderCorrectProb_eq]
  constructor
  · exact ENNReal.toReal_nonneg
  · rw [← ENNReal.toReal_one]
    exact ENNReal.toReal_mono ENNReal.one_ne_top prob_le_one

lemma measurable_posteriorEntropyIntegrand {M : ℕ}
    (π : Kernel Y (Fin M)) :
    Measurable (fun y => ∑ j, Real.negMulLog ((π y {j}).toReal)) := by
  classical
  refine Finset.measurable_sum _ ?_
  intro j hj
  exact Real.continuous_negMulLog.measurable.comp
    ((Kernel.measurable_coe π (measurableSet_singleton j)).ennreal_toReal)

/-- **Sharp arbitrary-decoder conditional Fano inequality.** -/
theorem posteriorConditionalEntropy_le_decoderError
    {M : ℕ} (hM : 2 ≤ M)
    (μ : Measure Y) [IsProbabilityMeasure μ]
    (π : Kernel Y (Fin M)) [IsMarkovKernel π]
    (d : Y → Fin M) (hd : Measurable d) :
    posteriorConditionalEntropy μ π ≤
      Real.binEntropy (decoderError μ π d) +
        decoderError μ π d * Real.log ((M : ℝ) - 1) := by
  classical
  let c : Y → ℝ := decoderCorrectProb π d
  let e : Y → ℝ := fun y => 1 - c y

  have hc_meas : Measurable c := by
    simpa [c] using measurable_decoderCorrectProb π d hd
  have hc_mem : ∀ y, c y ∈ Set.Icc (0 : ℝ) 1 := by
    intro y
    simpa [c] using decoderCorrectProb_mem_Icc π d y
  have he_meas : Measurable e := by
    exact measurable_const.sub hc_meas
  have he_mem : ∀ᵐ y ∂μ, e y ∈ Set.Icc (0 : ℝ) 1 := by
    exact Filter.Eventually.of_forall fun y => by
      dsimp [e]
      have h := hc_mem y
      constructor <;> linarith [h.1, h.2]
  have he_int : Integrable e μ := by
    refine Integrable.mono' (integrable_const (1 : ℝ))
      he_meas.aestronglyMeasurable ?_
    filter_upwards [he_mem] with y hy
    rw [Real.norm_eq_abs, abs_of_nonneg hy.1]
    simpa using hy.2

  have hbin_meas : Measurable (fun y => Real.binEntropy (e y)) :=
    Real.binEntropy_continuous.measurable.comp he_meas
  have hbin_int : Integrable (fun y => Real.binEntropy (e y)) μ := by
    refine Integrable.mono' (integrable_const (Real.log 2))
      hbin_meas.aestronglyMeasurable ?_
    filter_upwards [he_mem] with y hy
    rw [Real.norm_eq_abs,
      abs_of_nonneg (Real.binEntropy_nonneg hy.1 hy.2),
      Real.norm_eq_abs, abs_of_nonneg (Real.log_nonneg (by norm_num))]
    exact Real.binEntropy_le_log_two

  have hlog_nonneg : (0 : ℝ) ≤ Real.log ((M : ℝ) - 1) := by
    apply Real.log_nonneg
    have hmR : (2 : ℝ) ≤ (M : ℝ) := by exact_mod_cast hM
    linarith

  have he_nonneg : 0 ≤ decoderError μ π d := by
    unfold decoderError
    change 0 ≤ ∫ y, e y ∂μ
    exact integral_nonneg_of_ae (he_mem.mono fun _ hy => hy.1)
  have he_le_one : decoderError μ π d ≤ 1 := by
    unfold decoderError
    change (∫ y, e y ∂μ) ≤ 1
    calc
      (∫ y, e y ∂μ) ≤ ∫ _y, (1 : ℝ) ∂μ :=
        integral_mono_ae he_int (integrable_const (1 : ℝ))
          (he_mem.mono fun _ hy => hy.2)
      _ = 1 := by simp

  have hpoint :
      (fun y => ∑ j, Real.negMulLog ((π y {j}).toReal)) ≤ᵐ[μ]
        fun y => Real.binEntropy (e y) + e y * Real.log ((M : ℝ) - 1) := by
    refine Filter.Eventually.of_forall fun y => ?_
    have hp0 : ∀ j : Fin M, 0 ≤ (π y {j}).toReal := fun _ => ENNReal.toReal_nonneg
    have hp1 : ∑ j : Fin M, (π y {j}).toReal = 1 := by
      have htop : ∀ j : Fin M, π y {j} ≠ ⊤ := fun j => measure_ne_top (π y) {j}
      rw [← ENNReal.toReal_sum (fun j _ => htop j)]
      rw [sum_measure_singleton, Finset.coe_univ, measure_univ, ENNReal.toReal_one]
    have hsharp := sharp_discrete_fano_at_index hM
      (fun j : Fin M => (π y {j}).toReal) hp0 hp1 (d y)
    rw [show e y = 1 - (π y {d y}).toReal by
      simp [e, c, decoderCorrectProb_eq]]
    exact hsharp

  have hRHS_int : Integrable
      (fun y => Real.binEntropy (e y) + e y * Real.log ((M : ℝ) - 1)) μ :=
    hbin_int.add (he_int.mul_const _)

  have hjensen :
      (∫ y, Real.binEntropy (e y) ∂μ) ≤
        Real.binEntropy (∫ y, e y ∂μ) := by
    have hconc := Real.strictConcave_binEntropy.concaveOn
    have h := hconc.le_map_integral
      Real.binEntropy_continuous.continuousOn isClosed_Icc
      he_mem he_int
      (by simpa [Function.comp_def] using hbin_int)
    simpa [Function.comp_def] using h

  by_cases hH : Integrable
      (fun y => ∑ j, Real.negMulLog ((π y {j}).toReal)) μ
  · unfold posteriorConditionalEntropy
    calc
      (∫ y, ∑ j, Real.negMulLog ((π y {j}).toReal) ∂μ)
          ≤ ∫ y, (Real.binEntropy (e y) +
              e y * Real.log ((M : ℝ) - 1)) ∂μ :=
        integral_mono_ae hH hRHS_int hpoint
      _ = (∫ y, Real.binEntropy (e y) ∂μ) +
          (∫ y, e y ∂μ) * Real.log ((M : ℝ) - 1) := by
        rw [integral_add hbin_int (he_int.mul_const _), integral_mul_const]
      _ ≤ Real.binEntropy (∫ y, e y ∂μ) +
          (∫ y, e y ∂μ) * Real.log ((M : ℝ) - 1) := by
        gcongr
      _ = Real.binEntropy (decoderError μ π d) +
          decoderError μ π d * Real.log ((M : ℝ) - 1) := by
        rfl
  · unfold posteriorConditionalEntropy
    rw [integral_undef hH]
    exact add_nonneg
      (Real.binEntropy_nonneg he_nonneg he_le_one)
      (mul_nonneg he_nonneg hlog_nonneg)

end UEOT.V3.InformationDecoderConditionalFano
