import UEOT.V3.InformationCore
import Mathlib.InformationTheory.KullbackLeibler.DataProcessing
import Mathlib.Probability.Kernel.Composition.Prod
import Mathlib.Probability.Kernel.Composition.MapComap
import Mathlib.Probability.Kernel.Composition.Lemmas

/-!
# P-INFO-01 entropy-bound reduction

The source-facing inequality `I(M;Y) ≤ H(M)` is separated into standard pieces.
This module formalizes the channel/data-processing half and, crucially, identifies
the two channel outputs with the actual `(M,Y)` joint law and the product of its
marginals.  The discrete copy-KL/Shannon identity is proved in
`InformationDiscreteEntropy`.
-/

namespace UEOT.V3.InformationEntropyBound

open MeasureTheory ProbabilityTheory InformationTheory
open UEOT.V3.InformationCore
open scoped ENNReal ProbabilityTheory

universe uM uY

variable {M : Type uM} {Y : Type uY}
variable [MeasurableSpace M] [MeasurableSpace Y]

/-- The diagonal/copy law of a random state. -/
noncomputable def copyJoint (μ : Measure M) : Measure (M × M) :=
  μ.map (fun m => (m, m))

/-- A Markov channel on a copied pair `(m₁,m₂)` which retains the first
coordinate and sends the second through `κ`.  On a diagonal input this produces
`(m,Y)` with `Y ∼ κ m`; on an independent-copy input it destroys dependence
between the retained first coordinate and the channel output. -/
noncomputable def retainFirstSendSecond (κ : Kernel M Y) :
    Kernel (M × M) (M × Y) :=
  (Kernel.deterministic Prod.fst measurable_fst) ×ₖ
    Kernel.prodMkLeft M κ

instance retainFirstSendSecond_isMarkov
    (κ : Kernel M Y) [IsMarkovKernel κ] :
    IsMarkovKernel (retainFirstSendSecond κ) := by
  unfold retainFirstSendSecond
  infer_instance

/-- The copied law is finite whenever its source law is finite.  This explicit
bridge is needed because typeclass search deliberately does not unfold the
project-local `copyJoint` abbreviation. -/
instance copyJoint_isFinite
    (μ : Measure M) [IsFiniteMeasure μ] :
    IsFiniteMeasure (copyJoint μ) := by
  unfold copyJoint
  infer_instance

/-- The project-local copied-pair channel is exactly the standard parallel
channel `id ∥ₖ κ`: retain the first coordinate and process the second. -/
theorem retainFirstSendSecond_eq_parallelComp
    (κ : Kernel M Y) [IsSFiniteKernel κ] :
    retainFirstSendSecond κ = Kernel.id ∥ₖ κ := by
  ext z
  simp [retainFirstSendSecond, Kernel.prod_apply, Kernel.parallelComp_apply,
    Kernel.prodMkLeft_apply, Kernel.id_apply, Kernel.deterministic_apply]

/-- The diagonal copy law is the output of the standard copy kernel. -/
theorem copyJoint_eq_copy_comp
    (μ : Measure M) [SFinite μ] :
    copyJoint μ = Kernel.copy M ∘ₘ μ := by
  unfold copyJoint
  calc
    μ.map (fun m => (m, m)) = μ.map Function.diag := by rfl
    _ = μ ⊗ₘ Kernel.id := (Measure.compProd_id (μ := μ)).symm
    _ = Kernel.copy M ∘ₘ μ := Measure.compProd_id_eq_copy_comp

/-- Sending the second component of a diagonal copy through `κ` gives the
ordinary composition-product joint law `μ ⊗ₘ κ`. -/
theorem retainFirstSendSecond_comp_copyJoint
    (μ : Measure M) [SFinite μ]
    (κ : Kernel M Y) [IsSFiniteKernel κ] :
    retainFirstSendSecond κ ∘ₘ copyJoint μ = μ ⊗ₘ κ := by
  rw [retainFirstSendSecond_eq_parallelComp, copyJoint_eq_copy_comp,
    Measure.comp_assoc, Kernel.parallelComp_comp_copy]
  exact (Measure.compProd_eq_comp_prod μ κ).symm

/-- On two independent copies, retaining the first and processing the second
produces the product of the first marginal and the channel output marginal. -/
theorem retainFirstSendSecond_comp_prod
    (μ : Measure M) [SFinite μ]
    (κ : Kernel M Y) [IsSFiniteKernel κ] :
    retainFirstSendSecond κ ∘ₘ μ.prod μ = μ.prod (κ ∘ₘ μ) := by
  rw [retainFirstSendSecond_eq_parallelComp]
  exact (Measure.prod_comp_right (μ := μ) (ν := μ) (κ := κ)).symm

/-- Channel data processing: the KL separation remaining after retaining the
first copy and processing the second through `κ` cannot exceed the KL
separation of the original diagonal copy law from two independent copies. -/
theorem channel_kl_le_copy_kl
    (μ : Measure M) [IsProbabilityMeasure μ]
    (κ : Kernel M Y) [IsMarkovKernel κ] :
    klDiv (retainFirstSendSecond κ ∘ₘ copyJoint μ)
        (retainFirstSendSecond κ ∘ₘ μ.prod μ) ≤
      klDiv (copyJoint μ) (μ.prod μ) := by
  exact InformationTheory.klDiv_comp_right_le
    (copyJoint μ) (μ.prod μ) (retainFirstSendSecond κ)

/-- The channel statement is literally the mutual-information upper bound for
the joint law generated by `μ` and `κ`. -/
theorem mutualInfo_compProd_le_copy_kl
    (μ : Measure M) [IsProbabilityMeasure μ]
    (κ : Kernel M Y) [IsMarkovKernel κ] :
    mutualInfo (μ ⊗ₘ κ) ≤ klDiv (copyJoint μ) (μ.prod μ) := by
  have h := channel_kl_le_copy_kl μ κ
  rw [retainFirstSendSecond_comp_copyJoint μ κ,
    retainFirstSendSecond_comp_prod μ κ] at h
  simpa [mutualInfo, Measure.fst_compProd, Measure.snd_compProd] using h

end UEOT.V3.InformationEntropyBound