import UEOT.V3.PredictableOLS
import Mathlib.Tactic

/-!
# P-INV-05 — OLS normal equation from the source linear model

The source model is

`Y_t = phi_t^T thetaStar + xi_t`.

For unconstrained finite-dimensional least squares, the normal equation is the
canonical algebraic characterization of an OLS solution.  This module isolates
that characterization and proves that, under the source model, it is exactly

`G_N (thetaHat - thetaStar) = sum_t phi_t xi_t`.
-/

namespace UEOT.V3.PredictableOLSNormalEquation

open UEOT.V3.DesignIdentifiability
open UEOT.V3.PredictableOLS
open scoped BigOperators

/-- Response generated by the source linear model. -/
def linearResponse {N d : ℕ}
    (phi : Fin N → Fin d → ℝ)
    (thetaStar : Fin d → ℝ)
    (xi : Fin N → ℝ) : Fin N → ℝ :=
  fun t => designMap phi thetaStar t + xi t

/-- Normal-equation characterization of an unconstrained OLS solution. -/
def IsOLSNormalEq {N d : ℕ}
    (phi : Fin N → Fin d → ℝ)
    (Y : Fin N → ℝ)
    (thetaHat : Fin d → ℝ) : Prop :=
  ∀ j : Fin d,
    ∑ t : Fin N, phi t j * (designMap phi thetaHat t - Y t) = 0

/-- In the source linear model, the OLS normal equation becomes the exact
error-score identity `G_N (thetaHat-thetaStar) = Z`. -/
theorem gramAction_error_eq_scoreVector
    {N d : ℕ}
    (phi : Fin N → Fin d → ℝ)
    (thetaStar thetaHat : Fin d → ℝ)
    (xi : Fin N → ℝ)
    (hOLS : IsOLSNormalEq phi (linearResponse phi thetaStar xi) thetaHat) :
    gramAction phi (thetaHat - thetaStar) = scoreVector phi xi := by
  funext j
  have hj := hOLS j
  have hj' :
      (∑ t : Fin N,
        phi t j * (designMap phi thetaHat t - designMap phi thetaStar t)) -
        (∑ t : Fin N, phi t j * xi t) = 0 := by
    rw [← Finset.sum_sub_distrib]
    convert hj using 1
    apply Finset.sum_congr rfl
    intro t ht
    simp only [linearResponse]
    ring
  unfold gramAction scoreVector
  calc
    (∑ t : Fin N, phi t j * designMap phi (thetaHat - thetaStar) t) =
        ∑ t : Fin N,
          phi t j * (designMap phi thetaHat t - designMap phi thetaStar t) := by
      apply Finset.sum_congr rfl
      intro t ht
      rw [congrFun (designMap_sub phi thetaHat thetaStar) t]
      simp only [Pi.sub_apply]
    _ = ∑ t : Fin N, phi t j * xi t := sub_eq_zero.mp hj'

end UEOT.V3.PredictableOLSNormalEquation
