import UEOT.V3.ReflexiveStatePathLaw
import Mathlib.MeasureTheory.Constructions.Projective

/-!
# P-REF-01 uniqueness layer — finite prefixes determine the path law

A candidate complete-history path measure is admissible when every finite
prefix equals the finite law recursively generated from the initial law, the
causal policy and the controlled reflexive kernel. These finite laws form a
projective family. Mathlib's projective-limit uniqueness then identifies the
candidate with the Ionescu--Tulcea law.

This avoids the vacuous formulation `nu = canonicalLaw` as an assumption.
-/

namespace UEOT.V3.ReflexiveStatePathUniqueness

open MeasureTheory ProbabilityTheory Finset
open UEOT.V3.FiniteHistory
open UEOT.V3.ReflexiveStateAugmentation
open UEOT.V3.ReflexiveStatePathLaw
open scoped ProbabilityTheory

universe uZ uA

variable {Z : Type uZ} {A : Type uA}
variable [MeasurableSpace Z] [MeasurableSpace A]

/-- A complete-history path law has exactly the finite prefix laws recursively
specified by `(mu0, K, pi)`. -/
def PrefixCompatible
    (mu0 : Measure Z)
    (K : Kernel (Z × A) Z)
    (pi : CausalPolicy Z A)
    (nu : Measure (ℕ → Carrier Z A)) : Prop :=
  ∀ n, nu.map (Preorder.frestrictLe n) = finiteHistoryLaw mu0 K pi n

instance isProbabilityMeasure_initialHistoryPrefixLaw
    (mu0 : Measure Z) [IsProbabilityMeasure mu0] :
    IsProbabilityMeasure (initialHistoryPrefixLaw (A := A) mu0) := by
  unfold initialHistoryPrefixLaw
  exact Measure.isProbabilityMeasure_map
    (MeasurableEquiv.piUnique (fun _ : Iic 0 => Carrier Z A)).symm.measurable.aemeasurable

instance isProbabilityMeasure_finiteHistoryLaw
    (mu0 : Measure Z)
    (K : Kernel (Z × A) Z)
    (pi : CausalPolicy Z A)
    [IsProbabilityMeasure mu0]
    [IsMarkovKernel K]
    [∀ n, IsMarkovKernel (pi n)]
    (n : ℕ) :
    IsProbabilityMeasure (finiteHistoryLaw mu0 K pi n) := by
  unfold finiteHistoryLaw
  infer_instance

/-- The recursively specified finite prefix laws are themselves projectively
consistent. -/
theorem finiteHistoryLaw_projective
    (mu0 : Measure Z)
    (K : Kernel (Z × A) Z)
    (pi : CausalPolicy Z A)
    [IsMarkovKernel K]
    [∀ n, IsMarkovKernel (pi n)]
    {a b : ℕ} (hab : a ≤ b) :
    (finiteHistoryLaw mu0 K pi b).map
        (Preorder.frestrictLe₂ (π := fun _ : ℕ => Carrier Z A) hab) =
      finiteHistoryLaw mu0 K pi a := by
  rw [← historyPathLaw_prefix mu0 K pi b,
      ← historyPathLaw_prefix mu0 K pi a]
  rw [Measure.map_map
    (Preorder.measurable_frestrictLe₂
      (X := fun _ : ℕ => Carrier Z A) hab)
    (Preorder.measurable_frestrictLe b)]
  rfl

/-- Finite-set-indexed projective family generated by the canonical prefix
laws. -/
noncomputable def historyPrefixFamily
    (mu0 : Measure Z)
    (K : Kernel (Z × A) Z)
    (pi : CausalPolicy Z A) :
    (I : Finset ℕ) → Measure ((i : I) → Carrier Z A) :=
  inducedFamily
    (X := fun _ : ℕ => Carrier Z A)
    (fun n => finiteHistoryLaw mu0 K pi n)

instance isProbabilityMeasure_historyPrefixFamily
    (mu0 : Measure Z)
    (K : Kernel (Z × A) Z)
    (pi : CausalPolicy Z A)
    [IsProbabilityMeasure mu0]
    [IsMarkovKernel K]
    [∀ n, IsMarkovKernel (pi n)]
    (I : Finset ℕ) :
    IsProbabilityMeasure (historyPrefixFamily mu0 K pi I) := by
  unfold historyPrefixFamily
  infer_instance

/-- The finite family is projective because restricting a later recursively
constructed prefix gives the earlier one. -/
theorem historyPrefixFamily_projective
    (mu0 : Measure Z)
    (K : Kernel (Z × A) Z)
    (pi : CausalPolicy Z A)
    [IsMarkovKernel K]
    [∀ n, IsMarkovKernel (pi n)] :
    IsProjectiveMeasureFamily
      (α := fun _ : ℕ => Carrier Z A)
      (historyPrefixFamily mu0 K pi) := by
  unfold historyPrefixFamily
  exact isProjectiveMeasureFamily_inducedFamily
    (X := fun _ : ℕ => Carrier Z A)
    (fun n => finiteHistoryLaw mu0 K pi n)
    (fun a b hab => finiteHistoryLaw_projective mu0 K pi hab)

/-- Any measure with the canonical first-coordinate prefixes is a projective
limit of the same finite family. -/
theorem isProjectiveLimit_of_prefixCompatible
    (mu0 : Measure Z)
    (K : Kernel (Z × A) Z)
    (pi : CausalPolicy Z A)
    [IsMarkovKernel K]
    [∀ n, IsMarkovKernel (pi n)]
    (nu : Measure (ℕ → Carrier Z A))
    (hnu : PrefixCompatible mu0 K pi nu) :
    IsProjectiveLimit nu (historyPrefixFamily mu0 K pi) := by
  have hproj := historyPrefixFamily_projective mu0 K pi
  rw [isProjectiveLimit_nat_iff hproj]
  intro n
  unfold historyPrefixFamily
  rw [inducedFamily_Iic]
  exact hnu n

/-- The Ionescu--Tulcea history law has the required finite prefixes. -/
theorem historyPathLaw_prefixCompatible
    (mu0 : Measure Z)
    (K : Kernel (Z × A) Z)
    (pi : CausalPolicy Z A)
    [IsMarkovKernel K]
    [∀ n, IsMarkovKernel (pi n)] :
    PrefixCompatible mu0 K pi (historyPathLaw mu0 K pi) := by
  intro n
  exact historyPathLaw_prefix mu0 K pi n

/-- Non-vacuous uniqueness of the complete-history law from all finite prefix
laws. -/
theorem historyPathLaw_unique
    (mu0 : Measure Z)
    (K : Kernel (Z × A) Z)
    (pi : CausalPolicy Z A)
    [IsProbabilityMeasure mu0]
    [IsMarkovKernel K]
    [∀ n, IsMarkovKernel (pi n)]
    (nu : Measure (ℕ → Carrier Z A))
    (hnu : PrefixCompatible mu0 K pi nu) :
    nu = historyPathLaw mu0 K pi := by
  have hnuLim : IsProjectiveLimit nu (historyPrefixFamily mu0 K pi) :=
    isProjectiveLimit_of_prefixCompatible mu0 K pi nu hnu
  have hcanonicalLim :
      IsProjectiveLimit (historyPathLaw mu0 K pi)
        (historyPrefixFamily mu0 K pi) :=
    isProjectiveLimit_of_prefixCompatible mu0 K pi _
      (historyPathLaw_prefixCompatible mu0 K pi)
  exact hnuLim.unique hcanonicalLim

/-- A `Z`-path law is source-admissible when it is the state readout of a
complete-history law having exactly the recursively specified finite prefixes. -/
def IsReflexivePathLaw
    (mu0 : Measure Z)
    (K : Kernel (Z × A) Z)
    (pi : CausalPolicy Z A)
    (rho : Measure (ℕ → Z)) : Prop :=
  ∃ nu : Measure (ℕ → Carrier Z A),
    PrefixCompatible mu0 K pi nu ∧
      rho = nu.map statePathReadout

/-- **P-REF-01 path-law clause.** For an arbitrary causal randomized policy,
the reflexive-state path law is uniquely determined by the initial law and the
controlled kernel (together with the fixed policy). The proof is by
Ionescu--Tulcea construction plus projective-limit uniqueness, not by assuming
the candidate equals the canonical law. -/
theorem p_ref_01_pathlaw_unique
    (mu0 : Measure Z)
    (K : Kernel (Z × A) Z)
    (pi : CausalPolicy Z A)
    [IsProbabilityMeasure mu0]
    [IsMarkovKernel K]
    [∀ n, IsMarkovKernel (pi n)] :
    ∃! rho : Measure (ℕ → Z), IsReflexivePathLaw mu0 K pi rho := by
  refine ⟨reflexivePathLaw mu0 K pi, ?_, ?_⟩
  · refine ⟨historyPathLaw mu0 K pi,
      historyPathLaw_prefixCompatible mu0 K pi, ?_⟩
    rfl
  · intro rho hrho
    rcases hrho with ⟨nu, hnu, rfl⟩
    rw [historyPathLaw_unique mu0 K pi nu hnu]
    rfl

end UEOT.V3.ReflexiveStatePathUniqueness
