import UEOT.V3.DynamicsKernel
import UEOT.V3.PathError
import Mathlib.Probability.Kernel.Composition.MapComap
import Mathlib.MeasureTheory.Integral.Bochner.Basic
import Mathlib.Data.EReal.Basic

/-!
# P-FAC-01 foundation — representation covariance

This module isolates the coordinate-transport layer of P-FAC-01.  A
bimeasurable bijection of the microscopic state space transports a Markov
kernel by pushforward on outputs and pullback on inputs, while a readout is
transported by precomposition with the inverse chart.
-/

namespace UEOT.V3.RepresentationCovariance

open MeasureTheory ProbabilityTheory

universe uX uX' uM

variable {X : Type uX} {X' : Type uX'} {M : Type uM}
variable [MeasurableSpace X] [MeasurableSpace X'] [MeasurableSpace M]

noncomputable def transportKernel
    (P : Kernel X X) (T : X ≃ᵐ X') : Kernel X' X' :=
  Kernel.comap (Kernel.map P T) T.symm T.symm.measurable

def transportReadout
    (f : X → M) (T : X ≃ᵐ X') : X' → M :=
  f ∘ T.symm

theorem transportReadout_apply
    (f : X → M) (T : X ≃ᵐ X') (x : X) :
    transportReadout f T (T x) = f x := by
  simp [transportReadout]

theorem measurable_transportReadout
    (f : X → M) (hf : Measurable f) (T : X ≃ᵐ X') :
    Measurable (transportReadout f T) :=
  hf.comp T.symm.measurable

theorem transportKernel_apply
    (P : Kernel X X) (T : X ≃ᵐ X') (x : X) :
    transportKernel P T (T x) = (P x).map T := by
  unfold transportKernel
  rw [Kernel.comap_apply, Kernel.map_apply _ T.measurable]
  simp

theorem transportKernel_apply_symm
    (P : Kernel X X) (T : X ≃ᵐ X') (x' : X') :
    transportKernel P T x' = (P (T.symm x')).map T := by
  simpa using transportKernel_apply P T (T.symm x')

/-- Exact one-step kernel/readout covariance: transported dynamics followed by
the transported readout has the same pushed macro law as the original
dynamics followed by the original readout. -/
theorem transported_readout_pushforward
    (P : Kernel X X) (f : X → M) (hf : Measurable f)
    (T : X ≃ᵐ X') (x : X) :
    ((transportKernel P T) (T x)).map (transportReadout f T) =
      (P x).map f := by
  rw [transportKernel_apply]
  rw [Measure.map_map
    (measurable_transportReadout f hf T)
    T.measurable]
  congr 1
  funext y
  simp [transportReadout]


/-- Strong lumpability is invariant under a bimeasurable reparameterization of
the microscopic state space.  This is the dynamic-closure covariance clause
of P-FAC-01 at the exact one-step-kernel level. -/
theorem strongLumpability_transport_iff
    (P : Kernel X X) (Pbar : Kernel M M)
    (f : X → M) (hf : Measurable f) (T : X ≃ᵐ X') :
    UEOT.V3.DynamicsKernel.StrongLumpability P Pbar f hf ↔
      UEOT.V3.DynamicsKernel.StrongLumpability
        (transportKernel P T) Pbar
        (transportReadout f T)
        (measurable_transportReadout f hf T) := by
  rw [UEOT.V3.DynamicsKernel.strongLumpability_iff_apply,
      UEOT.V3.DynamicsKernel.strongLumpability_iff_apply]
  constructor
  · intro h x'
    rw [transportKernel_apply_symm]
    rw [Measure.map_map
      (measurable_transportReadout f hf T)
      T.measurable]
    have hcomp : transportReadout f T ∘ T = f := by
      funext x
      simp [transportReadout]
    rw [hcomp]
    simpa [transportReadout] using h (T.symm x')
  · intro h x
    have hx := h (T x)
    rw [transported_readout_pushforward P f hf T x] at hx
    simpa [transportReadout] using hx


/-- A bimeasurable microscopic reparameterization is itself an exact
strong-lumpability map from the original kernel to the transported kernel. -/
theorem transportKernel_strongLumpability
    (P : Kernel X X) (T : X ≃ᵐ X') :
    UEOT.V3.DynamicsKernel.StrongLumpability
      P (transportKernel P T) T T.measurable := by
  rw [UEOT.V3.DynamicsKernel.strongLumpability_iff_apply]
  intro x
  exact (transportKernel_apply P T x).symm

/-- Markovity is preserved by the bimeasurable transport. -/
instance isMarkovKernel_transportKernel
    (P : Kernel X X) [IsMarkovKernel P] (T : X ≃ᵐ X') :
    IsMarkovKernel (transportKernel P T) := by
  constructor
  intro x'
  rw [transportKernel_apply_symm]
  letI : IsProbabilityMeasure (P (T.symm x')) := by infer_instance
  exact Measure.isProbabilityMeasure_map T.measurable.aemeasurable

/-- Full path-law covariance under a bimeasurable microscopic coordinate
change.  This is the trajectory-law clause of P-FAC-01: pushing the original
microscopic trajectory coordinatewise through `T` gives exactly the
trajectory generated by the transported kernel from the transported initial
law. -/
theorem homTrajMeasure_transport_covariance
    (μ : Measure X) [IsProbabilityMeasure μ]
    (P : Kernel X X) [IsMarkovKernel P]
    (T : X ≃ᵐ X') :
    (UEOT.V3.DynamicsKernel.homTrajMeasure μ P).map
        (UEOT.V3.DynamicsKernel.mapPath T) =
      UEOT.V3.DynamicsKernel.homTrajMeasure
        (μ.map T) (transportKernel P T) := by
  letI : IsMarkovKernel (transportKernel P T) :=
    isMarkovKernel_transportKernel P T
  exact UEOT.V3.DynamicsKernel.homTrajMeasure_path_naturality
    μ P (transportKernel P T) T T.measurable
    (transportKernel_strongLumpability P T)


/-- Transport a response kernel only in its microscopic input coordinate; its
future/response space is unchanged. -/
noncomputable def transportResponse
    {Y : Type*} [MeasurableSpace Y]
    (Q : Kernel X Y) (T : X ≃ᵐ X') : Kernel X' Y :=
  Kernel.comap Q T.symm T.symm.measurable

@[simp] theorem transportResponse_apply
    {Y : Type*} [MeasurableSpace Y]
    (Q : Kernel X Y) (T : X ≃ᵐ X') (x' : X') :
    transportResponse Q T x' = Q (T.symm x') := by
  rfl

/-- Predictive factorization/sufficiency is invariant under a bimeasurable
microscopic coordinate change.  The theorem is protocol-dependent: every
protocol may have its own future space `Y e`, matching the dependent-future
form of the UEOT predictive layer. -/
theorem predictive_family_factorization_transport_iff
    {E : Type*} {Y : E → Type*}
    [∀ e, MeasurableSpace (Y e)]
    (Q : ∀ e, Kernel X (Y e))
    (Qbar : ∀ e, Kernel M (Y e))
    (f : X → M) (T : X ≃ᵐ X') :
    (∀ e x, Q e x = Qbar e (f x)) ↔
      ∀ e x',
        transportResponse (Q e) T x' =
          Qbar e (transportReadout f T x') := by
  constructor
  · intro h e x'
    simp only [transportResponse_apply, transportReadout]
    exact h e (T.symm x')
  · intro h e x
    have hx := h e (T x)
    simpa [transportReadout] using hx


/-! ## Reward and control-value covariance -/

/-- Coordinatewise path transport is itself a bimeasurable equivalence. -/
def pathMeasurableEquiv
    (T : X ≃ᵐ X') : (ℕ → X) ≃ᵐ (ℕ → X') where
  toEquiv :=
    { toFun := UEOT.V3.DynamicsKernel.mapPath T
      invFun := UEOT.V3.DynamicsKernel.mapPath T.symm
      left_inv := by
        intro x
        funext n
        simp [UEOT.V3.DynamicsKernel.mapPath]
      right_inv := by
        intro x
        funext n
        simp [UEOT.V3.DynamicsKernel.mapPath] }
  measurable_toFun :=
    UEOT.V3.DynamicsKernel.measurable_mapPath T T.measurable
  measurable_invFun :=
    UEOT.V3.DynamicsKernel.measurable_mapPath T.symm T.symm.measurable

@[simp] theorem pathMeasurableEquiv_apply
    (T : X ≃ᵐ X') (x : ℕ → X) :
    pathMeasurableEquiv T x =
      UEOT.V3.DynamicsKernel.mapPath T x := rfl

@[simp] theorem pathMeasurableEquiv_symm_apply
    (T : X ≃ᵐ X') (x' : ℕ → X') :
    (pathMeasurableEquiv T).symm x' =
      UEOT.V3.DynamicsKernel.mapPath T.symm x' := rfl

/-- Transporting both a path law and its reward functional through a
bimeasurable reparameterization preserves expected reward exactly. -/
theorem expectedPathReward_transport
    (μ : Measure (ℕ → X))
    (T : X ≃ᵐ X')
    (reward : (ℕ → X) → ℝ) :
    (∫ x', reward ((pathMeasurableEquiv T).symm x')
        ∂(μ.map (pathMeasurableEquiv T))) =
      ∫ x, reward x ∂μ := by
  calc
    (∫ x', reward ((pathMeasurableEquiv T).symm x')
        ∂(μ.map (pathMeasurableEquiv T))) =
      ∫ x, reward ((pathMeasurableEquiv T).symm
        ((pathMeasurableEquiv T) x)) ∂μ :=
      MeasureTheory.integral_map_equiv
        (μ := μ) (pathMeasurableEquiv T)
        (fun x' => reward ((pathMeasurableEquiv T).symm x'))
    _ = ∫ x, reward x ∂μ := by
      apply MeasureTheory.integral_congr_ae
      filter_upwards with x
      apply congrArg reward
      funext n
      simp [pathMeasurableEquiv, UEOT.V3.DynamicsKernel.mapPath]

/-- Source-facing trajectory reward covariance for the Markov path laws already
transported above. -/
theorem homTraj_expectedReward_transport
    (μ : Measure X) [IsProbabilityMeasure μ]
    (P : Kernel X X) [IsMarkovKernel P]
    (T : X ≃ᵐ X')
    (reward : (ℕ → X) → ℝ) :
    (∫ x',
        reward ((pathMeasurableEquiv T).symm x')
        ∂UEOT.V3.DynamicsKernel.homTrajMeasure
          (μ.map T) (transportKernel P T)) =
      ∫ x, reward x
        ∂UEOT.V3.DynamicsKernel.homTrajMeasure μ P := by
  letI : IsMarkovKernel (transportKernel P T) :=
    isMarkovKernel_transportKernel P T
  rw [← homTrajMeasure_transport_covariance μ P T]
  exact expectedPathReward_transport
    (UEOT.V3.DynamicsKernel.homTrajMeasure μ P) T reward

/-- Expected value of one policy/path-law pair. -/
noncomputable def policyExpectedValue
    {Pol Ω : Type*} [MeasurableSpace Ω]
    (law : Pol → Measure Ω) (reward : Ω → ℝ) (π : Pol) : ℝ :=
  ∫ ω, reward ω ∂law π

/-- Total optimal value over an arbitrary policy family.  `EReal` avoids
adding boundedness/nonemptiness assumptions that are absent from the covariance
statement. -/
noncomputable def optimalExpectedValue
    {Pol Ω : Type*} [MeasurableSpace Ω]
    (law : Pol → Measure Ω) (reward : Ω → ℝ) : EReal :=
  ⨆ π, (policyExpectedValue law reward π : EReal)

/-- If corresponding policies have exactly transported path laws and the
reward is transported by the inverse coordinate map, every policy value is
identical. -/
theorem policyExpectedValue_transport
    {Pol Ω Ω' : Type*}
    [MeasurableSpace Ω] [MeasurableSpace Ω']
    (law : Pol → Measure Ω) (law' : Pol → Measure Ω')
    (T : Ω ≃ᵐ Ω') (reward : Ω → ℝ)
    (hlaw : ∀ π, law' π = (law π).map T) :
    ∀ π,
      policyExpectedValue law' (reward ∘ T.symm) π =
        policyExpectedValue law reward π := by
  intro π
  unfold policyExpectedValue
  rw [hlaw π]
  simpa [Function.comp_def] using
    (MeasureTheory.integral_map_equiv
      (μ := law π) T (reward ∘ T.symm))

/-- Taking the supremum over the same transported policy family preserves the
optimal control value. -/
theorem optimalExpectedValue_transport
    {Pol Ω Ω' : Type*}
    [MeasurableSpace Ω] [MeasurableSpace Ω']
    (law : Pol → Measure Ω) (law' : Pol → Measure Ω')
    (T : Ω ≃ᵐ Ω') (reward : Ω → ℝ)
    (hlaw : ∀ π, law' π = (law π).map T) :
    optimalExpectedValue law' (reward ∘ T.symm) =
      optimalExpectedValue law reward := by
  have hfun :
      (fun π => (policyExpectedValue law' (reward ∘ T.symm) π : EReal)) =
        fun π => (policyExpectedValue law reward π : EReal) := by
    funext π
    exact congrArg (fun x : ℝ => (x : EReal))
      (policyExpectedValue_transport law law' T reward hlaw π)
  unfold optimalExpectedValue
  rw [hfun]


/-! ## Action-indexed / source-facing control wrappers -/

universe uA uE uPol uΩ uΩ'

/-- Exact dynamic closure is covariant simultaneously for every action in a
controlled kernel family.  The action coordinate itself is not reparameterized;
only the microscopic state chart changes. -/
theorem controlledStrongLumpability_transport_iff
    {A : Type uA}
    (P : A → Kernel X X) (Pbar : A → Kernel M M)
    (f : X → M) (hf : Measurable f) (T : X ≃ᵐ X') :
    (∀ a, UEOT.V3.DynamicsKernel.StrongLumpability (P a) (Pbar a) f hf) ↔
      ∀ a,
        UEOT.V3.DynamicsKernel.StrongLumpability
          (transportKernel (P a) T) (Pbar a)
          (transportReadout f T)
          (measurable_transportReadout f hf T) := by
  constructor
  · intro h a
    exact (strongLumpability_transport_iff (P a) (Pbar a) f hf T).1 (h a)
  · intro h a
    exact (strongLumpability_transport_iff (P a) (Pbar a) f hf T).2 (h a)

/-- For each fixed action kernel, the whole homogeneous microscopic path law
is transported exactly.  This is the action-indexed form of the already proved
trajectory covariance theorem. -/
theorem controlledHomTrajMeasure_transport
    {A : Type uA}
    (P : A → Kernel X X)
    (hP : ∀ a, IsMarkovKernel (P a))
    (T : X ≃ᵐ X')
    (a : A) (μ : Measure X) (hμ : IsProbabilityMeasure μ) :
    (UEOT.V3.DynamicsKernel.homTrajMeasure μ (P a)).map
        (UEOT.V3.DynamicsKernel.mapPath T) =
      UEOT.V3.DynamicsKernel.homTrajMeasure
        (μ.map T) (transportKernel (P a) T) := by
  letI : IsMarkovKernel (P a) := hP a
  letI : IsProbabilityMeasure μ := hμ
  exact homTrajMeasure_transport_covariance μ (P a) T

/-- The reward/value clause of P-FAC-01 once a policy-indexed path-law family
has been transported through a bimeasurable path equivalence.  The first
component is pointwise policy-value equality and the second is optimal-value
equality over the same policy family. -/
theorem controlValue_transport_bundle
    {Pol : Type uPol} {Ω : Type uΩ} {Ω' : Type uΩ'}
    [MeasurableSpace Ω] [MeasurableSpace Ω']
    (law : Pol → Measure Ω) (law' : Pol → Measure Ω')
    (T : Ω ≃ᵐ Ω') (reward : Ω → ℝ)
    (hlaw : ∀ π, law' π = (law π).map T) :
    (∀ π,
      policyExpectedValue law' (reward ∘ T.symm) π =
        policyExpectedValue law reward π) ∧
      optimalExpectedValue law' (reward ∘ T.symm) =
        optimalExpectedValue law reward := by
  exact ⟨policyExpectedValue_transport law law' T reward hlaw,
    optimalExpectedValue_transport law law' T reward hlaw⟩

/-- Bundle of the currently machine-checked P-FAC-01 covariance interfaces:
action-indexed exact dynamic closure, protocol-dependent predictive
factorization, and control-value covariance once the transported policy path
laws are supplied.  Full feedback-policy path-law transport remains a separate
source-audit item rather than being hidden in this wrapper. -/
theorem p_fac_01_covariance_bundle
    {A : Type uA} {E : Type uE} {Y : E → Type*}
    [∀ e, MeasurableSpace (Y e)]
    (P : A → Kernel X X) (Pbar : A → Kernel M M)
    (Q : ∀ e, Kernel X (Y e))
    (Qbar : ∀ e, Kernel M (Y e))
    (f : X → M) (hf : Measurable f) (T : X ≃ᵐ X') :
    ((∀ a, UEOT.V3.DynamicsKernel.StrongLumpability (P a) (Pbar a) f hf) ↔
      ∀ a,
        UEOT.V3.DynamicsKernel.StrongLumpability
          (transportKernel (P a) T) (Pbar a)
          (transportReadout f T)
          (measurable_transportReadout f hf T)) ∧
    ((∀ e x, Q e x = Qbar e (f x)) ↔
      ∀ e x',
        transportResponse (Q e) T x' =
          Qbar e (transportReadout f T x')) := by
  exact ⟨controlledStrongLumpability_transport_iff P Pbar f hf T,
    predictive_family_factorization_transport_iff Q Qbar f T⟩

/-! ## Finite causal path-law transport

This is the induction layer needed to remove the external path-law equality
assumption from the control-value part of P-FAC-01. -/

universe uHist

open UEOT.V3.PathError

/-- Coordinatewise equivalence between recursively nested finite causal
histories. -/
def causalHistoryEquiv
    {H₀ H₀' Z Z' : Type uHist}
    (e₀ : H₀ ≃ H₀') (eZ : Z ≃ Z') :
    ∀ n, CausalHistory H₀ Z n ≃ CausalHistory H₀' Z' n
  | 0 => e₀
  | n + 1 => (causalHistoryEquiv e₀ eZ n).prodCongr eZ

@[simp] theorem causalHistoryEquiv_zero
    {H₀ H₀' Z Z' : Type uHist}
    (e₀ : H₀ ≃ H₀') (eZ : Z ≃ Z') :
    causalHistoryEquiv e₀ eZ 0 = e₀ := rfl

@[simp] theorem causalHistoryEquiv_succ_apply
    {H₀ H₀' Z Z' : Type uHist}
    (e₀ : H₀ ≃ H₀') (eZ : Z ≃ Z')
    (n : ℕ) (h : CausalHistory H₀ Z (n + 1)) :
    causalHistoryEquiv e₀ eZ (n + 1) h =
      (causalHistoryEquiv e₀ eZ n h.1, eZ h.2) := rfl

/-- One causal-extension step commutes with bijective coordinate transport. -/
theorem pmfExtend_map_equiv
    {H H' Z Z' : Type uHist}
    [Fintype H] [Fintype H'] [Fintype Z] [Fintype Z']
    (p : PMF H) (K : H → PMF Z)
    (eH : H ≃ H') (eZ : Z ≃ Z') :
    (pmfExtend p K).map (eH.prodCongr eZ) =
      pmfExtend (p.map eH)
        (fun h' => (K (eH.symm h')).map eZ) := by
  unfold pmfExtend
  rw [PMF.map_bind, PMF.bind_map]
  congr 1
  funext h
  simp only [Function.comp_apply, Equiv.symm_apply_apply]
  rw [PMF.map_comp, PMF.map_comp]
  apply congrArg (fun q : Z → H' × Z' => (K h).map q)
  funext z
  rfl

/-- Exact finite-horizon path-law naturality. -/
theorem causalLaw_transport_equiv
    {H₀ H₀' Z Z' : Type uHist}
    [Fintype H₀] [Fintype H₀'] [Fintype Z] [Fintype Z']
    (p₀ : PMF H₀)
    (K : ∀ n, CausalHistory H₀ Z n → PMF Z)
    (K' : ∀ n, CausalHistory H₀' Z' n → PMF Z')
    (e₀ : H₀ ≃ H₀') (eZ : Z ≃ Z')
    (hK : ∀ n h,
      K' n (causalHistoryEquiv e₀ eZ n h) = (K n h).map eZ) :
    ∀ n,
      (causalLaw p₀ K n).map (causalHistoryEquiv e₀ eZ n) =
        causalLaw (p₀.map e₀) K' n := by
  intro n
  induction n with
  | zero =>
      rfl
  | succ n ih =>
      change
        (pmfExtend (causalLaw p₀ K n) (K n)).map
            ((causalHistoryEquiv e₀ eZ n).prodCongr eZ) =
          pmfExtend (causalLaw (p₀.map e₀) K' n) (K' n)
      rw [pmfExtend_map_equiv]
      rw [ih]
      congr
      funext h'
      have hh := hK n ((causalHistoryEquiv e₀ eZ n).symm h')
      simpa using hh.symm

end UEOT.V3.RepresentationCovariance
