import UEOT.V3.ViabilityKernel
import UEOT.V3.ViabilityPath
import UEOT.V3.DynamicsKernel
import Mathlib.Probability.Kernel.Basic

/-!
# P-PER-03 trajectory realization

The finite viability recursion yields a deterministic stationary preserving
policy.  This module realizes such a policy as a genuine Markov kernel and
then uses the repository's Ionescu--Tulcea-backed `homTrajMeasure` to obtain an
infinite path law on `ℕ → X`.  Subsequent source-facing lemmas can therefore
state probability-one nonexit on an actual trajectory measure, rather than on
an informal sequence of marginals.
-/

namespace UEOT.V3.ViabilityTrajectory

open MeasureTheory ProbabilityTheory
open UEOT.V3.ViabilityKernel
open UEOT.V3.DynamicsKernel

universe uX uA

variable {X : Type uX} {A : Type uA}
variable [Fintype X] [Fintype A]
variable [MeasurableSpace X] [MeasurableSingletonClass X]

/-- The homogeneous Markov kernel induced by a deterministic stationary
policy. -/
noncomputable def stationaryKernel
    (P : X → A → PMF X) (π : X → A) : Kernel X X :=
  Kernel.ofFunOfCountable fun x => (P x (π x)).toMeasure

@[simp] theorem stationaryKernel_apply
    (P : X → A → PMF X) (π : X → A) (x : X) :
    stationaryKernel P π x = (P x (π x)).toMeasure := rfl

instance stationaryKernel_isMarkov
    (P : X → A → PMF X) (π : X → A) :
    IsMarkovKernel (stationaryKernel P π) where
  isProbabilityMeasure x := by
    rw [stationaryKernel_apply]
    infer_instance

/-- Genuine infinite path law generated by the stationary policy. -/
noncomputable def stationaryTrajMeasure
    (P : X → A → PMF X) (π : X → A) (μ : PMF X) :
    Measure (ℕ → X) :=
  homTrajMeasure μ.toMeasure (stationaryKernel P π)

instance stationaryTrajMeasure_isProbability
    (P : X → A → PMF X) (π : X → A) (μ : PMF X) :
    IsProbabilityMeasure (stationaryTrajMeasure P π μ) := by
  unfold stationaryTrajMeasure
  infer_instance

/-- The path-level probability-one nonexit bridge can now be applied directly
to the stationary trajectory measure once coordinate safety has been derived
from the viability recursion. -/
theorem all_times_safe_of_coordinate_null
    (P : X → A → PMF X) (π : X → A) (μ : PMF X)
    (K : Set X)
    (hbad : ∀ n : ℕ,
      stationaryTrajMeasure P π μ
        {ω | ω n ∉ K} = 0) :
    stationaryTrajMeasure P π μ {ω | ∀ n : ℕ, ω n ∈ K} = 1 := by
  exact UEOT.V3.ViabilityPath.all_times_safe_of_each_time_bad_null
    (μ := stationaryTrajMeasure P π μ) K hbad

end UEOT.V3.ViabilityTrajectory
