import UEOT.V3.ViabilityKernel
import UEOT.V3.ViabilityPath
import UEOT.V3.DynamicsKernel
import Mathlib.Probability.Kernel.Basic
import Mathlib.Probability.ProbabilityMassFunction.Monad

/-!
# P-PER-03 trajectory realization

The finite viability recursion yields a deterministic stationary preserving
policy.  This module realizes such a policy as a genuine Markov kernel and
then uses the repository's Ionescu--Tulcea-backed `homTrajMeasure` to obtain an
infinite path law on `ℕ → X`.  The PMF recursion and the measure/kernel
recursion are connected explicitly, so path-level persistence is derived from
the same stationary dynamics rather than from a parallel informal model.
-/

namespace UEOT.V3.ViabilityTrajectory

open MeasureTheory ProbabilityTheory
open UEOT.V3.ViabilityKernel
open UEOT.V3.DynamicsKernel

universe uX uA

variable {X : Type uX} {A : Type uA}
variable [Fintype X] [Fintype A]
variable [MeasurableSpace X] [MeasurableSingletonClass X]

/-- The homogeneous Markov kernel induced by a deterministic stationary
policy. -/
noncomputable def stationaryKernel
    (P : X → A → PMF X) (π : X → A) : Kernel X X :=
  Kernel.ofFunOfCountable fun x => (P x (π x)).toMeasure

@[simp] theorem stationaryKernel_apply
    (P : X → A → PMF X) (π : X → A) (x : X) :
    stationaryKernel P π x = (P x (π x)).toMeasure := rfl

instance stationaryKernel_isMarkov
    (P : X → A → PMF X) (π : X → A) :
    IsMarkovKernel (stationaryKernel P π) where
  isProbabilityMeasure x := by
    rw [stationaryKernel_apply]
    infer_instance

/-- The PMF stationary recursion is exactly the measure/kernel composition
recursion induced by `stationaryKernel`.  This is the semantic bridge needed
to identify finite viability marginals with the marginals of the genuine path
measure. -/
theorem stationaryStateLaw_succ_toMeasure
    (P : X → A → PMF X) (π : X → A) (μ : PMF X) (n : ℕ) :
    (stationaryStateLaw P π μ (n + 1)).toMeasure =
      stationaryKernel P π ∘ₘ
        (stationaryStateLaw P π μ n).toMeasure := by
  ext s hs
  rw [stationaryStateLaw_succ, PMF.toMeasure_bind_apply]
  rw [Measure.bind_apply hs (Kernel.aemeasurable _)]
  rw [lintegral_countable']
  apply tsum_congr
  intro x
  rw [stationaryKernel_apply]
  rw [PMF.toMeasure_apply_singleton _ _ (MeasurableSet.singleton x)]
  rw [mul_comm]

/-- Genuine infinite path law generated by the stationary policy. -/
noncomputable def stationaryTrajMeasure
    (P : X → A → PMF X) (π : X → A) (μ : PMF X) :
    Measure (ℕ → X) :=
  homTrajMeasure μ.toMeasure (stationaryKernel P π)

instance stationaryTrajMeasure_isProbability
    (P : X → A → PMF X) (π : X → A) (μ : PMF X) :
    IsProbabilityMeasure (stationaryTrajMeasure P π μ) := by
  unfold stationaryTrajMeasure
  infer_instance

/-- Once every coordinate marginal is safe with probability one, the genuine
stationary path law never exits the viability set at any discrete time with
probability one. -/
theorem all_times_safe_of_coordinate_one
    (P : X → A → PMF X) (π : X → A) (μ : PMF X)
    (K : Set X)
    (hone : ∀ n : ℕ,
      stationaryTrajMeasure P π μ {ω | ω n ∈ K} = 1) :
    stationaryTrajMeasure P π μ {ω | ∀ n : ℕ, ω n ∈ K} = 1 := by
  exact UEOT.V3.ViabilityPath.all_times_safe_eq_one
    (μ := stationaryTrajMeasure P π μ)
    (Xn := fun n ω => ω n)
    K (Set.toFinite K).measurableSet
    (fun n => measurable_pi_apply n) hone

end UEOT.V3.ViabilityTrajectory
