import UEOT.V3.Compression.Objecthood.JointHomeostasis.LongRunHomeostasis
import UEOT.V3.Compression.Objecthood.RepairLawSelfReconstruction.IdentifiabilityBoundary
import UEOT.V3.Compression.Objecthood.Homeostasis.CertifiedHomeostaticMargin
import UEOT.V3.Compression.Objecthood.Homeostasis.HomeostasisSemantics
import Mathlib.Tactic

namespace UEOT.V3.Compression.Objecthood.JointHomeostasis

open Set Filter MeasureTheory ProbabilityTheory
open UEOT.V3.ViabilityKernel
open UEOT.V3.Compression.Objecthood
open UEOT.V3.Compression.Objecthood.RepairLawSelfReconstruction
open scoped ENNReal

universe uX uA uP uR uO
noncomputable section

/-- A fault row with one positive-mass successor whose physical coordinate has
left the certified same-program repair basin cannot satisfy P5's quantitative
finite joint fault envelope.  This is the exact carrier-support boundary of the
positive theorem. -/
theorem no_finiteJointFaultEnvelope_of_physical_escape
    {X : Type uX} {A : Type uA}
    {Program : Type uP} {Representation : Type uR}
    [Fintype X] [Fintype A]
    [MeasurableSpace X] [MeasurableSingletonClass X]
    (P : X → A → PMF X) (K : Set X)
    (R : PhysicalRepairCertificate P K)
    (T : TrustedRepairSubstrate Program X A)
    (codec : TrustedRepairCodec Program Representation)
    (r : Program)
    (F : RepairOrganizationState X A Representation →
      PMF (RepairOrganizationState X A Representation))
    {s w : RepairOrganizationState X A Representation}
    (hs : s ∈ finiteJointRepairCarrier P K R T codec r)
    (hw : w ∈ (F s).support)
    (hescape :
      w.physical ∉ StationaryRepairBasin P K (T.execute r)) :
    ¬ FiniteJointFaultEnvelope P K R T codec r F := by
  intro E
  have hwcarrier := E.fault_stays_finite_carrier s hs hw
  exact hescape hwcarrier.1.1

/-- Likewise, any positive-mass program corruption that no longer decodes to
the intended program lies outside the P5 positive envelope.  P5 therefore does
not claim recovery from arbitrary/uncorrectable program corruption. -/
theorem no_finiteJointFaultEnvelope_of_decode_change
    {X : Type uX} {A : Type uA}
    {Program : Type uP} {Representation : Type uR}
    [Fintype X] [Fintype A]
    [MeasurableSpace X] [MeasurableSingletonClass X]
    (P : X → A → PMF X) (K : Set X)
    (R : PhysicalRepairCertificate P K)
    (T : TrustedRepairSubstrate Program X A)
    (codec : TrustedRepairCodec Program Representation)
    (r : Program)
    (F : RepairOrganizationState X A Representation →
      PMF (RepairOrganizationState X A Representation))
    {s w : RepairOrganizationState X A Representation}
    (hs : s ∈ finiteJointRepairCarrier P K R T codec r)
    (hw : w ∈ (F s).support)
    (hdecode : codec.decode w.repairProgram ≠ r) :
    ¬ FiniteJointFaultEnvelope P K R T codec r F := by
  intro E
  have hwcarrier := E.fault_stays_finite_carrier s hs hw
  exact hdecode hwcarrier.1.2

/-- The deeper information-theoretic boundary remains RLSR's: if two
behaviorally distinct repair programs collapse to the same corrupted
observation, no deterministic observation-only reconstructor can be exact on
both.  P5 does not weaken this identifiability requirement. -/
theorem programObservationCollision_blocks_exactReconstruction
    {X : Type uX} {A : Type uA}
    {Program : Type uP} {Obs : Type uO}
    (T : TrustedRepairSubstrate Program X A) (K : Set X)
    (observe : Program → Obs)
    {r1 r2 : Program}
    (hdist : ¬ RepairProgramEquivalentOn T K r1 r2)
    (hobs : observe r1 = observe r2) :
    ¬ ∃ reconstruct : Obs → Program,
        ExactBehavioralReconstructor T K observe reconstruct :=
  no_exact_behavioral_reconstruction_of_observation_collision
    T K observe hdist hobs

/-- A finite system that is always legitimate even though faults occur with
hazard one.  It witnesses that positive certified load margin is sufficient
for RH quantitative bounds, not necessary for the abstract semantic property
of mean homeostasis. -/
noncomputable def alwaysLegitimateHazardOneSystem :
    RecurrentHomeostasisSystem Bool where
  legitimate := Set.univ
  carrier := Set.univ
  repairKernel := fun _ => PMF.pure true
  faultKernel := fun _ => PMF.pure true
  faultHazard := 1
  faultHazard_le_one := le_rfl
  potential := fun _ => 0
  repairDrift := 1
  repairDrift_ne_zero := by norm_num
  repairDrift_ne_top := by simp
  legitimate_subset_carrier := Set.Subset.rfl
  repair_stays_carrier := by
    intro z hz w hw
    trivial
  fault_stays_carrier := by
    intro z hz w hw
    trivial

noncomputable def alwaysLegitimateHazardOneBurden :
    FaultBurdenCertificate alwaysLegitimateHazardOneSystem where
  burden := 0
  burden_ne_top := by simp
  fault_expectation_bound := by
    intro z hz
    simp [alwaysLegitimateHazardOneSystem]

/-- Actual damaged mass generated by the all-legitimate witness. -/
noncomputable def alwaysLegitimateHazardOneDamage
    (mu0 : PMF Bool) (n : ℕ) : ℝ :=
  ((homeostaticMarginal alwaysLegitimateHazardOneSystem.mixedKernel mu0 n).toMeasure
    alwaysLegitimateHazardOneSystem.legitimateᶜ).toReal

@[simp] theorem alwaysLegitimateHazardOneDamage_eq_zero
    (mu0 : PMF Bool) (n : ℕ) :
    alwaysLegitimateHazardOneDamage mu0 n = 0 := by
  simp [alwaysLegitimateHazardOneDamage, alwaysLegitimateHazardOneSystem]

/-- The actual damaged probability of the all-legitimate witness is identically
zero, so it satisfies mean homeostasis at level zero. -/
theorem alwaysLegitimateHazardOne_meanHomeostasis (mu0 : PMF Bool) :
    MeanHomeostasis (alwaysLegitimateHazardOneDamage mu0) 0 := by
  intro eta heta
  filter_upwards [] with n
  simp [meanDamageAverage]
  exact le_of_lt heta

/-- **Positive margin is not a universal phase-transition iff.**

For one concrete recurrent-homeostasis system the canonical hazard is one, so
no positive load margin exists, while the semantic damaged occupation is still
identically zero because every state is legitimate. -/
theorem meanHomeostasis_without_positive_loadMargin (mu0 : PMF Bool) :
    (¬ 0 < homeostaticMarginReal
      alwaysLegitimateHazardOneSystem.faultHazard
      alwaysLegitimateHazardOneSystem.repairDrift
      alwaysLegitimateHazardOneBurden.burden) ∧
    MeanHomeostasis (alwaysLegitimateHazardOneDamage mu0) 0 := by
  constructor
  · simpa [alwaysLegitimateHazardOneSystem] using
      no_positive_margin_of_hazard_one
        alwaysLegitimateHazardOneSystem.repairDrift
        alwaysLegitimateHazardOneBurden.burden
  · exact alwaysLegitimateHazardOne_meanHomeostasis mu0

/-- P5 inherits RH's pathwise boundary unchanged: bounded/controlled mean
occupation does not imply that almost every trajectory revisits legitimacy
arbitrarily late. -/
theorem meanHomeostasis_not_enough_for_pathwiseRecurrent :
    MeanHomeostasis
        (damagedProbFromLaw twoClassPathMeasure ({true} : Set Bool))
        (1 / 2 : ℝ) ∧
      ¬ PathwiseRecurrentLegitimacy
        twoClassPathMeasure ({true} : Set Bool) :=
  meanHomeostasis_does_not_imply_pathwiseRecurrent

end
end UEOT.V3.Compression.Objecthood.JointHomeostasis
