import UEOT.V3.Compression.Objecthood.JointHomeostasis.RepairCarrier
import UEOT.V3.Compression.Objecthood.RepairLawSelfReconstruction.RepairThenPreserve
import UEOT.V3.Compression.Objecthood.AutonomousSelfStabilization

namespace UEOT.V3.Compression.Objecthood.JointHomeostasis

open Set MeasureTheory ProbabilityTheory
open UEOT.V3.ViabilityKernel
open UEOT.V3.Compression.Objecthood
open UEOT.V3.Compression.Objecthood.RepairLawSelfReconstruction
open scoped ENNReal

universe uX uA uP uR
noncomputable section

/-- Whether the mutable controller/program coordinates are exactly the canonical
organization generated by `r` at the state's current physical coordinate. -/
def CanonicalProgramOrganization
    {X : Type uX} {A : Type uA}
    {Program : Type uP} {Representation : Type uR}
    (T : TrustedRepairSubstrate Program X A)
    (codec : TrustedRepairCodec Program Representation)
    (r : Program)
    (s : RepairOrganizationState X A Representation) : Prop :=
  s = canonicalRepairOrganizationState T codec r s.physical

/-- One existing physical-repair drift unit pays for any remaining mutable
program/controller organization mismatch. -/
noncomputable def organizationMismatchPenalty
    {X : Type uX} {A : Type uA}
    {Program : Type uP} {Representation : Type uR}
    (T : TrustedRepairSubstrate Program X A)
    (codec : TrustedRepairCodec Program Representation)
    (r : Program) (drift : ENNReal)
    (s : RepairOrganizationState X A Representation) : ENNReal := by
  classical
  exact if CanonicalProgramOrganization T codec r s then 0 else drift

/-- Minimal P5 joint potential: reuse the complete O5 physical/controller
potential and add only one repair-program/canonical-organization penalty. -/
noncomputable def jointRepairPotential
    {X : Type uX} {A : Type uA}
    {Program : Type uP} {Representation : Type uR}
    [Fintype X] [Fintype A]
    [MeasurableSpace X] [MeasurableSingletonClass X]
    (P : X → A → PMF X) (K : Set X)
    (R : PhysicalRepairCertificate P K)
    (T : TrustedRepairSubstrate Program X A)
    (codec : TrustedRepairCodec Program Representation)
    (r : Program)
    (s : RepairOrganizationState X A Representation) : ENNReal :=
  autonomousRepairPotential P K R (s.physical, s.controller) +
    organizationMismatchPenalty T codec r R.drift s

@[simp] theorem organizationMismatchPenalty_canonical
    {X : Type uX} {A : Type uA}
    {Program : Type uP} {Representation : Type uR}
    (T : TrustedRepairSubstrate Program X A)
    (codec : TrustedRepairCodec Program Representation)
    (r : Program) (drift : ENNReal) (x : X) :
    organizationMismatchPenalty T codec r drift
      (canonicalRepairOrganizationState T codec r x) = 0 := by
  classical
  simp [organizationMismatchPenalty, CanonicalProgramOrganization,
    canonicalRepairOrganizationState]

/-- Canonical organization never has more O5 potential than the standard
physical potential plus one controller-repair unit. -/
theorem jointRepairPotential_canonical_le
    {X : Type uX} {A : Type uA}
    {Program : Type uP} {Representation : Type uR}
    [Fintype X] [Fintype A]
    [MeasurableSpace X] [MeasurableSingletonClass X]
    (P : X → A → PMF X) (K : Set X)
    (R : PhysicalRepairCertificate P K)
    (T : TrustedRepairSubstrate Program X A)
    (codec : TrustedRepairCodec Program Representation)
    (r : Program) (x : X) :
    jointRepairPotential P K R T codec r
        (canonicalRepairOrganizationState T codec r x) ≤
      R.potential x + R.drift := by
  rw [jointRepairPotential, organizationMismatchPenalty_canonical]
  simp only [add_zero, canonicalRepairOrganizationState]
  exact autonomousRepairPotential_le_W_add_d P K R (x, T.execute r)

/-- A canonical valid-program state in the physical target has zero joint
potential. -/
theorem jointRepairPotential_canonical_eq_zero_of_mem_target
    {X : Type uX} {A : Type uA}
    {Program : Type uP} {Representation : Type uR}
    [Fintype X] [Fintype A]
    [MeasurableSpace X] [MeasurableSingletonClass X]
    (P : X → A → PMF X) (K : Set X)
    (R : PhysicalRepairCertificate P K)
    (T : TrustedRepairSubstrate Program X A)
    (codec : TrustedRepairCodec Program Representation)
    (r : Program)
    (hvalid : RepairProgramValid T P K r)
    {x : X} (hx : x ∈ K) :
    jointRepairPotential P K R T codec r
      (canonicalRepairOrganizationState T codec r x) = 0 := by
  rw [jointRepairPotential, organizationMismatchPenalty_canonical]
  have hzero : autonomousRepairPotential P K R (x, T.execute r) = 0 :=
    autonomousRepairPotential_eq_zero_of_legitimate P K R ⟨hx, hvalid⟩
  simp [canonicalRepairOrganizationState, hzero]

/-- **P5.2 joint repair drift.**

On the decode-correct joint repair carrier, one RLSR safe step inherits the
original positive P-REC drift toward exact same-program joint legitimacy.  The
only new energy term is the canonical-organization mismatch penalty; physical
and controller repair are reused from O5. -/
theorem safeRepairKernel_jointRepairPotential_drift
    {X : Type uX} {A : Type uA}
    {Program : Type uP} {Representation : Type uR}
    [Fintype X] [Fintype A] [Nonempty A] [Fintype Representation]
    [MeasurableSpace X] [MeasurableSingletonClass X]
    [MeasurableSpace (RepairOrganizationState X A Representation)]
    [MeasurableSingletonClass (RepairOrganizationState X A Representation)]
    (P : X → A → PMF X) (K : Set X)
    (hfix : viabilityStep P K = K)
    (R : PhysicalRepairCertificate P K)
    (T : TrustedRepairSubstrate Program X A)
    (codec : TrustedRepairCodec Program Representation)
    (r : Program)
    (himpl : RepairProgramDynamicsImplementsPolicy T P r
      (repairThenPreservePolicy P K hfix R.repairPolicy))
    {s : RepairOrganizationState X A Representation}
    (hs : s ∈ jointRepairCarrier T codec P K r)
    (hnotLeg : s ∉ jointLegitimate T codec K r) :
    (∫⁻ w, jointRepairPotential P K R T codec r w
      ∂(safeRepairKernel T codec P s).toMeasure) + R.drift ≤
      jointRepairPotential P K R T codec r s := by
  classical
  let _ : Fintype (RepairOrganizationState X A Representation) :=
    repairOrganizationStateFintype
  have hvalid : RepairProgramValid T P K r :=
    repairProgramValid_of_dynamicsImplements_repairThenPreserve
      T P K hfix R.repairPolicy r himpl
  rcases hs with ⟨hxB, hdecode⟩
  rw [safeRepairKernel_eq_of_decode_eq T codec P r s hdecode]
  let f : X → RepairOrganizationState X A Representation :=
    canonicalRepairOrganizationState T codec r
  have hf : Measurable f := measurable_of_finite f
  have hInt : Measurable (jointRepairPotential P K R T codec r) :=
    measurable_of_finite _
  have hm :
      (P s.physical (T.execute r s.physical)).toMeasure.map f =
        ((P s.physical (T.execute r s.physical)).map f).toMeasure :=
    PMF.toMeasure_map f (P s.physical (T.execute r s.physical)) hf
  rw [← hm, lintegral_map hInt hf]
  by_cases hxK : s.physical ∈ K
  · have hcanon : ¬ CanonicalProgramOrganization T codec r s := by
      intro hc
      apply hnotLeg
      exact ⟨s.physical, hxK, hc⟩
    have hExp0 :
        (∫⁻ y, jointRepairPotential P K R T codec r (f y)
          ∂(P s.physical (T.execute r s.physical)).toMeasure) = 0 := by
      rw [lintegral_fintype]
      apply Finset.sum_eq_zero
      intro y hyuniv
      rw [PMF.toMeasure_apply_singleton _ _ (MeasurableSet.singleton y)]
      by_cases hy0 : P s.physical (T.execute r s.physical) y = 0
      · simp [hy0]
      · have hys : y ∈ (P s.physical (T.execute r s.physical)).support :=
          (PMF.mem_support_iff _ _).2 hy0
        have hyK : y ∈ K := hvalid s.physical hxK hys
        have hpot0 := jointRepairPotential_canonical_eq_zero_of_mem_target
          P K R T codec r hvalid hyK
        simp [f, hpot0]
    rw [hExp0, zero_add]
    unfold jointRepairPotential organizationMismatchPenalty
    simp [hcanon]
  · have hkernel :
        P s.physical (T.execute r s.physical) =
          P s.physical (R.repairPolicy s.physical) := by
      rw [himpl s.physical]
      simp [repairThenPreservePolicy, hxK]
    have hExpLe :
        (∫⁻ y, jointRepairPotential P K R T codec r (f y)
          ∂(P s.physical (T.execute r s.physical)).toMeasure) ≤
        (∫⁻ y, R.potential y + R.drift
          ∂(P s.physical (R.repairPolicy s.physical)).toMeasure) := by
      rw [hkernel]
      apply lintegral_mono
      intro y
      exact jointRepairPotential_canonical_le P K R T codec r y
    have hsplit :
        (∫⁻ y, R.potential y + R.drift
          ∂(P s.physical (R.repairPolicy s.physical)).toMeasure) =
        (∫⁻ y, R.potential y
          ∂(P s.physical (R.repairPolicy s.physical)).toMeasure) + R.drift := by
      rw [lintegral_add_right R.potential measurable_const]
      simp
    rw [hsplit] at hExpLe
    have hphys := R.drift_condition s.physical hxK
    have htoPot :
        (∫⁻ y, jointRepairPotential P K R T codec r (f y)
          ∂(P s.physical (T.execute r s.physical)).toMeasure) ≤
        R.potential s.physical := hExpLe.trans hphys
    calc
      (∫⁻ y, jointRepairPotential P K R T codec r (f y)
          ∂(P s.physical (T.execute r s.physical)).toMeasure) + R.drift
          ≤ R.potential s.physical + R.drift :=
            add_le_add htoPot (le_refl R.drift)
      _ = autonomousRepairPotential P K R (s.physical, s.controller) := by
        simp [autonomousRepairPotential, hxK]
      _ ≤ jointRepairPotential P K R T codec r s := by
        simp [jointRepairPotential]

end
end UEOT.V3.Compression.Objecthood.JointHomeostasis
