import UEOT.V3.Compression.Objecthood.ResourceClosure.StateCostEnvelope

/-!
# Theory Completion P6.2 — asymptotic mean resource closure

P5 controls Cesaro damaged occupation, so the strongest direct P6 consequence
is a Cesaro/mean resource statement.  This module keeps that level explicit:
actual expected state costs are first bounded by the P6.1 damage envelope, then
averaged.  A strict steady-load margin makes the averaged actual expected cost
eventually smaller than replenishment.

No pathwise stock conclusion is inferred here.
-/

namespace UEOT.V3.Compression.Objecthood.ResourceClosure

open Set Filter Topology MeasureTheory ProbabilityTheory
open UEOT.V3.ViabilityKernel
open UEOT.V3.Compression.Objecthood
open UEOT.V3.Compression.Objecthood.JointHomeostasis
open UEOT.V3.Compression.Objecthood.RepairLawSelfReconstruction
open scoped ENNReal BigOperators

universe uX uA uP uR
noncomputable section

/-- Cesaro average of a real-valued schedule. -/
noncomputable def meanRealSchedule (f : ℕ → ℝ) (n : ℕ) : ℝ :=
  (((n + 1 : ℕ) : ℝ)⁻¹) * ∑ t ∈ Finset.range (n + 1), f t

/-- Pointwise schedule domination passes to Cesaro averages. -/
theorem meanRealSchedule_mono
    {f g : ℕ → ℝ}
    (hfg : ∀ n, f n ≤ g n) (n : ℕ) :
    meanRealSchedule f n ≤ meanRealSchedule g n := by
  unfold meanRealSchedule
  gcongr with t ht
  exact hfg t

/-- Minimal expected-cost envelope generated by damaged probability. -/
def ResourceCostModel.expectedCostEnvelope
    (C : ResourceCostModel) (damage : ℕ → ℝ) (n : ℕ) : ℝ :=
  C.maintenance + C.variableCost * damage n

/-- Cesaro mean of the expected-cost envelope. -/
noncomputable def ResourceCostModel.meanExpectedCostEnvelope
    (C : ResourceCostModel) (damage : ℕ → ℝ) (n : ℕ) : ℝ :=
  meanRealSchedule (C.expectedCostEnvelope damage) n

/-- The mean envelope is exactly maintenance plus variable cost times mean
damage. -/
theorem ResourceCostModel.meanExpectedCostEnvelope_eq
    (C : ResourceCostModel) (damage : ℕ → ℝ) (n : ℕ) :
    C.meanExpectedCostEnvelope damage n =
      C.maintenance + C.variableCost * meanDamageAverage damage n := by
  unfold ResourceCostModel.meanExpectedCostEnvelope
    ResourceCostModel.expectedCostEnvelope meanRealSchedule meanDamageAverage
  rw [Finset.sum_add_distrib]
  simp only [Finset.sum_const, Finset.card_range, nsmul_eq_mul]
  rw [← Finset.mul_sum]
  have hn : ((n + 1 : ℕ) : ℝ) ≠ 0 := by positivity
  let N : ℝ := ((n + 1 : ℕ) : ℝ)
  change N⁻¹ * (N * C.maintenance +
      C.variableCost * ∑ t ∈ Finset.range (n + 1), damage t) =
    C.maintenance + C.variableCost *
      (N⁻¹ * ∑ t ∈ Finset.range (n + 1), damage t)
  have hN : N ≠ 0 := by simpa [N] using hn
  field_simp [hN]

/-- Mean homeostasis yields the corresponding mean cost-envelope bound. -/
theorem ResourceCostModel.eventually_meanExpectedCostEnvelope_le
    (C : ResourceCostModel) (damage : ℕ → ℝ) (rho : ℝ)
    (hhomeo : MeanHomeostasis damage rho) :
    ∀ eta > 0, ∀ᶠ n in atTop,
      C.meanExpectedCostEnvelope damage n ≤
        C.maintenance + C.variableCost * (rho + eta) := by
  intro eta heta
  filter_upwards [hhomeo eta heta] with n hn
  rw [C.meanExpectedCostEnvelope_eq]
  gcongr
  exact C.variableCost_nonneg

/-- A strict steady resource-load margin makes the mean envelope eventually
strictly cheaper than constant replenishment. -/
theorem ResourceCostModel.eventually_meanExpectedCostEnvelope_lt_supply
    (C : ResourceCostModel) (damage : ℕ → ℝ) (rho supply : ℝ)
    (hhomeo : MeanHomeostasis damage rho)
    (hmargin : C.maintenance + C.variableCost * rho < supply) :
    ∀ᶠ n in atTop, C.meanExpectedCostEnvelope damage n < supply := by
  by_cases hv0 : C.variableCost = 0
  · filter_upwards [] with n
    rw [C.meanExpectedCostEnvelope_eq]
    simpa [hv0] using hmargin
  · have hvpos : 0 < C.variableCost :=
      lt_of_le_of_ne C.variableCost_nonneg (Ne.symm hv0)
    let delta : ℝ := supply -
      (C.maintenance + C.variableCost * rho)
    have hdelta : 0 < delta := by
      dsimp [delta]
      linarith
    let eta : ℝ := delta / (2 * C.variableCost)
    have heta : 0 < eta := by
      dsimp [eta]
      positivity
    have htarget :
        C.maintenance + C.variableCost * (rho + eta) < supply := by
      dsimp [eta, delta]
      field_simp
      nlinarith
    filter_upwards
      [C.eventually_meanExpectedCostEnvelope_le damage rho hhomeo eta heta]
      with n hn
    exact hn.trans_lt htarget

/-- If actual expected costs are pointwise below the P6 envelope, strict mean
load slack makes the Cesaro average of actual expected costs eventually smaller
than supply. -/
theorem ResourceCostModel.eventually_meanActualCost_lt_supply
    (C : ResourceCostModel)
    (actual damage : ℕ → ℝ) (rho supply : ℝ)
    (hactual : ∀ n, actual n ≤ C.expectedCostEnvelope damage n)
    (hhomeo : MeanHomeostasis damage rho)
    (hmargin : C.maintenance + C.variableCost * rho < supply) :
    ∀ᶠ n in atTop, meanRealSchedule actual n < supply := by
  have henv := C.eventually_meanExpectedCostEnvelope_lt_supply
    damage rho supply hhomeo hmargin
  filter_upwards [henv] with n hn
  exact (meanRealSchedule_mono hactual n).trans_lt hn

/-- Concrete P5→P6 asymptotic bridge.  The actual expected accounting cost of
P5 marginals is computed from the state-level cost adapter, not defined to be
the damage envelope. -/
theorem finiteJoint_eventually_meanActualResourceCost_lt_supply
    {X : Type uX} {A : Type uA}
    {Program : Type uP} {Representation : Type uR}
    [Fintype X] [Fintype A] [Nonempty A] [Fintype Representation]
    [MeasurableSpace X] [MeasurableSingletonClass X]
    (P : X → A → PMF X) (K : Set X)
    (hfix : viabilityStep P K = K)
    (R : PhysicalRepairCertificate P K)
    (T : TrustedRepairSubstrate Program X A)
    (codec : TrustedRepairCodec Program Representation)
    (r : Program)
    (himpl : RepairProgramDynamicsImplementsPolicy T P r
      (repairThenPreservePolicy P K hfix R.repairPolicy))
    (F : RepairOrganizationState X A Representation →
      PMF (RepairOrganizationState X A Representation))
    (epsilon : NNReal) (hepsilon : epsilon ≤ 1)
    (hF : FiniteJointFaultEnvelope P K R T codec r F)
    (mu0 : PMF (RepairOrganizationState X A Representation))
    (hmu0 : StaysIn mu0 (finiteJointRepairCarrier P K R T codec r))
    (hhazard : epsilon < 1)
    (C : ResourceCostModel) (supply : ℝ)
    (hmargin :
      let S := finiteJointRecurrentHomeostasisSystem
        P K hfix R T codec r himpl F epsilon hepsilon hF
      let rho :=
        ((epsilon : ENNReal) * canonicalFaultBurden S).toReal /
          (((1 - epsilon : NNReal) : ENNReal) * S.repairDrift).toReal
      C.maintenance + C.variableCost * rho < supply) :
    let S := finiteJointRecurrentHomeostasisSystem
      P K hfix R T codec r himpl F epsilon hepsilon hF
    let actual : ℕ → ℝ := fun n =>
      pmfRealExpectation (homeostaticMarginal S.mixedKernel mu0 n)
        (stateResourceCost C
          (fun s => s ∈ jointLegitimate T codec K r)
          (jointProgramMismatch T codec r))
    ∀ᶠ n in atTop, meanRealSchedule actual n < supply := by
  dsimp only
  let S := finiteJointRecurrentHomeostasisSystem
    P K hfix R T codec r himpl F epsilon hepsilon hF
  let D : ℕ → ENNReal := fun n =>
    (homeostaticMarginal S.mixedKernel mu0 n).toMeasure S.legitimateᶜ
  let damage : ℕ → ℝ := fun n => (D n).toReal
  let actual : ℕ → ℝ := fun n =>
    pmfRealExpectation (homeostaticMarginal S.mixedKernel mu0 n)
      (stateResourceCost C
        (fun s => s ∈ jointLegitimate T codec K r)
        (jointProgramMismatch T codec r))
  let rho : ℝ :=
    ((epsilon : ENNReal) * canonicalFaultBurden S).toReal /
      (((1 - epsilon : NNReal) : ENNReal) * S.repairDrift).toReal
  have hactual : ∀ n, actual n ≤ C.expectedCostEnvelope damage n := by
    intro n
    change pmfRealExpectation (homeostaticMarginal S.mixedKernel mu0 n)
        (stateResourceCost C
          (fun s => s ∈ jointLegitimate T codec K r)
          (jointProgramMismatch T codec r)) ≤
      C.maintenance + C.variableCost * (D n).toReal
    have h := p5_pmfRealExpectation_stateResourceCost_le
      C T codec K r (homeostaticMarginal S.mixedKernel mu0 n)
    change pmfRealExpectation (homeostaticMarginal S.mixedKernel mu0 n)
        (stateResourceCost C
          (fun s => s ∈ jointLegitimate T codec K r)
          (jointProgramMismatch T codec r)) ≤
      C.maintenance + C.variableCost * (D n).toReal at h
    exact h
  have hhomeo : MeanHomeostasis damage rho := by
    simpa [S, D, damage, rho] using
      finiteJoint_meanHomeostasis
        P K hfix R T codec r himpl F epsilon hepsilon hF
        mu0 hmu0 hhazard
  exact C.eventually_meanActualCost_lt_supply
    actual damage rho supply hactual hhomeo (by
      simpa [S, rho] using hmargin)

end
end UEOT.V3.Compression.Objecthood.ResourceClosure
