import UEOT.V3.Compression.CrossTrack.DualIsolationCanonical
import UEOT.V3.TVKernel

/-!
# Dual Isolation — P-MET-01 realization bridge

Parent Binding originally exposes a forward row-TV Lipschitz constant `L`.
P-MET-01 can derive the sharp nonexpansive value `L = 1` when parent rows are
generated by applying one common Markov channel (for each parent state) to an
assembly-level probability law, provided the assembly metric dominates the TV
distance of those laws.

The crucial guard is the realization identity.  No claim is made that an
arbitrary parent kernel admits such a factorization.
-/

namespace UEOT.V3.Compression.CrossTrack

open MeasureTheory ProbabilityTheory
open scoped ProbabilityTheory
open UEOT.V3
open UEOT.V3.FiniteDobrushin
open UEOT.V3.Compression.InvariantSetGaugeInvariance
open UEOT.V3.Compression.TopologyChangingGoaL1ResidualConorm

universe uP uC uA uX uY uS

noncomputable section

variable {P : Type uP} {C : Type uC}
variable {A : Type uA}
variable {X : Type uX} [MeasurableSpace X]
variable {S : Type uS} [Fintype S] [Nonempty S]
noncomputable local instance dualIsolationPMetDecidableEq : DecidableEq S :=
  Classical.decEq S
local instance dualIsolationPMetMeasurableSpace : MeasurableSpace S := ⊤

/-- **P-MET parent-realization mechanism.**

Each assembly realization `a` carries a probability law `baseLaw a`.  For each
finite parent state `x`, one common Markov channel `channel x` maps that law to
the actual row law of every parent completion.  The assembly metric is required
to dominate the base-law TV distance.

This certificate contains only a realization factorization and metric
comparison.  It contains no invariant law or long-run semantic conclusion. -/
structure CommonMarkovParentRealization
    (X : Type uX) [MeasurableSpace X]
    [PseudoMetricSpace A]
    (repr : P → A)
    (K : P → Matrix S S ℝ)
    (hK : ∀ p, K p ∈ Matrix.rowStochastic ℝ S) where
  baseLaw : A → Measure X
  base_probability : ∀ a, IsProbabilityMeasure (baseLaw a)
  metric_tv_le : ∀ a b,
    UEOT.V3.TotalVariation.tvDist (baseLaw a) (baseLaw b) ≤ dist a b
  channel : S → Kernel X S
  channel_markov : ∀ x, IsMarkovKernel (channel x)
  row_realization : ∀ p x,
    (rowPMF (K p) (hK p) x).toMeasure =
      (channel x) ∘ₘ (baseLaw (repr p))

/-- P-MET-01 data processing makes every realized parent row nonexpansive with
respect to the assembly metric. -/
theorem CommonMarkovParentRealization.rowTV_le_assemblyDist
    [PseudoMetricSpace A]
    (repr : P → A)
    (K : P → Matrix S S ℝ)
    (hK : ∀ p, K p ∈ Matrix.rowStochastic ℝ S)
    (real : CommonMarkovParentRealization X repr K hK)
    (p q : P) (x : S) :
    crossRowTV (K p) (hK p) (K q) (hK q) x ≤
      dist (repr p) (repr q) := by
  let _ : IsProbabilityMeasure (real.baseLaw (repr p)) :=
    real.base_probability (repr p)
  let _ : IsProbabilityMeasure (real.baseLaw (repr q)) :=
    real.base_probability (repr q)
  let _ : IsMarkovKernel (real.channel x) := real.channel_markov x
  unfold crossRowTV UEOT.V3.FiniteDiscountedControl.FiniteProbabilityRow.tvDist
  rw [real.row_realization p x, real.row_realization q x]
  exact
    (UEOT.V3.TVKernel.tvDist_comp_le
      (real.baseLaw (repr p)) (real.baseLaw (repr q)) (real.channel x)).trans
      (real.metric_tv_le (repr p) (repr q))

/-- A common-Markov realization automatically supplies Parent Binding with the
sharp data-processing constant `L = 1`. -/
noncomputable def CommonMarkovParentRealization.toParentBinding
    [PseudoMetricSpace A]
    (repr : P → A)
    (K : P → Matrix S S ℝ)
    (hK : ∀ p, K p ∈ Matrix.rowStochastic ℝ S)
    (real : CommonMarkovParentRealization X repr K hK) :
    ParentBindingLipschitz repr K hK where
  L := 1
  L_nonneg := by norm_num
  row_lipschitz := by
    intro p q x
    simpa using real.rowTV_le_assemblyDist repr K hK p q x

@[simp] theorem CommonMarkovParentRealization.toParentBinding_L
    [PseudoMetricSpace A]
    (repr : P → A)
    (K : P → Matrix S S ℝ)
    (hK : ∀ p, K p ∈ Matrix.rowStochastic ℝ S)
    (real : CommonMarkovParentRealization X repr K hK) :
    (real.toParentBinding repr K hK).L = 1 := rfl

/-- **P-MET-01 pairwise dual-isolation theorem.**

The common-channel realization removes the supplied forward Lipschitz factor
from the pairwise semantic bound: P-MET-01 certifies that factor as one. -/
theorem dualIsolation_commonMarkov_pairwiseSemanticBound
    [MetricSpace A]
    {Y : Type uY} [PseudoMetricSpace Y]
    (repr : P → A)
    (diagnostic : A → Y)
    (beta eta : ℝ)
    (hiso : BindingIsolation diagnostic beta)
    (heta : 0 ≤ eta)
    (observed : Y)
    (K : P → Matrix S S ℝ)
    (hK : ∀ p, K p ∈ Matrix.rowStochastic ℝ S)
    (real : CommonMarkovParentRealization X repr K hK)
    (mu : P → stdSimplex ℝ S)
    (hmu : ∀ p, mu p ∈ invariantLawSet (K p) (hK p))
    (kappaMin : ℝ)
    (hkappaMin : 0 < kappaMin)
    (hcard : 1 < Fintype.card S)
    {p q : P}
    (hpObs : dist (diagnostic (repr p)) observed ≤ eta)
    (hqObs : dist (diagnostic (repr q)) observed ≤ eta)
    (hpIso : kappaMin ≤ l1ResidualConorm (K p)) :
    lawTV (mu p) (mu q) ≤
      (2 * eta / beta) / kappaMin := by
  have h := dualIsolation_pairwiseSemanticBound
    repr diagnostic beta eta hiso heta observed K hK
    (real.toParentBinding repr K hK) mu hmu
    kappaMin hkappaMin hcard hpObs hqObs hpIso
  simpa using h

/-- **P-MET-01 dual-isolation theorem, supplied-beta form.**

Once the parent realization factors through common Markov channels, the
forward constant disappears from the bound: `L = 1` is derived rather than
assumed. -/
theorem dualIsolation_commonMarkov_fiberSemanticDiameter
    [MetricSpace A]
    {Y : Type uY} [PseudoMetricSpace Y]
    (pi : P → C)
    (repr : P → A)
    (diagnostic : A → Y)
    (beta eta : ℝ)
    (hiso : BindingIsolation diagnostic beta)
    (heta : 0 ≤ eta)
    (observed : Y)
    (K : P → Matrix S S ℝ)
    (hK : ∀ p, K p ∈ Matrix.rowStochastic ℝ S)
    (real : CommonMarkovParentRealization X repr K hK)
    (mu : P → stdSimplex ℝ S)
    (hmu : ∀ p, mu p ∈ invariantLawSet (K p) (hK p))
    (c : C)
    (hfiberNonempty : ∃ p, pi p = c)
    (kappaMin : ℝ)
    (hkappaMin : 0 < kappaMin)
    (hcard : 1 < Fintype.card S)
    (hobs : ∀ p, pi p = c →
      dist (diagnostic (repr p)) observed ≤ eta)
    (hisolationFloor : ∀ p, pi p = c →
      kappaMin ≤ l1ResidualConorm (K p)) :
    fiberSemanticDiameter pi mu c ≤
      (2 * eta) / (beta * kappaMin) := by
  have h := dualIsolation_fiberSemanticDiameter_normalized
    pi repr diagnostic beta eta hiso heta observed K hK
    (real.toParentBinding repr K hK) mu hmu c hfiberNonempty
    kappaMin hkappaMin hcard hobs hisolationFloor
  simpa using h

/-- **Canonical P-MET-01 dual-isolation theorem.**

For finite assembly spaces with an injective diagnostic and common-Markov
parent realization, the complete bound depends only on the two inverse
isolation margins.  The forward factor is certified by data processing. -/
theorem canonicalDualIsolation_commonMarkov_fiberSemanticDiameter
    {Y : Type uY} [MetricSpace Y]
    [Fintype A] [Nontrivial A] [MetricSpace A]
    (pi : P → C)
    (repr : P → A)
    (diagnostic : A → Y)
    (hdiagInjective : Function.Injective diagnostic)
    (eta : ℝ) (heta : 0 ≤ eta)
    (observed : Y)
    (K : P → Matrix S S ℝ)
    (hK : ∀ p, K p ∈ Matrix.rowStochastic ℝ S)
    (real : CommonMarkovParentRealization X repr K hK)
    (mu : P → stdSimplex ℝ S)
    (hmu : ∀ p, mu p ∈ invariantLawSet (K p) (hK p))
    (c : C)
    (hfiberNonempty : ∃ p, pi p = c)
    (kappaMin : ℝ)
    (hkappaMin : 0 < kappaMin)
    (hcard : 1 < Fintype.card S)
    (hobs : ∀ p, pi p = c →
      dist (diagnostic (repr p)) observed ≤ eta)
    (hisolationFloor : ∀ p, pi p = c →
      kappaMin ≤ l1ResidualConorm (K p)) :
    fiberSemanticDiameter pi mu c ≤
      (2 * eta) /
        (bindingIsolationConorm diagnostic * kappaMin) := by
  have h := canonicalDualIsolation_fiberSemanticDiameter
    pi repr diagnostic hdiagInjective eta heta observed K hK
    (real.toParentBinding repr K hK) mu hmu c hfiberNonempty
    kappaMin hkappaMin hcard hobs hisolationFloor
  simpa using h

end

end UEOT.V3.Compression.CrossTrack
