import UEOT.V3.CoreOperationalAssembly
import UEOT.V3.CompositionCarrierLift
import UEOT.V3.Compression.CrossTrack.InteractionBindingIsolation
import Mathlib.InformationTheory.Hamming

/-!
# Endogenous candidate formation from lower-level response structure

Track H proved that child/coarse data do not in general identify one unique
richer parent.  The correct constructive target is therefore not a universal
single-parent decoder, but a canonically generated *finite candidate family*.

This module composes existing source-certified interfaces:

* the exact response-defect carrier family from `CoreOperationalAssembly`;
* P-COMP-06, which lifts physical minimal carriers to minimal child coalitions;
* the statistical carrier-recovery theorem, which transfers response-table
  recovery to the generated coalition family;
* the interaction-identifiability layer, now instantiated on those generated
  coalition candidates rather than on an arbitrary assembly type.

No uniqueness claim is introduced: multiple minimal coalitions may remain.
-/

namespace UEOT.V3.Compression.CrossTrack

open MeasureTheory
open UEOT.V3
open UEOT.V3.CoreOperationalAssembly
open UEOT.V3.CompositionCarrierLift

universe uV uChild uH uProbe uR uY uE uZ

noncomputable section

variable {V : Type uV} {Child : Type uChild}
variable {H : Type uH} {Probe : Type uProbe}
variable {Rout : Type uR} {Y : Type uY}
variable [MeasurableSpace Y]

/-- Candidate parent assemblies generated from lower-level response structure:
first recover exact physical minimal carriers from the response law, then take
the minimal child coalitions sufficient to cover at least one such carrier. -/
def responseFormedCandidateFamily
    (readout : Finset V → H → Rout)
    (p : H → Probe → Measure Y)
    (regions : Child → Finset V) : Set (Finset Child) :=
  childMinimalFamily regions (exactCarrierFamily readout p)

/-- Empirical/threshold analogue of `responseFormedCandidateFamily`. -/
def estimatedResponseFormedCandidateFamily
    (readout : Finset V → H → Rout)
    (pHat : H → Probe → Measure Y) (tau : ℝ)
    (regions : Child → Finset V) : Set (Finset Child) :=
  childMinimalFamily regions (estimatedCarrierFamily readout pHat tau)

/-- P-COMP-06 gives an exact two-stage construction of the response-formed
candidate family through per-physical-carrier minimal covers followed by the
outer minimalization. -/
theorem responseFormedCandidateFamily_eq_lifted
    [Fintype Child]
    (readout : Finset V → H → Rout)
    (p : H → Probe → Measure Y)
    (regions : Child → Finset V) :
    responseFormedCandidateFamily readout p regions =
      liftedMinimalCoverFamily regions (exactCarrierFamily readout p) := by
  exact p_comp_06 regions (exactCarrierFamily readout p)

/-- One concrete zero-defect physical carrier seed already guarantees that the
exact minimal-carrier family is nonempty: finite minimalization extracts an
inclusion-minimal zero-defect subcarrier. -/
theorem exactCarrierFamily_nonempty_of_zeroDefectSeed
    (readout : Finset V → H → Rout)
    (p : H → Probe → Measure Y)
    (S0 : Finset V)
    (hzero : UEOT.V3.StatisticalDefect.responseDefect readout p S0 = 0) :
    (exactCarrierFamily readout p).Nonempty := by
  obtain ⟨M, _hMS, hmin⟩ :=
    UEOT.Finite.exists_minimal_subset
      (fun T => UEOT.V3.StatisticalDefect.responseDefect readout p T = 0)
      S0 hzero
  exact ⟨M, hmin⟩

/-- A still more primitive candidate-formation existence theorem.  It needs
only one zero-defect physical seed and coverage of that seed by the declared
children.  Minimal physical and child-coalition structure is then generated by
finite minimization rather than supplied as input. -/
theorem responseFormedCandidateFamily_nonempty_of_zeroDefectSeed
    [Fintype Child]
    (readout : Finset V → H → Rout)
    (p : H → Probe → Measure Y)
    (regions : Child → Finset V)
    (S0 : Finset V)
    (hzero : UEOT.V3.StatisticalDefect.responseDefect readout p S0 = 0)
    (hcoverSeed : coalitionCovers regions S0 Finset.univ) :
    (responseFormedCandidateFamily readout p regions).Nonempty := by
  obtain ⟨M, hMS, hmin⟩ :=
    UEOT.Finite.exists_minimal_subset
      (fun T => UEOT.V3.StatisticalDefect.responseDefect readout p T = 0)
      S0 hzero
  have hM : M ∈ exactCarrierFamily readout p := hmin
  have hcoverM : coalitionCovers regions M Finset.univ := by
    intro v hv
    exact hcoverSeed v (hMS hv)
  have hsuff :
      childSufficient regions (exactCarrierFamily readout p) Finset.univ :=
    ⟨M, hM, hcoverM⟩
  obtain ⟨S, _hSub, hChildMin⟩ :=
    UEOT.Finite.exists_minimal_subset
      (childSufficient regions (exactCarrierFamily readout p))
      Finset.univ hsuff
  exact ⟨S, hChildMin⟩

/-- Candidate formation is nonempty once at least one exact physical carrier
exists and every exact physical carrier is coverable by the declared child
regions.  No parent candidate is postulated separately. -/
theorem responseFormedCandidateFamily_nonempty
    [Fintype Child]
    (readout : Finset V → H → Rout)
    (p : H → Probe → Measure Y)
    (regions : Child → Finset V)
    (hphysical : (exactCarrierFamily readout p).Nonempty)
    (hcover : ∀ M ∈ exactCarrierFamily readout p,
      coalitionCovers regions M Finset.univ) :
    (responseFormedCandidateFamily readout p regions).Nonempty := by
  rcases hphysical with ⟨M, hM⟩
  have hsuff :
      childSufficient regions (exactCarrierFamily readout p) Finset.univ :=
    ⟨M, hM, hcover M hM⟩
  obtain ⟨S, _hSub, hMin⟩ :=
    UEOT.Finite.exists_minimal_subset
      (childSufficient regions (exactCarrierFamily readout p))
      Finset.univ hsuff
  exact ⟨S, hMin⟩

/-- Exact carrier-family recovery immediately recovers the generated candidate
family; there is no second independent matching assumption at the coalition
level. -/
theorem estimatedResponseFormedCandidateFamily_eq_true
    (readout : Finset V → H → Rout)
    (p pHat : H → Probe → Measure Y)
    (regions : Child → Finset V)
    (tau : ℝ)
    (hcarrier :
      estimatedCarrierFamily readout pHat tau = exactCarrierFamily readout p) :
    estimatedResponseFormedCandidateFamily readout pHat tau regions =
      responseFormedCandidateFamily readout p regions := by
  unfold estimatedResponseFormedCandidateFamily responseFormedCandidateFamily
  rw [hcarrier]

/-- **Response-level formation recovery.**

The same simultaneous response event already used by the frozen statistical
core recovers the exact physical carrier family.  Pushing that equality
through P-COMP-06's child-coalition construction recovers the parent-candidate
family generated from the children. -/
theorem responseFormedCandidateFamily_recovery_on_good_event
    [Fintype V] [DecidableEq V]
    [Fintype H] [Nonempty H]
    [Fintype Probe] [Nonempty Probe]
    (readout : Finset V → H → Rout)
    (p pHat : H → Probe → Measure Y)
    (hp : ∀ h i, IsProbabilityMeasure (p h i))
    (hpHat : ∀ h i, IsProbabilityMeasure (pHat h i))
    (regions : Child → Finset V)
    (eta gamma Delta tau : ℝ)
    (hresp : ∀ h i,
      UEOT.V3.TotalVariation.tvDist (p h i) (pHat h i) ≤ eta)
    (hsep : ∀ h h',
      ¬UEOT.V3.PredictiveClassRecovery.trueEquivalent p h h' →
        gamma ≤ UEOT.V3.PredictiveClassRecovery.protocolDistance p h h')
    (hpredGap : 2 * eta < gamma / 2)
    (hcarrierGap : ∀ S,
      0 < UEOT.V3.StatisticalDefect.responseDefect readout p S →
        Delta ≤ UEOT.V3.StatisticalDefect.responseDefect readout p S)
    (hlower : 2 * eta < tau)
    (hupper : tau < Delta - 2 * eta) :
    estimatedResponseFormedCandidateFamily readout pHat tau regions =
      responseFormedCandidateFamily readout p regions := by
  have hrec := response_recovery_on_good_event
    readout p pHat hp hpHat eta gamma Delta tau
    hresp hsep hpredGap hcarrierGap hlower hupper
  exact estimatedResponseFormedCandidateFamily_eq_true
    readout p pHat regions tau hrec.2.1

/-! ## Generated candidates as the input to interaction identifiability -/

/-- A formed parent candidate is not an arbitrary assembly token: it is a child
coalition belonging to the response-generated minimal candidate family. -/
abbrev FormedCandidate
    (readout : Finset V → H → Rout)
    (p : H → Probe → Measure Y)
    (regions : Child → Finset V) :=
  {S : Finset Child // S ∈ responseFormedCandidateFamily readout p regions}

noncomputable instance formedCandidateFintype
    [Fintype Child]
    (readout : Finset V → H → Rout)
    (p : H → Probe → Measure Y)
    (regions : Child → Finset V) :
    Fintype (FormedCandidate readout p regions) :=
  Fintype.ofFinite _

/-- The canonical metric used on generated coalition candidates is the Hamming
metric on child-membership signatures.  Thus one unit of assembly distance is
one changed child-membership bit, rather than an arbitrary enumeration metric. -/
noncomputable instance formedCandidateHammingMetric
    [Fintype Child]
    (readout : Finset V → H → Rout)
    (p : H → Probe → Measure Y)
    (regions : Child → Finset V) :
    MetricSpace (FormedCandidate readout p regions) := by
  classical
  exact MetricSpace.induced
    (fun S : FormedCandidate readout p regions =>
      Hamming.toHamming (fun i : Child => decide (i ∈ S.1)))
    (by
      intro S T h
      apply Subtype.ext
      apply Finset.ext
      intro i
      have hi := congrArg
        (fun q : Hamming (fun _ : Child => Bool) => Hamming.ofHamming q i) h
      simpa using hi)
    inferInstance

theorem formedCandidate_nonempty
    [Fintype Child]
    (readout : Finset V → H → Rout)
    (p : H → Probe → Measure Y)
    (regions : Child → Finset V)
    (hphysical : (exactCarrierFamily readout p).Nonempty)
    (hcover : ∀ M ∈ exactCarrierFamily readout p,
      coalitionCovers regions M Finset.univ) :
    Nonempty (FormedCandidate readout p regions) := by
  rcases responseFormedCandidateFamily_nonempty
      readout p regions hphysical hcover with ⟨S, hS⟩
  exact ⟨⟨S, hS⟩⟩

theorem formedCandidate_nontrivial_of_two
    [Fintype Child]
    (readout : Finset V → H → Rout)
    (p : H → Probe → Measure Y)
    (regions : Child → Finset V)
    {S T : Finset Child}
    (hS : S ∈ responseFormedCandidateFamily readout p regions)
    (hT : T ∈ responseFormedCandidateFamily readout p regions)
    (hne : S ≠ T) :
    Nontrivial (FormedCandidate readout p regions) := by
  exact ⟨⟨⟨S, hS⟩, ⟨T, hT⟩, by simpa using hne⟩⟩

variable {E : Type uE} {Z : Type uZ} [MeasurableSpace Z]

/-- Restrict an interaction-response law on child coalitions to the generated
candidate subtype. -/
noncomputable def formedCandidateResponseFamily
    (readout : Finset V → H → Rout)
    (p : H → Probe → Measure Y)
    (regions : Child → Finset V)
    (response : Finset Child → E → Measure Z)
    (hprob : ∀ S e, IsProbabilityMeasure (response S e)) :
    InteractionResponseFamily (FormedCandidate readout p regions) E Z where
  response := fun S e => response S.1 e
  probability := fun S e => hprob S.1 e

/-- **Formation -> identification bridge.**

Once at least two generated coalition candidates remain, the previously proved
interaction-isolation equivalence applies directly to those formed candidates,
using coalition Hamming distance.  The candidate type is no longer supplied as
an unrelated external assembly space. -/
theorem formedCandidate_interactionIsolation_pos_iff
    [Fintype Child]
    (readout : Finset V → H → Rout)
    (p : H → Probe → Measure Y)
    (regions : Child → Finset V)
    (response : Finset Child → E → Measure Z)
    (hprob : ∀ S e, IsProbabilityMeasure (response S e))
    [Nontrivial (FormedCandidate readout p regions)]
    (probes : Finset E) (hprobes : probes.Nonempty) :
    0 < interactionIsolationConorm
        (formedCandidateResponseFamily readout p regions response hprob)
        probes hprobes ↔
      PairwiseInteractionSeparating
        (formedCandidateResponseFamily readout p regions response hprob)
        probes := by
  exact interactionIsolationConorm_pos_iff_pairwiseSeparating
    (formedCandidateResponseFamily readout p regions response hprob)
    probes hprobes

end

end UEOT.V3.Compression.CrossTrack
