import UEOT.V3.Compression.CrossTrack.ParentBindingStatic
import UEOT.V3.Compression.TransportCertificate

/-!
# Parent Binding Mechanism — PB4/PB5 dynamic bridge

M-TC transports assembly-state defect through a time-varying development
pipeline.  Parent-binding regularity converts that transported assembly defect
into a row-kernel defect, and Track-S residual isolation converts the latter
into long-run semantic error.
-/

namespace UEOT.V3.Compression.CrossTrack

open scoped BigOperators
open Filter
open UEOT.V3
open UEOT.V3.FiniteDobrushin
open UEOT.V3.Compression.InvariantSetGaugeInvariance
open UEOT.V3.Compression.TopologyChangingGoaL1ResidualConorm
open UEOT.V3.Compression.TransportCertificate

universe uA uS

noncomputable section

variable {A : Type uA} [PseudoMetricSpace A]
variable {S : Type uS} [Fintype S] [Nonempty S]
noncomputable local instance parentBindingDynamicDecidableEq : DecidableEq S :=
  Classical.decEq S

/-- The exact M-TC weighted finite-horizon envelope for an assembly-state
development pipeline. -/
noncomputable def bindingTransportEnvelope
    (L epsilon : ℕ → ℝ) (d0 : ℝ) (n : ℕ) : ℝ :=
  (∏ j ∈ Finset.range n, L j) * d0 +
    ∑ k ∈ Finset.range n,
      epsilon k * ∏ j ∈ Finset.Ico (k + 1) n, L j

/-- The existing M-TC development theorem, exposed with the PB envelope name. -/
theorem assemblyDist_le_bindingTransportEnvelope
    (theta thetaBar : ℕ → A)
    (Psi : ℕ → A → A)
    (L epsilon : ℕ → ℝ)
    (href : ∀ t, thetaBar (t + 1) = Psi t (thetaBar t))
    (hres : ∀ t, dist (theta (t + 1)) (Psi t (theta t)) ≤ epsilon t)
    (hlip : ∀ t x y, dist (Psi t x) (Psi t y) ≤ L t * dist x y)
    (hL0 : ∀ t, 0 ≤ L t)
    (n : ℕ) :
    dist (theta n) (thetaBar n) ≤
      bindingTransportEnvelope L epsilon (dist (theta 0) (thetaBar 0)) n := by
  exact development_pipeline_via_weighted_chain
    theta thetaBar Psi L epsilon href hres hlip hL0 n

/-- **PB4 — M-TC-generated parent semantic tracking.**

The assembly distance at time `n` is generated by M-TC from the initial
assembly defect and local development residuals.  A Lipschitz parent-dynamics
realization then turns that bound into the row-TV premise required by Track X.
No fresh transport principle is introduced here. -/
theorem parentSemanticTracking_via_MTC
    (theta thetaBar : ℕ → A)
    (Psi : ℕ → A → A)
    (L epsilon : ℕ → ℝ)
    (href : ∀ t, thetaBar (t + 1) = Psi t (thetaBar t))
    (hres : ∀ t, dist (theta (t + 1)) (Psi t (theta t)) ≤ epsilon t)
    (hlip : ∀ t x y, dist (Psi t x) (Psi t y) ≤ L t * dist x y)
    (hL0 : ∀ t, 0 ≤ L t)
    (K : A → Matrix S S ℝ)
    (hK : ∀ a, K a ∈ Matrix.rowStochastic ℝ S)
    (bind : ParentBindingLipschitz (fun a : A => a) K hK)
    (muBar mu : ℕ → stdSimplex ℝ S)
    (hmuBar : ∀ n,
      muBar n ∈ invariantLawSet (K (thetaBar n)) (hK (thetaBar n)))
    (hmu : ∀ n,
      mu n ∈ invariantLawSet (K (theta n)) (hK (theta n)))
    (hcard : 1 < Fintype.card S)
    (n : ℕ)
    (hisolation : 0 < l1ResidualConorm (K (thetaBar n))) :
    lawTV (muBar n) (mu n) ≤
      (bind.L *
        bindingTransportEnvelope L epsilon
          (dist (theta 0) (thetaBar 0)) n) /
        l1ResidualConorm (K (thetaBar n)) := by
  have hdist := assemblyDist_le_bindingTransportEnvelope
    theta thetaBar Psi L epsilon href hres hlip hL0 n
  have hrow : ∀ x,
      crossRowTV
        (K (thetaBar n)) (hK (thetaBar n))
        (K (theta n)) (hK (theta n)) x ≤
      bind.L *
        bindingTransportEnvelope L epsilon
          (dist (theta 0) (thetaBar 0)) n := by
    intro x
    calc
      crossRowTV
          (K (thetaBar n)) (hK (thetaBar n))
          (K (theta n)) (hK (theta n)) x
          ≤ bind.L * dist (thetaBar n) (theta n) :=
        bind.row_lipschitz (thetaBar n) (theta n) x
      _ ≤ bind.L *
          bindingTransportEnvelope L epsilon
            (dist (theta 0) (thetaBar 0)) n := by
        apply mul_le_mul_of_nonneg_left _ bind.L_nonneg
        simpa [dist_comm] using hdist
  exact suppliedInvariant_tracking
    (K (thetaBar n)) (hK (thetaBar n))
    (K (theta n)) (hK (theta n))
    (muBar n) (mu n) (hmuBar n) (hmu n)
    (bind.L *
      bindingTransportEnvelope L epsilon
        (dist (theta 0) (thetaBar 0)) n)
    hcard hisolation hrow

/-- Uniform residual isolation replaces the time-dependent source denominator
by one declared parent-semantic isolation floor. -/
theorem parentSemanticTracking_via_MTC_uniformIsolation
    (theta thetaBar : ℕ → A)
    (Psi : ℕ → A → A)
    (L epsilon : ℕ → ℝ)
    (href : ∀ t, thetaBar (t + 1) = Psi t (thetaBar t))
    (hres : ∀ t, dist (theta (t + 1)) (Psi t (theta t)) ≤ epsilon t)
    (hlip : ∀ t x y, dist (Psi t x) (Psi t y) ≤ L t * dist x y)
    (hL0 : ∀ t, 0 ≤ L t)
    (K : A → Matrix S S ℝ)
    (hK : ∀ a, K a ∈ Matrix.rowStochastic ℝ S)
    (bind : ParentBindingLipschitz (fun a : A => a) K hK)
    (muBar mu : ℕ → stdSimplex ℝ S)
    (hmuBar : ∀ n,
      muBar n ∈ invariantLawSet (K (thetaBar n)) (hK (thetaBar n)))
    (hmu : ∀ n,
      mu n ∈ invariantLawSet (K (theta n)) (hK (theta n)))
    (hcard : 1 < Fintype.card S)
    (kappaMin : ℝ)
    (hkappaMin : 0 < kappaMin)
    (hisolationFloor : ∀ n,
      kappaMin ≤ l1ResidualConorm (K (thetaBar n)))
    (n : ℕ) :
    lawTV (muBar n) (mu n) ≤
      (bind.L *
        bindingTransportEnvelope L epsilon
          (dist (theta 0) (thetaBar 0)) n) / kappaMin := by
  have hsourceIsolation : 0 < l1ResidualConorm (K (thetaBar n)) :=
    lt_of_lt_of_le hkappaMin (hisolationFloor n)
  have htrack := parentSemanticTracking_via_MTC
    theta thetaBar Psi L epsilon href hres hlip hL0
    K hK bind muBar mu hmuBar hmu hcard n hsourceIsolation
  have hdist := assemblyDist_le_bindingTransportEnvelope
    theta thetaBar Psi L epsilon href hres hlip hL0 n
  have henv0 : 0 ≤ bindingTransportEnvelope L epsilon
      (dist (theta 0) (thetaBar 0)) n :=
    (dist_nonneg.trans hdist)
  have hnum0 : 0 ≤ bind.L *
      bindingTransportEnvelope L epsilon
        (dist (theta 0) (thetaBar 0)) n :=
    mul_nonneg bind.L_nonneg henv0
  exact htrack.trans
    (div_le_div_of_nonneg_left hnum0 hkappaMin (hisolationFloor n))

/-- **PB5 — asymptotic semantic exactification.**

Whenever a nonnegative assembly-error envelope tends to zero and a fixed
positive isolation floor remains available, any semantic error controlled by
`L * delta / kappaMin` also tends to zero.  This is the asymptotic closure of
the PB3/PB4 bridge, not a claim that M-TC alone makes the assembly error decay.
-/
theorem parentSemanticTracking_tendsto_zero
    (muBar mu : ℕ → stdSimplex ℝ S)
    (delta : ℕ → ℝ)
    (Lbind kappaMin : ℝ)
    (hdelta : Tendsto delta atTop (nhds 0))
    (hbound : ∀ n,
      lawTV (muBar n) (mu n) ≤ Lbind * delta n / kappaMin) :
    Tendsto (fun n => lawTV (muBar n) (mu n)) atTop (nhds 0) := by
  apply squeeze_zero
  · intro n
    exact lawTV_nonneg _ _
  · exact hbound
  · have hmul : Tendsto (fun n => Lbind * delta n) atTop (nhds (Lbind * 0)) :=
      hdelta.const_mul Lbind
    have hdiv := hmul.div_const kappaMin
    simpa using hdiv

/-- Direct PB4 -> PB5 closure: if the exact M-TC assembly envelope tends to
zero while a uniform positive parent-semantic isolation floor persists, then
the stationary semantics of the actual and reference parent realizations
converge in total variation. -/
theorem parentSemanticTracking_via_MTC_tendsto_zero
    (theta thetaBar : ℕ → A)
    (Psi : ℕ → A → A)
    (L epsilon : ℕ → ℝ)
    (href : ∀ t, thetaBar (t + 1) = Psi t (thetaBar t))
    (hres : ∀ t, dist (theta (t + 1)) (Psi t (theta t)) ≤ epsilon t)
    (hlip : ∀ t x y, dist (Psi t x) (Psi t y) ≤ L t * dist x y)
    (hL0 : ∀ t, 0 ≤ L t)
    (K : A → Matrix S S ℝ)
    (hK : ∀ a, K a ∈ Matrix.rowStochastic ℝ S)
    (bind : ParentBindingLipschitz (fun a : A => a) K hK)
    (muBar mu : ℕ → stdSimplex ℝ S)
    (hmuBar : ∀ n,
      muBar n ∈ invariantLawSet (K (thetaBar n)) (hK (thetaBar n)))
    (hmu : ∀ n,
      mu n ∈ invariantLawSet (K (theta n)) (hK (theta n)))
    (hcard : 1 < Fintype.card S)
    (kappaMin : ℝ)
    (hkappaMin : 0 < kappaMin)
    (hisolationFloor : ∀ n,
      kappaMin ≤ l1ResidualConorm (K (thetaBar n)))
    (henvelope : Tendsto
      (fun n => bindingTransportEnvelope L epsilon
        (dist (theta 0) (thetaBar 0)) n)
      atTop (nhds 0)) :
    Tendsto (fun n => lawTV (muBar n) (mu n)) atTop (nhds 0) := by
  apply parentSemanticTracking_tendsto_zero
    muBar mu
    (fun n => bindingTransportEnvelope L epsilon
      (dist (theta 0) (thetaBar 0)) n)
    bind.L kappaMin henvelope
  intro n
  exact parentSemanticTracking_via_MTC_uniformIsolation
    theta thetaBar Psi L epsilon href hres hlip hL0
    K hK bind muBar mu hmuBar hmu hcard
    kappaMin hkappaMin hisolationFloor n

end

end UEOT.V3.Compression.CrossTrack
